### ISSUE TITLE
The outbound error response logging is needlessly verbose

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6024]
When the outbound scheduler attempts to send a payload over the network and something goes wrong (e.g. the target server 500s) we log out the entire error response:

https://github.com/medic/medic/blob/master/sentinel/src/schedule/outbound.js#L260
```js
    logger.error(`Failed to push ${medicDoc._id} to ${key}: %o`, err);
```

While this is delightfully general purpose (and this code path is used for all errors in that flow), the default output for responses is really massive and contains a bunch of unnecessary information that makes logs really hard to read.

We should reduce the amount of logging we do in that case, probably down to just the statuscode and response payload (if it exists), and if there is no statuscode because of some other problem (eg timeout) we just log that message and not the entire response object.

**Comment by dianabarsan** [comment]
Ready for AT on `6024-cleaner-errors`

**Comment by ngaruko** [comment]
LGTM. Error a lot shorter and concise. 
AT'd on `local` using the [text.it API](https://github.com/medic/cht-core/issues/6306#issuecomment-623823702).
1 - Tested without configuring couchdb credentials
**_On master_**
```[2020-06-23 02:52:59] 2020-06-23 02:52:59 ESC[31mERRORESC[39m: Failed to push 039cc7cd-4804-401e-92b7-d5a54eb74c5c to textit-patient: { Error: CouchDB config key 'medic-credentials/textit.in' has not been populated. See the Outbound documentation.
[2020-06-23 02:52:59]     at secureSettings.getCredentials.then.password (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/src/outbound.js:27:13)
[2020-06-23 02:52:59]     at <anonymous>
[2020-06-23 02:52:59]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2020-06-23 02:52:59]   [stack]: 'Error: CouchDB config key \'medic-credentials/textit.in\' has not been populated. See the Outbound documentation.\n    at secureSettings.getCredentials.then.password (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/src/outbound.js:27:13)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2020-06-23 02:52:59]   [message]: 'CouchDB config key \'medic-credentials/textit.in\' has not been populated. See the Outbound documentation.' }  ```

![image](https://user-images.githubusercontent.com/6979995/85356057-19a6b680-b562-11ea-9afd-70ee824b8aaf.png)

**_On the branch_** 
```[2020-06-23 03:11:59] 2020-06-23 03:11:59 ESC[31mERRORESC[39m: Failed to push 03
9cc7cd-4804-401e-92b7-d5a54eb74c5c to textit-patient: CouchDB config key 'medic-
credentials/textit.in' has not been populated. See the Outbound documentation.```

Other errors
**_On master_** 
```
[2020-06-23 03:23:16] 2020-06-23 03:23:16 ESC[31mERRORESC[39m: Failed to push f88e2fab-eb91-4645-80d1-50a8aa96ad3f to textit-patient: { Error: Mapping error for 'textit-patient/extra.chw._id' on source document 'f88e2fab-eb91-4645-80d1-50a8aa96ad3f': cannot find 'doc.parent.parent.contact._id' on source document
[2020-06-23 03:23:16]     at Object.keys.forEach.dest (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/src/outbound.js:76:13)
[2020-06-23 03:23:16]     at Array.forEach (<anonymous>)
[2020-06-23 03:23:16]     at mapDocumentToPayload (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/src/outbound.js:57:31)
[2020-06-23 03:23:16]     at Promise.resolve.then (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/src/outbound.js:206:21)
[2020-06-23 03:23:16]     at <anonymous>
[2020-06-23 03:23:16]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2020-06-23 03:23:16]   [stack]: 'Error: Mapping error for \'textit-patient/extra.chw._id\' on source document \'f88e2fab-eb91-4645-80d1-50a8aa96ad3f\': cannot find \'doc.parent.parent.contact._id\' on source document\n    at Object.keys.forEach.dest (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/src/outbound.js:76:13)\n    at Array.forEach (<anonymous>)\n    at mapDocumentToPayload (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/src/outbound.js:57:31)\n    at Promise.resolve.then (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/src/outbound.js:206:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2020-06-23 03:23:16]   [message]: 'Mapping error for \'textit-patient/extra.chw._id\' on source document \'f88e2fab-eb91-4645-80d1-50a8aa96ad3f\': cannot find \'doc.parent.parent.contact._id\' on source document' } 
```
**_On branch_**
```
[2020-06-23 03:13:29] 2020-06-23 03:13:29 ESC[31mERRORESC[39m: Failed to push 6187dfe1-ecf5-4e2a-bbe4-9fa8f2c226a3 to textit-patient: Mapping error for 'textit-patient/extra.chw._id' on source document '6187dfe1-ecf5-4e2a-bbe4-9fa8f2c226a3': cannot find 'doc.parent.parent.contact._id' on source document```

**Comment by garethbowen** [comment]
@ngaruko Should this be in the "ready to merge" state?

**Comment by SCdF** [comment]
Merged

**Comment by SCdF** [comment]
According to this comment: https://github.com/medic/cht-core/issues/6419#issuecomment-655171376

We aren't correctly catching request issues

**Comment by SCdF** [comment]
@ngaruko I cannot reproduce your error in the logs. It very much looks like it's from a much older version of master, prior to the log work done in this ticket.

I used the latest master as of the time of this comment. I created the following outbound config:
```json
    "outbound": {
      "test_outbound_errors": {
        "relevant_to": "doc.name === 'test'",
        "mapping": {
          "id": "doc._id",
          "rev": "doc._rev"
        },
        "destination": {
          "base_url": "http://localhost:3333",
          "path": "/api/v1/patient/badtime"
        }
      }
    },
```

I used a mock JS file to return the same style of error that you got, that looks like this:

```js
const express = require('express'),
      bodyParser = require('body-parser');

const app = express();
const port = 3333;

const log = (title, req) => {
  console.log(new Date(), title, req.headers, req.body);
}

app.use(bodyParser.json()); // for parsing application/json
app.use(bodyParser.urlencoded({ extended: true })); // for parsing application/x-www-form-urlencoded

// <snip unimportant stuff>

app.post('/api/v1/patient/badtime', (req, res) => {
  log('badtime', req);

  res
    .status(400)
    .send({flow:['No such object: 94d7e4e1-775b-4162-b2bd-cd299e7ba075']});
});

app.listen(port, () => console.log(`SIH mock up on ${port}`));
```

When I engage with this config by creating a person with the name `test` this is what I see in the logs:
```
2020-07-08 13:44:39 DEBUG: About to send outbound request
2020-07-08 13:44:39 DEBUG: {
  "url": "http://localhost:3333/api/v1/patient/badtime",
  "body": {
    "id": "60f8b8f3-1aaa-4d49-b82f-b5889a091f09",
    "rev": "2-eb7bd59433f79b2d9c1b16b76243ff91"
  },
  "json": true,
  "timeout": 10000
}
2020-07-08 13:44:39 ERROR: Failed to push 60f8b8f3-1aaa-4d49-b82f-b5889a091f09 to test_outbound_errors, server responsed with 400
2020-07-08 13:44:39 ERROR: Response body: {"flow":["No such object: 94d7e4e1-775b-4162-b2bd-cd299e7ba075"]}
2020-07-08 13:44:39 INFO: task:outbound:60f8b8f3-1aaa-4d49-b82f-b5889a091f09 already exists, ignoring
```

Note that the DEBUG lines will not appear in production, so it's really only those two ERROR lines.

This is what I'd expect to see looking at the code as well: in the [two](https://github.com/medic/cht-core/blob/master/shared-libs/transitions/src/transitions/mark_for_outbound.js#L46-L49) [places](https://github.com/medic/cht-core/blob/master/sentinel/src/schedule/outbound.js#L131-L134) where we call outbound code that might error we intentionally ignore the result of the catch because we know it gets logged internally.

Can you take another look at this, and if you can still reproduce it please comment with detailed reproduction steps (or we can jump on a call)

**Comment by ngaruko** [comment]
@SCdF Seems to work well when I switch to this branch (`6024-cleaner-errors`)- but not on `master` atm. Must be a glitch in my environment as this was merged last month, and was expecting to be clean log in `master` ... 
```
[2020-07-08 22:47:06] 2020-07-08 22:47:06 ESC[31mERRORESC[39m: Failed to push e8dd7763-d33e-4ae6-b8aa-e3ab236c43ae to textit-patient, server responsed with 400 
[2020-07-08 22:47:06] 2020-07-08 22:47:06 ESC[31mERRORESC[39m: Response body: {"flow":["No such object: 039e2314-9bd2-4710-8b2d-d3d72a1745cd-X"]} 
```

**Comment by SCdF** [comment]
Talked to Bede, this was a mistake in his retesting, and it works as expected
