### ISSUE TITLE
medic-conf errors when trying to build the default config

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6115]
**Describe the bug**
When running medic-conf to compile and deploy the default (CHT reference app) configuration an error is thrown and the configuration is not deployed.

**To Reproduce**
1. Go to /config/default
2. Execute `medic-conf --local`
3. See error

**Expected behavior**
No error is thrown. Config is compiled and deployed.

**Logs**
```
    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      ./contact-summary.js (277 KiB)
    
    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (277 KiB)
          ./contact-summary.js
    
    
    WARNING in webpack performance recommendations: 
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/ 
ERROR Error: Webpack warnings when building contact-summary
    at compiler.run (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/src/lib/package-lib.js:100:23)
    at finalCallback (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at runWithDependencies.err (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/MultiCompiler.js:277:6)
    at done (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at err (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/MultiCompiler.js:188:7)
    at compiler.run (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/MultiCompiler.js:270:7)
    at finalCallback (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/Compiler.js:306:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/Compiler.js:499:39)
    at emitAssets.err (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/Compiler.js:298:10)
    at hooks.afterEmit.callAsync.err (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/webpack/lib/Compiler.js:485:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/gareth/.nvm/versions/node/v10.16.0/lib/node_modules/medic-conf/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1) 
```

**Environment**
- Instance: local
- Browser: N/A
- Client platform: Ubuntu
- App: medic-conf, webapp
- Version: 3.7.0, master

**Additional context**
The workaround is to turn on debug, eg:

```
medic-conf --local -- --debug
```

This isn't great because it leaves the configuration unminified but helps in development.

**Comment by dianabarsan** [comment]
Possibly related: https://github.com/medic/medic-conf/issues/224

**Comment by wtekeu** [comment]
Ready for AT: `6115-medic-conf-webpack-error`

**Comment by ngaruko** [comment]
LGTM with this one.
However, there are other errors, most probably linked to eslint errors and warnings. Will continue investigating in this and raise a different issue if needed.
```
 /Users/bede/Medic/medic-dev/cht-core/config/default/targets.js
      2:7  warning  'FIVE_YEARS_IN_DAYS' is assigned a value but never used  no-unused-vars
      4:3  warning  'today' is assigned a value but never used               no-unused-vars
      5:3  warning  'addDays' is assigned a value but never used             no-unused-vars
    
    ✖ 3 problems (0 errors, 3 warnings)
    
     @ /Users/bede/Medic/medic-dev/medic-conf/src/nools/lib.js 4:14-35 
ERROR Error: Webpack warnings when building nools
    at /Users/bede/Medic/medic-dev/medic-conf/src/lib/package-lib.js:103:23
    at finalCallback (/Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/Users/bede/Medic/medic-dev/medic-conf/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bede/Medic/medic-dev/medic-conf/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/bede/Medic/medic-dev/medic-conf/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/Compiler.js:298:10
    at /Users/bede/Medic/medic-dev/medic-conf/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bede/Medic/medic-dev/medic-conf/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1) 
```
Since these errors are showing ev

**Comment by kennsippell** [comment]
Just saw this official package supported by moment for this. Likely not worth revisiting, but an interesting find that I thought I'd post.
https://www.npmjs.com/package/moment-locales-webpack-plugin
