### ISSUE TITLE
Users with a lot of large docs to replicate continuously fail

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6143]
**Describe the bug**

When replicating we use the default PouchDB batch size of 100 so we can efficiently send large numbers of docs in one request. If the docs include images (eg: MRDT photos) then this request can get large. On the server API limits the JSON parser to 32MB after which we respond with an error. This means if the user accumulates more than 32MB of data to replicate the request fails consistently and the user can never recover.

**To Reproduce**
1. Go offline
2. Create at least 100 reports with lots of attachments (high quality photos will work). Make sure there's at least 400kB of data per report so you exceed the 32MB limit.
3. Go online again
4. Click sync
5. See the error in the console
6. Check the server and see the docs haven't synced

**Expected behavior**
There may be errors logged but the docs should sync to the server.

**Logs**
API Logs
```
REQ 2ce77879-2a5c-48f0-a174-4a2d1d900418 ::1 - GET /medic/_changes?timeout=600000&style=all_docs&heartbeat=10000&since=5202-g1AAAAJyeJyd0T0OgjAUB_AKJLB6Aj0C5UuYZDMx8QzaljYNQRnUWa_hpIP30JvoLRyx9BEnYlKW16Qv75d_-yqEkCftAo1ZfWSyoHlVM1LJen-oVMsiiE6apimlTVZbdeFGMc7SMOwb-MPQqap0DhJFyLlrTMxSxrPAFMtbbN3FWkKsMBEsIqbSppVOv1i2pzEeJzimkSG2c1RFZ3Uo7wqgu9BggAn2UzEIvAH4aN960RrFnBcBHaQ9QXtBPOujQcwTEfqmawDwDWD3gaNUgyQTnGd-32j5BbAJw5A&limit=100 HTTP/1.1
REQ 016e62e6-3eac-46a9-a873-48152fe8ea88 ::1 - POST /medic/_bulk_docs HTTP/1.1
2019-12-02 14:59:58 ERROR: Server error: { PayloadTooLargeError: request entity too large
    at readStream (/home/gareth/src/medic/cht-core/api/node_modules/raw-body/index.js:155:17)
    at getRawBody (/home/gareth/src/medic/cht-core/api/node_modules/raw-body/index.js:108:12)
    at read (/home/gareth/src/medic/cht-core/api/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/home/gareth/src/medic/cht-core/api/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/layer.js:95:5)
    at /home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/index.js:281:22
    at param (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/index.js:354:14)
  [stack]:
   'PayloadTooLargeError: request entity too large\n    at readStream (/home/gareth/src/medic/cht-core/api/node_modules/raw-body/index.js:155:17)\n    at getRawBody (/home/gareth/src/medic/cht-core/api/node_modules/raw-body/index.js:108:12)\n    at read (/home/gareth/src/medic/cht-core/api/node_modules/body-parser/lib/read.js:77:3)\n    at jsonParser (/home/gareth/src/medic/cht-core/api/node_modules/body-parser/lib/types/json.js:135:5)\n    at Layer.handle [as handle_request] (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/gareth/src/medic/cht-core/api/node_modules/express/lib/router/index.js:354:14)',
  message: 'request entity too large',
  [name]: 'PayloadTooLargeError',
  expected: 9350,
  length: 9350,
  limit: 100,
  type: 'entity.too.large' } 
RES 016e62e6-3eac-46a9-a873-48152fe8ea88 ::1 - POST /medic/_bulk_docs HTTP/1.1 500 35 12.784 ms
```

Browser logs:

![Screenshot from 2019-12-02 15-01-25](https://user-images.githubusercontent.com/2064938/69925363-ab8e9980-1514-11ea-9434-21c5485fd51b.png)

**Screenshots**

**Environment**
- Instance: MUSO
- Browser: Chrome
- Client platform: Ubuntu
- App: webapp and API
- Version: master, 3.7.2

**Additional context**
Initially raised in https://github.com/medic/medic-projects/issues/7075

**Comment by dianabarsan** [comment]
Ready for AT on `6143-retry-replication`

**Comment by ngaruko** [comment]
LGTM
