### ISSUE TITLE
update medic's pyxform to support for custom contact types

### ISSUE THREAD

**Issue by derickl** [medic/cht-core#6182]
From 3.7 with the introduction of configurable hierarchy, we now support any number of place and person types (beyond the historically supported ones: `person, clinic, health_center, district_hospital`).

Unfortunately the new contact types are not supported in our fork of pyxform as these have to be set question types in pyxform. Given the variability of these contact definitions, we need to have a way of dynamically adding question types in pyxform when converting forms or settle (initially) on a set of contact types that will initially fulfil the needs of projects that need more than 3 levels of hierarch.

The old contact types are currently defined here: https://github.com/medic/pyxform/blob/6f7909d564e104640562241da4cf8393036243ad/pyxform/question_type_dictionary.py#L158-#L189

Given that we've essentially settled on XLSForms as the approach to form definitions, we really do need to figure. 

One dirty workaround is for folks to modify their local copies of `pyxform/question_type_dictionary.py` and add the the new question types.

cc @garethbowen

**Comment by garethbowen** [comment]
Look at this at the same time as #3538

**Comment by kennsippell** [comment]
Would you solve this by allowing `db:*` in PyxForm? Or do we want to only allow valid contact_types as defined in app_settings.json?

**Comment by kennsippell** [comment]
Working around this issue was required for MSF-Niger Covid response via this branch https://github.com/medic/pyxform/tree/msf-niger.

**Comment by abbyad** [comment]
Would be nice if db:* could be handled in a standard ODK XForm way, so that in the future we wouldn't need a custom pyxform for this.

**Comment by garethbowen** [comment]
Is there any other way that the object type can be passed so the field type could be just `db-object` (or something) and Core could fetch the type from a different attribute? That would make the whole solution much simpler.

**Comment by abbyad** [comment]
Bringing in notes from discussion with @garethbowen. It appears that the need for XLSForm types for each db-object type is not needed. The only reason it is used now is to [inform the search in the Enketo widget](https://github.com/medic/cht-core/blob/2c1db1618bdafc5ec14c3a27aa4a37249fcc1b4a/webapp/src/js/enketo/widgets/db-object-widget.js#L64-L76).

Current db-object fields could instead be of type `string` with `db-object` appearance. The db object type (eg "person") could specified in the appearance as well, with a known prefix (eg `db-type-person`). The code would then need to pull out the type from the class list accordingly.

**Comment by garethbowen** [comment]
We should probably think about changing the name from `db-object` to `contact-search` or something to make it clear it is only designed to work with contacts.

**Comment by abbyad** [comment]
Ya, good idea. If we are changing the name I'll throw `select-contact` into the ring!

**Comment by garethbowen** [comment]
Example error output:

```
Traceback (most recent call last):
  File "/usr/local/bin/xls2xform-medic", line 11, in <module>
    load_entry_point('pyxform-medic==0.9.24', 'console_scripts', 'xls2xform-medic')()
  File "/usr/local/lib/python2.7/dist-packages/pyxform/xls2xform.py", line 88, in main_cli
    args.skip_validate)
  File "/usr/local/lib/python2.7/dist-packages/pyxform/xls2xform.py", line 25, in xls2xform_convert
    xform_path, validate=validate, warnings=warnings)
  File "/usr/local/lib/python2.7/dist-packages/pyxform/survey.py", line 548, in print_xform_to_file
    raise e
pyxform.errors.PyXFormError: Unknown question type 'select-contact'.
```

**Comment by garethbowen** [comment]
The pyxform tests are failing but it looks like they fail on `master` too so I'm ignoring them...

**Comment by garethbowen** [comment]
Ready for AT in `6182-pyxform-configurable-hierarchy-support`.

pyxform didn't end up changing at all. Once you install this branch, read the [documentation change](https://github.com/medic/medic-docs/pull/219) and reconfigure forms to use the new type and appearance. Make sure the old way works for the hardcoded hierarchies, and the new way works. Make sure you can specify 0, 1, or many types (as documented).

**Comment by ngaruko** [comment]
Tested with the [pregnancy form](https://github.com/medic/cht-core/blob/6182-pyxform-configurable-hierarchy-support/config/default/forms/app/pregnancy.xml), with appearance set to `select-contact type-{{contact_type}}`. 
Not sure if we should think of handing invalid `select-contact` types (or no type entered) in the UI @garethbowen ?
Just to notify the user what went wrong. 
![image](https://user-images.githubusercontent.com/6979995/87659854-455c3b80-c7b2-11ea-9d54-aa6a9f0cfbd0.png)

**Comment by garethbowen** [comment]
Possibly... this affected the old way of defining contact types too so I agree it shouldn't block this issue. Maybe raise a new issue in cht-core so it's more obvious when the search is always going to return no results?

**Comment by garethbowen** [comment]
Documentation and cht-core code merged.
