### ISSUE TITLE
The update settings API reports success but has no effect

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6315]
**Describe the bug**
Uploading app settings via medic-conf latest 3.1.0 results in "success", but the settings doc is not updated.

**To Reproduce**
1. `cd medic-projects/brac-uganda`
1. `medic-conf --local upload-app-settings`

**Expected behavior**
This is an invalid app_settings file (it was valid for 2.10), so this should probably fail.
But the API returns `{ success: true }`, yet the `_rev` for the settings doc doesn't change and the content of the app_settings file doesn't reflect the uploaded file.

**Logs**

The requests are hitting the server, so it likely isn't an issue in medic-conf.
```
REQ 5cee3543-4d00-4274-85a5-0391e4b62ac8 ::ffff:127.0.0.1 admin PUT /medic/_design/medic/_rewrite/update_settings/medic?replace=1 HTTP/1.1
2020-03-18 18:56:47 INFO: Updating settings with new defaults 
RES 5cee3543-4d00-4274-85a5-0391e4b62ac8 ::ffff:127.0.0.1 admin PUT /medic/_design/medic/_rewrite/update_settings/medic?replace=1 HTTP/1.1 200 16 276.857 ms
```

**Screenshots**

**Environment**
- Instance: dev machine
- Browser: Chrome
- Client platform: Bionic
- App: webapp
- Version: 3.8.0

**Additional context**

**Comment by garethbowen** [comment]
This may be partially solved by #4783 which should respond correctly when an invalid (or outdated) settings file is provided. Confirm that's true.

There's another similar case which is we don't give any indication if we detect the settings haven't changed. In this case we don't write to the db because we don't want users to download the settings doc when it hasn't changed. Update the response to make this clear, eg:

```json
{
  "success": true,
  "updated": false
}
```

**Comment by dianabarsan** [comment]
I haven't been able to replicate this against current `master`.

If I try to upload invalid json, API throws an error that I end up seeing as the result of the `medic-conf` command:

```
medic-conf --local upload-app-settings
INFO Processing config in default.
INFO Actions:
     - upload-app-settings
INFO Starting action: upload-app-settings…
ERROR StatusCodeError: 500 - "Server error"
    at new StatusCodeError (/home/diana/projects/medic-conf/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/diana/projects/medic-conf/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/diana/projects/medic-conf/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/diana/projects/medic-conf/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/home/diana/projects/medic-conf/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/home/diana/projects/medic-conf/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
```

And in API, this request fails at body-parser level:
```
REQ e2c57f3c-6367-42d5-aae2-afa4679d826b ::ffff:127.0.0.1 admin PUT /medic/_design/medic/_rewrite/update_settings/medic?replace=1 HTTP/1.1
2020-04-08 10:22:18 ERROR: Server error: SyntaxError: Unexpected token d in JSON at position 282664
    at JSON.parse (<anonymous>)
    at parse (/home/diana/projects/medic/api/node_modules/body-parser/lib/types/json.js:89:19)
    at /home/diana/projects/medic/api/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/diana/projects/medic/api/node_modules/raw-body/index.js:224:16)
    at done (/home/diana/projects/medic/api/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/diana/projects/medic/api/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

If I upload valid json that is different than what exists on the server, I get success in both places:

```
medic-conf --local upload-app-settings
INFO Processing config in default.
INFO Actions:
     - upload-app-settings
INFO Starting action: upload-app-settings…
INFO upload-app-settings complete.
```

```
REQ 497975a7-ba61-4f8a-bdb5-daca139a6046 ::ffff:127.0.0.1 admin PUT /medic/_design/medic/_rewrite/update_settings/medic?replace=1 HTTP/1.1
2020-04-08 10:25:30 INFO: Updating settings with new defaults
RES 497975a7-ba61-4f8a-bdb5-daca139a6046 ::ffff:127.0.0.1 admin PUT /medic/_design/medic/_rewrite/update_settings/medic?replace=1 HTTP/1.1 200 16 187.436 ms
2020-04-08 10:25:30 INFO: Detected settings change - reloading
```

If I upload valid json that is **not** different than what exists on the server, I get success in `medic-conf` and no update triggered in api:

```
medic-conf --local upload-app-settings
INFO Processing config in default.
INFO Actions:
     - upload-app-settings
INFO Starting action: upload-app-settings…
INFO upload-app-settings complete.
```

```
REQ 064d72e2-b21f-4f0a-8845-859e7071a7cf ::ffff:127.0.0.1 admin PUT /medic/_design/medic/_rewrite/update_settings/medic?replace=1 HTTP/1.1
RES 064d72e2-b21f-4f0a-8845-859e7071a7cf ::ffff:127.0.0.1 admin PUT /medic/_design/medic/_rewrite/update_settings/medic?replace=1 HTTP/1.1 200 16 16.625 ms
```

I'm currently in the process of updating API so it responds with `success` and `updated` - as @garethbowen suggested.

**Comment by garethbowen** [comment]
Ready for AT.

The cht-core branch `6315-api-settings-responses` contains the API changes which can be tested by CURLing the `/api/v1/settings` API directly. There is updated documentation for this endpoint in the branch.

The medic-conf branch `6315-api-settings-update-param` contains a change to log out whether or not the settings were updated. If this is run against `master` it shouldn't output anything, but if both branches are used together you should see a message about whether or not the settings were actually changed.

**Comment by ngaruko** [comment]
**LGTM**
Added a default language and modified country code and gateway number in `app_settings` and ran `upload-app-settings` .

**Before**
![image](https://user-images.githubusercontent.com/6979995/79625671-a3ab5b00-817e-11ea-8b4d-d1e47772b9ee.png)


**After**
![image](https://user-images.githubusercontent.com/6979995/79625714-e10fe880-817e-11ea-8fd2-32c8f36ad2c5.png)

Back to @dianabarsan to merge!

**Comment by dianabarsan** [comment]
Merged into `master`.
