### ISSUE TITLE
tasks.js containing a url in code or comments causes crash in nools

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6506]
**Overview**
This tasks.js file
```
module.exports = [{
  name: 'dldj',
  icon: 'follow-up',
  title: 'task.whatever',
  appliesTo: 'reports',
  appliesIf: () => 'http://www.foo.com',
  appliesToType: ['pregnancy'],
  actions: [{ form: 'referral_follow_up' }],
  events: [{ days: 0, start: 3, end: 7 }],
  resolvedIf: () => false,
},];
```

Causes crash with stack below.

**To Reproduce**
1. Update tasks.js to include text above
2. medic-conf compile-app-settings upload-app-settings --local
3. Load tasks tab

**Expected behavior**
No crash

**Logs**
```
Error: Invalid rule definition 
Unable to match { in {   when { c: Contact } then { 
  ...
}
      at parse (node_modules/nools/lib/parser/nools/nool.parser.js:24:27)
      at Object.exports.parse (node_modules/nools/lib/parser/nools/nool.parser.js:37:5)
      at Object.exports.parseRuleSet (node_modules/nools/lib/parser/index.js:15:27)
      at Object.exports.parse (node_modules/nools/lib/compile/index.js:144:19)
      at parse (node_modules/nools/lib/index.js:26:23)
      at Object.exports.compile (node_modules/nools/lib/index.js:57:16)
      at compileNools (src/get-nools-instances.js:45:36)
      at doGetInstances (src/get-nools-instances.js:50:44)
      at getInstances (src/get-nools-instances.js:9:12)
      at Harness.getTasks (src/harness.js:271:29)
      at Context.it (test/moment/test.js:18:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Ubuntu Bionic
- App: medic-conf + cht-core + nools
- Version: master (3.10)

**Comment by garethbowen** [comment]
Definitely should fix this bug.

I'm curious though, why are you checking a URL? Are you branching based on dev/app versions? I'm wondering if there's also a feature we could add here.

**Comment by kennsippell** [comment]
I believe [this is the line here](https://github.com/noolsjs/nools/blob/master/lib/parser/nools/nool.parser.js#L10) @peter-ochieng. Looks like it assumes any `//` is a comment and removes everything after it... Unsure if that can be removed? Or how you'd appropriately patch that regex. Gl!

I've never actually had to use a string literal in my nools code. Not branching based on dev/prod urls. I was using some code that included a link to help documentation in an error string.

**Comment by peter-ochieng** [comment]
Thanks @kennsippell for the link, am currently working on that regex patch then I'll see how to apply it.

**Comment by garethbowen** [comment]
Instead of patching nools I think it'd be better if we could find a way to escape the characters, either in documentation or automatically in medic-conf.

**Comment by garethbowen** [comment]
Moved to 3.11.0 so it doesn't block 3.10.0

**Comment by dianabarsan** [comment]
There's been much debate around this, mainly in this discussion here https://github.com/medic/cht-conf/pull/354#discussion_r475067356 and here https://github.com/medic/cht-core/pull/6527 . 

Please correct me if I'm wrong, but the conclusion is that:
- parties are in agreement that a fixing patch should be cht-conf side instead of cht-core side
- failing the config when comments exist is not desirable, as it might block using external libraries
- dropping Nools fixes this, but that's scheduled for CHT 5.0, which has no set delivery date. 

I'm wondering what is expected to be done for this in 3.14. 

Following @kennsippell 's recommendation, we could tag this as `blocked` and move it to 5.0, to be adressed when Nools is dropped.

**Comment by njogz** [comment]
@dianabarsan I agree with marking this as blocked until Nools is dropped.

**Comment by kennsippell** [comment]
This is ready for testing. @garethbowen Would you help put it in an appropriate product board?

Details at https://github.com/medic/cht-conf/issues/225#issuecomment-1475033726

**Comment by garethbowen** [comment]
Done.

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

#### Reproducible using `cht-core:master` and `cht-conf:main` ✅ 

Adding the task config provided by Kenn the app crashes.

<details>
<summary>task.js</summary> 

```.js
module.exports = [
...
{
  name: 'dldj',
  icon: 'follow-up',
  title: 'task.whatever',
  appliesTo: 'reports',
  appliesIf: () => 'http://www.foo.com',
  appliesToType: ['pregnancy'],
  actions: [{ form: 'referral_follow_up' }],
  events: [{ days: 0, start: 3, end: 7 }],
  resolvedIf: () => false,
}
];
```

</details>

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233186040-223b9bb6-aa1c-4b7a-b8c0-9f9c5eae4056.png)

</details>

---

#### Test 1 - Sanity check ❌ 

**cht-core version:** `master`
**cht-conf version:** `225-no-nools` 

I had two tasks already created (see image tasks_created) and when I uploaded the default [task.js](https://github.com/medic/cht-core/blob/master/config/default/tasks.js) file the app crashed and it shows the following error.

<details>
<summary>Image tasks_created</summary> 

![image](https://user-images.githubusercontent.com/94494491/233211179-5755870e-24b2-405a-aa23-1d7c2779d4af.png)

</details>

<details>
<summary>Error log</summary> 

```
Error getting tasks for all contacts Error: Error parsing !function(e){
...
}
 at A (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2298980)
    at M.parse (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2299281)
    at M.parseRuleSet (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2298672)
    at M.parse (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2218639)
    at R (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2242941)
    at M.compile (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2243259)
    at Object.initialize (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2340443)
    at Object.initialize (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2335652)
    at Object.initialize (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2332657)
    at main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:674983
```

</details>

<details>
<summary>Error image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233212614-10cc3230-ce65-48b8-b611-14904b782085.png)


</details>

---

#### Test 2 - Sanity check ✅ 

**cht-core version:** `noNools `
**cht-conf version:** `main` 

Uploading the default task config and generating pregnancy tasks worked as expected

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233228944-0424c693-ec53-4346-abb0-f378449413e8.png)

</details>

---

#### Test 3 - Fix ✅ 

**cht-core version:** `noNools `
**cht-conf version:** `225-no-nools` 

Uploading the default task config and generating pregnancy tasks worked as expected.


<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233229150-44d5ff00-9df1-4a59-9e7d-b11dc2982a5a.png)

</details>

And adding the task config provided by Kenn the app works as expected

<details>
<summary>task.js</summary> 

```.js
module.exports = [
...
{
  name: 'dldj',
  icon: 'follow-up',
  title: 'task.whatever',
  appliesTo: 'reports',
  appliesIf: () => 'http://www.foo.com',
  appliesToType: ['pregnancy'],
  actions: [{ form: 'referral_follow_up' }],
  events: [{ days: 0, start: 3, end: 7 }],
  resolvedIf: () => false,
}
];
```

</details>

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233229357-30d32039-a891-41bd-87cd-2cc87c328666.png)

</details>

---

Test failed :x:
Moving the ticket back to `In Progress`.
@kennsippell can you please check?

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

#### Test 1 - Sanity check ✅ 

**cht-core version:** `master`
**cht-conf version:** `225-no-nools` 


Uploading the default task config and generating pregnancy tasks worked as expected

<details>
<summary>Image attached</summary> 

<img width="689" alt="image" src="https://user-images.githubusercontent.com/94494491/234388517-11333b00-18c0-41e7-a1e2-1b8efc1eb6c5.png">

</details>

---

#### Test 2 - Sanity check ✅ 

**cht-core version:** `noNools `
**cht-conf version:** `main` 

Uploading the default task config and generating pregnancy tasks worked as expected

<details>
<summary>Image attached</summary> 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/94494491/234392990-2615f197-5448-4a47-87d8-6f320c2d87a9.png">


</details>

---

#### Test 3 - Fix ✅ 

**cht-core version:** `noNools `
**cht-conf version:** `225-no-nools` 

Uploading the default task config and generating pregnancy tasks worked as expected.


<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233229150-44d5ff00-9df1-4a59-9e7d-b11dc2982a5a.png)

</details>

And adding the task config provided by Kenn the app works as expected

<details>
<summary>task.js</summary> 

```.js
module.exports = [
...
{
  name: 'dldj',
  icon: 'follow-up',
  title: 'task.whatever',
  appliesTo: 'reports',
  appliesIf: () => 'http://www.foo.com',
  appliesToType: ['pregnancy'],
  actions: [{ form: 'referral_follow_up' }],
  events: [{ days: 0, start: 3, end: 7 }],
  resolvedIf: () => false,
}
];
```

</details>

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/234395020-5c1bb1ac-d0b6-4ffa-b44a-fa22a4b9f1fa.png)

</details>

---

Test passed successfully. :white_check_mark:
Moving the ticket to `Ready to Merge`
@kennsippell

**Comment by tatilepizs** [comment]
I did a quick test after the [last commit](https://github.com/medic/cht-core/pull/8065/commits/8a8f301fec1efcfe9db226351ed13d776def6d8c) and everything is working as expected.

Ready to merge 🚢 🚢
