### ISSUE TITLE
Flaky test: token login should redirect the user to the app if already logged in

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6605]
**Describe the issue**
I've seen a [few builds](https://travis-ci.org/github/medic/cht-core/builds/719775504) fail with this error:

```
  token login
    [31mâœ— should redirect the user to the app if already logged in[39m (3 secs)
      [31m- [39m[31mFailed: stale element reference: element is not attached to the page document[39m
      [31m  (Session info: headless chrome=84.0.4147.135)[39m
      [31m  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.15.0-1077-gcp x86_64)[39m
        (Session info: headless chrome=84.0.4147.135)
        (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.15.0-1077-gcp x86_64)
          at Object.checkLegacyResponse (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/error.js:546:15)
          at parseHttpResponse (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/http.js:509:13)
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/http.js:441:30
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
      From: Task: WebElement.isDisplayed()
          at thenableWebDriverProxy.schedule (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
          at WebElement.schedule_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
          at WebElement.isDisplayed (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/webdriver.js:2362:17)
          at actionFn (/home/travis/build/medic/cht-core/node_modules/protractor/built/element.js:89:44)
          at Array.map (<anonymous>)
          at /home/travis/build/medic/cht-core/node_modules/protractor/built/element.js:461:65
          at ManagedPromise.invokeCallback_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2927:27
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:668:7
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)Error
          at ElementArrayFinder.applyAction_ (/home/travis/build/medic/cht-core/node_modules/protractor/built/element.js:459:27)
          at ElementArrayFinder.<computed> [as isDisplayed] (/home/travis/build/medic/cht-core/node_modules/protractor/built/element.js:91:29)
          at ElementFinder.<computed> [as isDisplayed] (/home/travis/build/medic/cht-core/node_modules/protractor/built/element.js:831:22)
          at /home/travis/build/medic/cht-core/tests/helper.js:235:10
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/webdriver.js:938:14
          at TaskQueue.execute_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2974:25
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:668:7
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
      From: Task: <anonymous>
          at pollCondition (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2195:19)
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2191:7
          at new ManagedPromise (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:1077:7)
          at ControlFlow.promise (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2505:12)
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2190:22
          at TaskQueue.execute_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2927:27
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:668:7
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
      From: Task: <anonymous wait>
          at scheduleWait (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2188:20)
          at ControlFlow.wait (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2517:12)
          at thenableWebDriverProxy.wait (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
          at run (/home/travis/build/medic/cht-core/node_modules/protractor/built/browser.js:59:33)
          at ProtractorBrowser.to.<computed> [as wait] (/home/travis/build/medic/cht-core/node_modules/protractor/built/browser.js:67:16)
          at Object.waitElementToDisappear (/home/travis/build/medic/cht-core/tests/helper.js:233:13)
          at waitForLoaderToDisappear (/home/travis/build/medic/cht-core/tests/e2e/login/token-login.spec.js:66:14)
          at UserContext.<anonymous> (/home/travis/build/medic/cht-core/tests/e2e/login/token-login.spec.js:76:5)
          at /home/travis/build/medic/cht-core/node_modules/jasminewd2/index.js:112:25
          at new ManagedPromise (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:1077:7)
          at ControlFlow.promise (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2505:12)
          at schedulerExecute (/home/travis/build/medic/cht-core/node_modules/jasminewd2/index.js:95:18)
          at TaskQueue.execute_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2974:25
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:668:7
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
      From: Task: Run it("should redirect the user to the app if already logged in") in control flow
          at UserContext.<anonymous> (/home/travis/build/medic/cht-core/node_modules/jasminewd2/index.js:94:19)
          at /home/travis/build/medic/cht-core/node_modules/jasminewd2/index.js:64:48
          at ControlFlow.emit (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/events.js:62:21)
          at ControlFlow.shutdown_ (/home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2674:10)
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2599:53
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:2728:9
          at /home/travis/build/medic/cht-core/node_modules/selenium-webdriver/lib/promise.js:668:7
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
      From asynchronous test: 
      Error
          at Suite.<anonymous> (/home/travis/build/medic/cht-core/tests/e2e/login/token-login.spec.js:72:3)
          at Object.<anonymous> (/home/travis/build/medic/cht-core/tests/e2e/login/token-login.spec.js:45:1)
          at Module._compile (internal/modules/cjs/loader.js:1137:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
          at Module.load (/home/travis/build/medic/cht-core/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
          at Function.Module._load (internal/modules/cjs/loader.js:878:14)
          at Module.require (internal/modules/cjs/loader.js:1025:19)
          at require (internal/modules/cjs/helpers.js:72:18)
          at Array.forEach (<anonymous>)
          at Function.promise (/home/travis/build/medic/cht-core/node_modules/q/q.js:682:9)
          at _fulfilled (/home/travis/build/medic/cht-core/node_modules/q/q.js:834:54)
          at /home/travis/build/medic/cht-core/node_modules/q/q.js:863:30
          at Promise.promise.promiseDispatch (/home/travis/build/medic/cht-core/node_modules/q/q.js:796:13)
          at /home/travis/build/medic/cht-core/node_modules/q/q.js:604:44
          at runSingle (/home/travis/build/medic/cht-core/node_modules/q/q.js:137:13)
          at flush (/home/travis/build/medic/cht-core/node_modules/q/q.js:125:13)
          at processTicksAndRejections (internal/process/task_queues.js:79:11)
    [32mâœ“ should display an error when token login is disabled[39m (1 sec)
```

**Comment by garethbowen** [comment]
Merged - no AT required.
