### ISSUE TITLE
Outbound push may log user and password

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#7023]
**Describe the bug**
During an error the username and password is being dumped to the logs for outbound push. Logs should never contain that level of detail. Noticed this while looking at logtrail for prod instances. 

**To Reproduce**
1. configure outbound push
2. expire the cert on the receiving end
3. an error is generated and the log contains the user and password. 

**Expected behavior**
The error should be logged but the user and password should be removed. 

**Logs**
```
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42] 2021-03-19 14:23:42 ERROR: Failed to push DOC_ID to outbound_push: { RequestError: Error: certificate has expired
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSSocket.socketErrorListener (_http_client.js:387:9)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at ClientRequest.emit (events.js:211:7)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at emitOne (events.js:121:20)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at Request.onRequestError (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request/request.js:877:8)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at Request.RP$callback [as _callback] (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request-promise-core/lib/plumbing.js:46:31)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]   message: 'Error: certificate has expired',
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at Request.plumbing.callback (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request-promise-core/lib/plumbing.js:87:29)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at self.callback (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request/request.js:185:22)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at new RequestError (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request-promise-core/lib/errors.js:14:15)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]   name: 'RequestError',
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at Request.emit (events.js:211:7)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at emitOne (events.js:116:13)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42] 2021-03-19 14:23:42 INFO: checking schedule again in 4 minutes 
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      resolveWithFullResponse: false,
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]         [name]: 'RP$callback',
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      code: 'CERT_HAS_EXPIRED' },
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSSocket.emit (events.js:208:7)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]   error: 
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSSocket.emit (events.js:208:7)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]         [length]: 3,
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      [message]: 'certificate has expired',
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at emitNone (events.js:106:13)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]   [stack]: 'RequestError: Error: certificate has expired\n    at new RequestError (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request/request.js:185:22)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at Request.onRequestError (/srv/software/medic-sentinel/md5-a6sJzRQMfoYRsTWs3ySEA==/node_modules/@medic/outbound/node_modules/request/request.js:877:8)\n    at emitOne (events.js:121:20)\n    at ClientRequest.emit (events.js:211:7)\n    at TLSSocket.socketErrorListener (_http_client.js:387:9)' } 
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      simple: true,
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]         [prototype]: RP$callback { [constructor]: [Circular] } },
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]       { [Function: RP$callback]
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      method: 'POST',
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      [message]: 'certificate has expired',
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSSocket._finishInit (_tls_wrap.js:639:8)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSSocket._finishInit (_tls_wrap.js:639:8)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]   response: undefined,
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      transform2xxOnly: false },
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      transform: undefined,
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      callback: 
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]    { form: { login: 'USER_NAME', password: 'ACTUAL_PASSSWORD' },
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]   options: 
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      timeout: 10000,
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      json: true,
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      url: 'https://outbound.medic.com',
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      [stack]: 'Error: certificate has expired\n    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket._finishInit (_tls_wrap.js:639:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)',
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]     at emitNone (events.js:106:13)
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]    { Error: certificate has expired
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      code: 'CERT_HAS_EXPIRED' },
Mar 19 10:23:42 prod-sentinel-logs: (prod-instance) | [2021-03-19 14:23:42]      [stack]: 'Error: certificate has expired\n    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket._finishInit (_tls_wrap.js:639:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)',
```

**Screenshots**

**Environment**
- Instance: https://muso-mali.dev.medicmobile.org
- App: sentinel
- Version: 

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment]
Also check other places where we log requests particularly in api and sentinel. In this handler because we're not sure what went wrong we're simply [logging the entire error](https://github.com/medic/cht-core/blob/master/shared-libs/outbound/src/outbound.js#L258) which contains too much info - we should be more judicious in what we log.

**Comment by dianabarsan** [comment]
This particular issue with outbound should be fixed in 3.10. https://github.com/medic/cht-core/issues/6024
As far as I know, the instance this is happening on is on an older version (~3.9.x). 

We should still address this logging issue, absolutely, but maybe we could lower the priority since this particular case is already fixed.

**Comment by garethbowen** [comment]
I think it's worth fixing the "unsure" case so it doesn't log passwords in 3.11.0. That should be a fairly easy change to make. I'm happy to defer the audit of the other times we log after sending authenticated requests for a later release.

**Comment by dianabarsan** [comment]
Ready for AT on `7023-better-logging`.

**Comment by newtewt** [comment]
I am testing locally and don't see any errors. My test server is responding with a 500 when calling a specific endpoint. I don't seem to be getting the similar dump as in the prod example. Would there be a better way to reproduce for testing or is this enough?

**Comment by dianabarsan** [comment]
Yea, cause in 3.10 Outbound was updated to treat RequestErrors itself. 
I personally tested the fix on the RapidPro branch, which also throws errors when the RapidPro server requests fail. I think you can also do it with AfricasTalking, but you'd have to add their url to your `hosts` and have the endpoint throw an error or not resolve.

**Comment by newtewt** [comment]
I think this is good to go. Using outbound push I'm calling an endpoint that returns a 500 error. The logs only show the returned error and not a dump as in 3.9 and below. 

```
[2021-04-01 13:02:39] 2021-04-01 13:02:39 ERROR: Failed to push e40f76e4-3ca1-4560-b3c5-f2a222fe998d to express_under, server responsed with 500
[2021-04-01 13:02:39] 2021-04-01 13:02:39 ERROR: Response body: {"error":"This is an error"}
```

**Comment by dianabarsan** [comment]
Outbound was updated in 3.10.x to doctor those logs, so it's not affected by this change. This change would be seen when other requests error (like AfricasTalking outgoing requests).

**Comment by dianabarsan** [comment]
If it's easier, I'll merge and these request failure logs will probably be very visible when RapidPro Gateway is AT-ed. If something's amiss we can re-open. Does that work for you, @newtewt ?

**Comment by newtewt** [comment]
I think that works.

**Comment by dianabarsan** [comment]
Merged to `master`.
