### ISSUE TITLE
Flaky wdio e2e test "Create Person Under Area create person under area should only see children"

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7228]
**Describe the issue**
A wdio test flakes with error: 
```
[Chrome Headless 92.0.4515.107 linux #0-1] Running: Chrome Headless (v92.0.4515.107) on linux
[Chrome Headless 92.0.4515.107 linux #0-1] Session ID: 4f4bca71-9734-4c69-99cb-b35f4002912f
[Chrome Headless 92.0.4515.107 linux #0-1]
[Chrome Headless 92.0.4515.107 linux #0-1] » /tests/e2e/contacts/person-under-area.wdio-spec.js
[Chrome Headless 92.0.4515.107 linux #0-1] Create Person Under Area
[Chrome Headless 92.0.4515.107 linux #0-1]    ✖ create person under area should only see children
[Chrome Headless 92.0.4515.107 linux #0-1]
[Chrome Headless 92.0.4515.107 linux #0-1] 1 failing (56.6s)
[Chrome Headless 92.0.4515.107 linux #0-1]
[Chrome Headless 92.0.4515.107 linux #0-1] 1) Create Person Under Area create person under area should only see children
[Chrome Headless 92.0.4515.107 linux #0-1] element ("#analytics-tab") still not displayed after 50000ms
[Chrome Headless 92.0.4515.107 linux #0-1] Error: element ("#analytics-tab") still not displayed after 50000ms
[Chrome Headless 92.0.4515.107 linux #0-1]     at /home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/commands/browser/waitUntil.js:66:23
[Chrome Headless 92.0.4515.107 linux #0-1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[Chrome Headless 92.0.4515.107 linux #0-1]     at Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:78:29)
[Chrome Headless 92.0.4515.107 linux #0-1]     at Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:23:32)
[Chrome Headless 92.0.4515.107 linux #0-1]     at Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:78:29)
[Chrome Headless 92.0.4515.107 linux #0-1]     at Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:78:29)
[Chrome Headless 92.0.4515.107 linux #0-1]     at Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:23:32)
[Chrome Headless 92.0.4515.107 linux #0-1]     at Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:78:29)
[Chrome Headless 92.0.4515.107 linux #0-1]     at Object.goToBase (/home/runner/work/cht-core/cht-core/tests/page-objects/common/common.wdio.page.js:38:3)
[Chrome Headless 92.0.4515.107 linux #0-1]     at Object.cookieLogin (/home/runner/work/cht-core/cht-core/tests/page-objects/login/login.wdio.page.js:36:3)
```

Run artifact: 
[WDIO Results Artifact 12.x.zip](https://github.com/medic/cht-core/files/6914986/WDIO.Results.Artifact.12.x.zip)

**Describe the improvement you'd like**
Fix the test.

**Comment by dianabarsan** [comment]
The test also sometimes fails with: 
```
[Chrome Headless 92.0.4515.131 linux #0-0] Running: Chrome Headless (v92.0.4515.131) on linux
[Chrome Headless 92.0.4515.131 linux #0-0] Session ID: 87639590-8cba-4ac4-9c0d-35d3bd94dcf9
[Chrome Headless 92.0.4515.131 linux #0-0]
[Chrome Headless 92.0.4515.131 linux #0-0] » /tests/e2e/contacts/new-lineage-structure.wdio-spec.js
[Chrome Headless 92.0.4515.131 linux #0-0] Create new lineage structure
[Chrome Headless 92.0.4515.131 linux #0-0]    ✓ Create new health center
[Chrome Headless 92.0.4515.131 linux #0-0]    ✓ Create new area
[Chrome Headless 92.0.4515.131 linux #0-0]    ✓ Create new household
[Chrome Headless 92.0.4515.131 linux #0-0]    ✖ Create new person
[Chrome Headless 92.0.4515.131 linux #0-0]
[Chrome Headless 92.0.4515.131 linux #0-0] 3 passing (8.3s)
[Chrome Headless 92.0.4515.131 linux #0-0] 1 failing
[Chrome Headless 92.0.4515.131 linux #0-0]
[Chrome Headless 92.0.4515.131 linux #0-0] 1) Create new lineage structure Create new person
[Chrome Headless 92.0.4515.131 linux #0-0] Node is either not visible or not an HTMLElement
[Chrome Headless 92.0.4515.131 linux #0-0] Node is either not visible or not an HTMLElement
[Chrome Headless 92.0.4515.131 linux #0-0] Error: Node is either not visible or not an HTMLElement
[Chrome Headless 92.0.4515.131 linux #0-0]     at ElementHandle._clickablePoint (/home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/JSHandle.ts:423:13)
[Chrome Headless 92.0.4515.131 linux #0-0]     at runMicrotasks (<anonymous>)
[Chrome Headless 92.0.4515.131 linux #0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[Chrome Headless 92.0.4515.131 linux #0-0]     at ElementHandle.click (/home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/JSHandle.ts:495:22)
------------------------------------------------------------------
[Chrome Headless 92.0.4515.131 linux #0-1] Running: Chrome Headless (v92.0.4515.131) on linux
[Chrome Headless 92.0.4515.131 linux #0-1] Session ID: b4c96d31-39f0-4e6d-b3d1-0d6d99137ce5
[Chrome Headless 92.0.4515.131 linux #0-1]
[Chrome Headless 92.0.4515.131 linux #0-1] » /tests/e2e/contacts/person-under-area.wdio-spec.js
[Chrome Headless 92.0.4515.131 linux #0-1] Create Person Under Area
[Chrome Headless 92.0.4515.131 linux #0-1]    ✖ create person under area should only see children
[Chrome Headless 92.0.4515.131 linux #0-1]
[Chrome Headless 92.0.4515.131 linux #0-1] 1 failing (17.5s)
[Chrome Headless 92.0.4515.131 linux #0-1]
[Chrome Headless 92.0.4515.131 linux #0-1] 1) Create Person Under Area create person under area should only see children
[Chrome Headless 92.0.4515.131 linux #0-1] Can't call addValue on element with selector "//input[@aria-controls="select2-facilitySelect-results"]" because element wasn't found
[Chrome Headless 92.0.4515.131 linux #0-1] Error: Can't call addValue on element with selector "//input[@aria-controls="select2-facilitySelect-results"]" because element wasn't found
[Chrome Headless 92.0.4515.131 linux #0-1]     at Object.implicitWait [as default] (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/utils/implicitWait.js:34:19)
[Chrome Headless 92.0.4515.131 linux #0-1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

example run: https://github.com/medic/cht-core/runs/3244381261?check_suite_focus=true

**Comment by meghna-khemka** [comment]
Fixes for 'Create Person Under Area create person under area' pushed under https://github.com/medic/cht-core/pull/7225

**Comment by meghna-khemka** [comment]
New lineage one will be pushed under https://github.com/medic/cht-core/pull/7231 by Bede

**Comment by garethbowen** [comment]
Both the linked PRs have been merged, and this test is currently 100% in build history. Closing this as fixed.
