### ISSUE TITLE
Flaky wdio e2e test Create new lineage structure

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7244]
**Describe the issue**
Test is failing with: 
```
[Chrome Headless 92.0.4515.131 linux #0-0] 1) Create new lineage structure Create new person
[Chrome Headless 92.0.4515.131 linux #0-0] expect(received).toBe(expected) // Object.is equality

Expected: "James"
Received: "East Ralph"
[Chrome Headless 92.0.4515.131 linux #0-0] Error: expect(received).toBe(expected) // Object.is equality
[Chrome Headless 92.0.4515.131 linux #0-0]
[Chrome Headless 92.0.4515.131 linux #0-0] Expected: "James"
[Chrome Headless 92.0.4515.131 linux #0-0] Received: "East Ralph"
[Chrome Headless 92.0.4515.131 linux #0-0]     at Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/contacts/new-lineage-structure.wdio-spec.js:41:50)
[Chrome Headless 92.0.4515.131 linux #0-0]     at runMicrotasks (<anonymous>)
[Chrome Headless 92.0.4515.131 linux #0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[Chrome Headless 92.0.4515.131 linux #0-0]     at Context.executeAsync (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:136:16)
[Chrome Headless 92.0.4515.131 linux #0-0]     at Context.testFrameworkFnWrapper (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:52:18)
```

**Describe the improvement you'd like**
Fix the test.

Test artifact: 
[WDIO Results Artifact 12.x (2).zip](https://github.com/medic/cht-core/files/6958748/WDIO.Results.Artifact.12.x.2.zip)

**Comment by dianabarsan** [comment]
This issue explains why this test is failing: https://github.com/medic/cht-core/issues/7250

**Comment by dianabarsan** [comment]
I tried to stabilize this test by adding some "waits" between contact loads. Please reopen if the test starts failing again.
