### ISSUE TITLE
e2e tests failing too much in CI

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-core#7344]
**Describe the bug**
More than the half of the jobs are failing in CI with flaky tests, and lately I have the impression that each time is getting worst. In the last 2 PRs I worked the ratio was worst: ~4 in 5 failing.

**Expected behavior**
Although is expected some times e2e to fail, the number of failures should be reduced drastically to be considered "normal".

**Logs**

Here are a few cases from the jobs history, it's hard to find a pattern, what is common in most is that the failed tests always take more time than expected (to fail), most of them above 10 secs.

https://github.com/medic/cht-core/pull/7301/checks?check_run_id=3616617946:

```
 ci-e2e on node 12.x

   Add new district tests : 
    ✗ should edit district with contact_type (12 secs)
      - Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, #contacts-list .content-row)
```

https://github.com/medic/cht-core/pull/7301/checks?check_run_id=3621248850:

```
 Config Tests (exec:test-config-default)
   1) pregnancy home visit tests
       pregnancy home visit task should show:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/cht-core/cht-core/config/default/test/tasks/pregnancy_home_visit.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) pregnancy home visit tests
       pregnancy home visit task for unknown LMP:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/cht-core/cht-core/config/default/test/tasks/pregnancy_home_visit.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://github.com/medic/cht-core/pull/7301/checks?check_run_id=3621249313

```
 ci-e2e on node 8.x 
   Bulk delete reports
    ✗ should select, deselect and delete only selected reports (12 secs)
      - Failed: stale element reference: element is not attached to the page document
        (Session info: headless chrome=93.0.4577.63)
        (Driver info: chromedriver=93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}),platform=Linux 5.4.0-1058-azure x86_64)
   Concatenate xpath strings
    ✗ concatenates strings (20 secs)
      - Failed: Wait timed out after 10006ms
     as a user with a home place
      ✗ should display correct data (4 secs)
        - Failed: stale element reference: element is not attached to the page document
          (Session info: headless chrome=93.0.4577.63)
          (Driver info: chromedriver=93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}),platform=Linux 5.4.0-1058-azure x86_64)
```

https://github.com/medic/cht-core/runs/3668085676?check_suite_focus=true:

```
 ci-e2e on node 8.x 
   Incorrect locale
    ✗ should work with incorrect locale (14 secs)
      - Failed: Wait timed out after 2009ms
```

https://github.com/medic/cht-core/pull/7301/checks?check_run_id=3668301050:

```
 Grunt CI-Compile
1) should fail if ValidateForm fails
     FormsXmlCtrl controller validations
     Error: Uncaught AssertionError: expected { uploading: true, error: false, success: false } to deeply equal { uploading: false,
  error: true,
  success: false,
  errorMessage: 'Upload failed: Error validating form - wrong content' } (/home/runner/work/cht-core/cht-core/node_modules/chai/chai.js:250)
```

https://github.com/medic/cht-core/pull/7301/checks?check_run_id=3669047399:

```
 ci-e2e on node 8.x 
 Test it!

1) Add new district tests :  should add new district with a new person
  - Failed: stale element reference: element is not attached to the page document
    (Session info: headless chrome=93.0.4577.63)
    (Driver info: chromedriver=93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}),platform=Linux 5.4.0-1058-azure x86_64)
```

https://github.com/medic/cht-core/runs/3679101546?check_suite_focus=true:

```
 ci-e2e on node 10.x 
 Test it!

    for a french offline user
      ✗ should show the correct privacy policy on login (9 secs)
        - Failed: element click intercepted: Element <a href="" dropdowntoggle="" id="header-dropdown-link" aria-controls="header-dropdown" aria-haspopup="true">...</a> is not clickable at point (999, 45). Other element would receive the click: <modal-container role="dialog" tabindex="-1" class="modal fade in" style="display: block;" aria-modal="true">...</modal-container>
          (Session info: headless chrome=93.0.4577.63)
          (Driver info: chromedriver=93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}),platform=Linux 5.4.0-1058-azure x86_64)
```

https://github.com/medic/cht-core/runs/3679638764?check_suite_focus=true:

```
 ci-e2e on node 12.x 
 Test it!

    for a french offline user
      ✗ should show the correct privacy policy on login (8 secs)
        - Failed: element click intercepted: Element <a href="" dropdowntoggle="" id="header-dropdown-link" aria-controls="header-dropdown" aria-haspopup="true">...</a> is not clickable at point (999, 45). Other element would receive the click: <modal-container role="dialog" tabindex="-1" class="modal fade in" style="display: block;" aria-modal="true">...</modal-container>
          (Session info: headless chrome=93.0.4577.63)
          (Driver info: chromedriver=93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}),platform=Linux 5.4.0-1058-azure x86_64)
```

https://github.com/medic/cht-core/runs/3680212437?check_suite_focus=true:

```
 ci-e2e on node 12.x 
 Test it!

    Add new district tests : 
    ✗ should add new district with a new person (12 secs)
      - Failed: stale element reference: element is not attached to the page document
        (Session info: headless chrome=93.0.4577.63)
        (Driver info: chromedriver=93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}),platform=Linux 5.4.0-1058-azure x86_64) 
```

https://github.com/medic/cht-core/runs/3687752867?check_suite_focus=true:

```
ci-webdriver-default on node 12.x 
 Test it!

 [Chrome Headless 93.0.4577.82 linux #0-15] MessageFormat
[Chrome Headless 93.0.4577.82 linux #0-15]    ✖ should display plurals correctly
[Chrome Headless 93.0.4577.82 linux #0-15] element (".card.tasks .table-filter a") still not displayed after 15000ms
```

https://github.com/medic/cht-core/runs/3704755599:

```
 ci-e2e on node 8.x 
 Test it!

  Adding new language
    ✗ should add new translations (3 secs)
      - Expected '' to be 'Geen verslae gevind nie'.
          at UserContext.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/translations/new-language.spec.js:67:71)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Environment**
Jobs at Github Actions.

**Comment by dianabarsan** [comment]
One of these have already been fixed, for example:

> 1) should fail if ValidateForm fails
should be fixed by: https://github.com/medic/cht-core/commit/f9eb9e928c1359a79520693c7b8c325d33b609e8

Also, this one has a known source: 
> for a french offline user
      ✗ should show the correct privacy policy on login (9 secs)

https://github.com/medic/cht-core/issues/6960

**Comment by dianabarsan** [comment]
I'm attempting to stabilize Add new district tests here: https://github.com/medic/cht-core/pull/7388

**Comment by garethbowen** [comment]
Some of these have been resolved. If any still occur we should have one issue for each, rather than a mega issue. Closing for now.
