### ISSUE TITLE
Report export doesn't filter by "verified" correctly

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7465]
**Describe the bug**
Calling the api reports export endpoint, and using the `verified` filter, will result in an error. 

**To Reproduce**
1. Log in as an admin. 
2. Load this url in your browser: `http://<you instance>/api/v2/export/reports?filters[verified]=true`
3. Open the downloaded CSV
4. See error `Error exporting data: keys.map is not a function`

**Expected behavior**
Exporting using `verified` should be possible. 

**Logs**
API logs:
```
2022-01-11 11:45:56 ERROR: TypeError: keys.map is not a function
    at getKeysArray (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:8:15)
    at getRequestWithMappedKeys (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:32:12)
    at verificationRequest (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:90:10)
    at reports (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:196:7)
    at Object.generate (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:309:12)
    at /home/diana/projects/medic/shared-libs/search/src/search.js:125:41
    at Object.getDocIds (/home/diana/projects/medic/api/src/services/export/report-mapper.js:42:12)
    at SearchResultReader._read (/home/diana/projects/medic/api/src/services/export-data.js:61:24)
    at SearchResultReader.Readable.read (_stream_readable.js:469:10)
    at maybeReadMore_ (_stream_readable.js:617:12) {
  [stack]: 'TypeError: keys.map is not a function\n' +
    '    at getKeysArray (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:8:15)\n' +
    '    at getRequestWithMappedKeys (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:32:12)\n' +
    '    at verificationRequest (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:90:10)\n' +
    '    at reports (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:196:7)\n' +
    '    at Object.generate (/home/diana/projects/medic/shared-libs/search/src/generate-search-requests.js:309:12)\n' +
    '    at /home/diana/projects/medic/shared-libs/search/src/search.js:125:41\n' +
    '    at Object.getDocIds (/home/diana/projects/medic/api/src/services/export/report-mapper.js:42:12)\n' +
    '    at SearchResultReader._read (/home/diana/projects/medic/api/src/services/export-data.js:61:24)\n' +
    '    at SearchResultReader.Readable.read (_stream_readable.js:469:10)\n' +
    '    at maybeReadMore_ (_stream_readable.js:617:12)',
  [message]: 'keys.map is not a function'
} 
```

**Environment**
- Instance: any
- App: api
- Version: 2.16+ (introduced by https://github.com/medic/cht-core/issues/4577)

**Why Now?**
Partner(s): Internal
Reason(s): A partner will have CHWs/Supervisors with a detrimental experience, thus providing bad care

**Comment by dianabarsan** [comment]
This is ready for AT on `7464-export-with-filters`.

**Comment by ngaruko** [comment]
Tested on local,
Main branch :

```
_id,form,patient_id,reported_date,from,contact.name,contact.parent.name,contact.parent.parent.name,contact.parent.parent.parent.name,inputs.contact._id,inputs.contact.patient_id,inputs.meta.deprecatedID,inputs.meta.location.error,inputs.meta.location.lat,inputs.meta.location.long,inputs.meta.location.message,inputs.source,inputs.user.contact_id,meta.instanceID,the_status
--ERROR--
Error exporting data: keys.map is not a function
```
and logs:
```
2022-01-14 14:27:06 ERROR: TypeError: keys.map is not a function
    at getKeysArray (/Users/bede/.horticulturalist/deployments/medic-api/md5-ynnwarrmenYrgpFegKirCA==/node_modules/@medic/search/src/generate-search-requests.js:8:15)
    at getRequestWithMappedKeys (/Users/bede/.horticulturalist/deployments/medic-api/md5-ynnwarrmenYrgpFegKirCA==/node_modules/@medic/search/src/generate-search-requests.js:32:12)
    at verificationRequest (/Users/bede/.horticulturalist/deployments/medic-api/md5-ynnwarrmenYrgpFegKirCA==/node_modules/@medic/search/src/generate-search-requests.js:90:10)
    at reports (/Users/bede/.horticulturalist/deployments/medic-api/md5-ynnwarrmenYrgpFegKirCA==/node_modules/@medic/search/src/generate-search-requests.js:196:7)
    at Object.generate (/Users/bede/.horticulturalist/deployments/medic-api/md5-ynnwarrmenYrgpFegKirCA==/node_modules/@medic/search/src/generate-search-requests.js:309:12)

....
....
```

and on the 7464 branch, downloaded, report(s) downloaded,  no errors:
```
REQ ca217f33-86ca-4c23-b410-6d64ee6dd79d ::ffff:127.0.0.1 - GET /api/v2/export/reports?filters[verified]=true HTTP/1.1
2022-01-14 16:19:57 INFO: Export requested for "reports" 
2022-01-14 16:19:57 INFO:   filters: {
  "verified": [
    true
  ]
} 
2022-01-14 16:19:57 INFO:   options: {
  "humanReadable": false
} 
```
![image](https://user-images.githubusercontent.com/6979995/149446075-4185929f-8355-49f0-893c-ba09ca11a0b5.png)

**Comment by dianabarsan** [comment]
Merged to `master`.
