### ISSUE TITLE
Retry resetting user contact doc in e2e tests

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7507]
**Describe the issue**
If resetting the user contact doc fails due to a document conflict (or any other reason) the test aborts. This is used in test cleanup so doesn't indicate an actual failure. This happened in [this build](https://github.com/medic/cht-core/runs/4531387459?check_suite_focus=true).

**Describe the improvement you'd like**
We should retry a couple of times to make the e2e test suite more robust.

**Describe alternatives you've considered**
Trying to work out why the test is modifying the user contact doc, but it could be for a range of legitimate reasons, so it makes sense to simply retry I think.

Example log:
```
 ------------------------------------------------------------------
[Chrome Headless 96.0.4664.93 linux #0-14] Running: Chrome Headless (v96.0.4664.93) on linux
[Chrome Headless 96.0.4664.93 linux #0-14] Session ID: 233f1ef9-fc54-404f-a849-990841576aa9
[Chrome Headless 96.0.4664.93 linux #0-14]
[Chrome Headless 96.0.4664.93 linux #0-14] » /tests/e2e/login/token-login.wdio-spec.js
[Chrome Headless 96.0.4664.93 linux #0-14] Token login
[Chrome Headless 96.0.4664.93 linux #0-14]    ✓ should redirect the user to the app if already logged in
[Chrome Headless 96.0.4664.93 linux #0-14]    ✓ should display an error when token login is disabled
[Chrome Headless 96.0.4664.93 linux #0-14]    ✓ should display an error with incorrect url
[Chrome Headless 96.0.4664.93 linux #0-14]    ✓ should display an error when accessing with random strings
[Chrome Headless 96.0.4664.93 linux #0-14]    ✓ should display an error when token is expired
[Chrome Headless 96.0.4664.93 linux #0-14]    ✓ should log the user in when token is correct
[Chrome Headless 96.0.4664.93 linux #0-14]    ✖ "after all" hook for Token login
[Chrome Headless 96.0.4664.93 linux #0-14]
[Chrome Headless 96.0.4664.93 linux #0-14] 6 passing (7.6s)
[Chrome Headless 96.0.4664.93 linux #0-14] 1 failing
[Chrome Headless 96.0.4664.93 linux #0-14]
[Chrome Headless 96.0.4664.93 linux #0-14] 1) Token login "after all" hook for Token login
[Chrome Headless 96.0.4664.93 linux #0-14] 409 - {"error":"conflict","reason":"Document update conflict."}
[Chrome Headless 96.0.4664.93 linux #0-14] StatusCodeError: 409 - {"error":"conflict","reason":"Document update conflict."}
[Chrome Headless 96.0.4664.93 linux #0-14]     at new StatusCodeError (/home/runner/work/cht-core/cht-core/node_modules/request-promise-core/lib/errors.js:32:15)
[Chrome Headless 96.0.4664.93 linux #0-14]     at /home/runner/work/cht-core/cht-core/node_modules/request-promise-core/lib/plumbing.js:97:41
[Chrome Headless 96.0.4664.93 linux #0-14]     at runMicrotasks (<anonymous>)
[Chrome Headless 96.0.4664.93 linux #0-14]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
------------------------------------------------------------------
```

**Comment by garethbowen** [comment]
Test code only, so no AT required. Merged.
