### ISSUE TITLE
Flakey snackbar tests

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7580]
**Describe the issue**

The `snackbar.wdio-spec.js` tests fail quite frequently.

```
[Chrome Headless 100.0.4896.60 linux #0-28] Running: Chrome Headless (v100.0.4896.60) on linux
[Chrome Headless 100.0.4896.60 linux #0-28] Session ID: 403e3d1a-0e68-458e-b628-50702a27b7e0
[Chrome Headless 100.0.4896.60 linux #0-28]
[Chrome Headless 100.0.4896.60 linux #0-28] » /tests/e2e/snackbar.wdio-spec.js
[Chrome Headless 100.0.4896.60 linux #0-28] Snackbar
[Chrome Headless 100.0.4896.60 linux #0-28]    ✖ should display the snackbar with the syncing messages and then hide it
[Chrome Headless 100.0.4896.60 linux #0-28]    ✓ should display the snackbar with a clickable action
[Chrome Headless 100.0.4896.60 linux #0-28]
[Chrome Headless 100.0.4896.60 linux #0-28] 1 passing (23.4s)
[Chrome Headless 100.0.4896.60 linux #0-28] 1 failing
[Chrome Headless 100.0.4896.60 linux #0-28]
[Chrome Headless 100.0.4896.60 linux #0-28] 1) Snackbar should display the snackbar with the syncing messages and then hide it
[Chrome Headless 100.0.4896.60 linux #0-28] element ("#snackbar.active") still not displayed after 15000ms
[Chrome Headless 100.0.4896.60 linux #0-28] Error: element ("#snackbar.active") still not displayed after 15000ms
[Chrome Headless 100.0.4896.60 linux #0-28]     at /home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/commands/browser/waitUntil.js:66:23
[Chrome Headless 100.0.4896.60 linux #0-28]     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 100.0.4896.60 linux #0-28]     at async Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:24:32)
[Chrome Headless 100.0.4896.60 linux #0-28]     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 100.0.4896.60 linux #0-28]     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 100.0.4896.60 linux #0-28]     at async Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:24:32)
[Chrome Headless 100.0.4896.60 linux #0-28]     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 100.0.4896.60 linux #0-28]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/snackbar.wdio-spec.js:34:5)
```

**Comment by garethbowen** [comment]
This is definitely not fixed, with multiple failures recently, eg:

```
 [Chrome Headless 101.0.4951.41 linux #0-29] » /tests/e2e/snackbar.wdio-spec.js
[Chrome Headless 101.0.4951.41 linux #0-29] Syncing snackbar
[Chrome Headless 101.0.4951.41 linux #0-29]    ✖ should display the snackbar with the syncing messages and then hide it
[Chrome Headless 101.0.4951.41 linux #0-29]    ✓ should display the snackbar with a clickable action
[Chrome Headless 101.0.4951.41 linux #0-29]
[Chrome Headless 101.0.4951.41 linux #0-29] 1 passing (24s)
[Chrome Headless 101.0.4951.41 linux #0-29] 1 failing
[Chrome Headless 101.0.4951.41 linux #0-29]
[Chrome Headless 101.0.4951.41 linux #0-29] 1) Syncing snackbar should display the snackbar with the syncing messages and then hide it
[Chrome Headless 101.0.4951.41 linux #0-29] waitUntil condition timed out after 15000ms
[Chrome Headless 101.0.4951.41 linux #0-29] Error: waitUntil condition timed out after 15000ms
[Chrome Headless 101.0.4951.41 linux #0-29]     at /home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/commands/browser/waitUntil.js:68:19
[Chrome Headless 101.0.4951.41 linux #0-29]     at async Browser.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 101.0.4951.41 linux #0-29]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/snackbar.wdio-spec.js:36:5)
```
