### ISSUE TITLE
conflicts diff script crashes because of change in view code

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7650]
**Describe the bug**
[The scripts/conflicts/diff](https://github.com/medic/cht-core/blob/41e6582b4c2ce9831428bcc30d05b422ad45cf1c/scripts/conflicts/diff.js) throws an error:
```
Generating diffs for conflicts on http://admin:pass@127.0.0.1:6500/medic
Found 1 conflicts
TypeError: Cannot read property 'length' of null
    at /home/diana/projects/medic/scripts/conflicts/diff.js:33:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**To Reproduce**
Run the script against a 3.9+ CHT instance. 
 
**Expected behavior**
It should output something like: 
```
=====================
org.couchdb.user:aeroscope
=====================
 {
-  _rev: "8-de3fe258b9e30b7096b9125ce1f2276d"
+  _rev: "4-d50f73817a473255c40e6b06eebbe78b"
-  facility_id: "c5d73dde-c62b-4297-a78f-929e59438686"
+  facility_id: "dfe8e4d8-5338-4321-8751-e2ee64ec5bbf"
-  contact_id: "afa1cfabc855af4abd7a9721dd001624"
+  contact_id: "50472724-b83f-4ce8-b7f7-58f267a5442f"
 }
```

**Environment**
- Version: 3.9+

**Additional context**
This is caused by [this commit](https://github.com/medic/cht-core/commit/67bb273e2d20b775b27a6c0bdf20b169284aff1d) adding a reduce function to the conflicts view. 
Fixing this just requires passing `{ reduce: true }` to the query in the script: 
https://github.com/medic/cht-core/blob/41e6582b4c2ce9831428bcc30d05b422ad45cf1c/scripts/conflicts/diff.js#L25

**Comment by dianabarsan** [comment]
This is ready to be AT ed on `PrjShrestha:Prajwol-7650-Diff-Script-crash-fix`

**Comment by tatilepizs** [comment]
**Config:** Default
**Environment:** Local
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `Master`
After running the script `diff.js` this is the output.

<details>
<summary>Output</summary>

```
➜  conflicts git:(master) node diff.js
Generating diffs for conflicts on http://admin:password@localhost:5984/medic
Found 1 conflicts
TypeError: Cannot read property 'length' of null
    at /Users/tlepiz/Documents/Medic/Repos/cht-core/scripts/conflicts/diff.js:33:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

</details>

### Fixed on `PrjShrestha:Prajwol-7650-Diff-Script-crash-fix`
After running the script `diff.js` this is the output.

<details>
<summary>Output</summary>

```
➜  conflicts git:(Prajwol-7650-Diff-Script-crash-fix) node diff.js
Generating diffs for conflicts on http://admin:password@localhost:5984/medic
Found 1 conflicts
{
  _rev: {
    __old: '2-e90de87842bf5636d1881688712c55dd',
    __new: '2-3e32a1377adbd29bf9baa09da9eadaba'
  },
  hidden_fields: [
    [ ' ', 'patient_age_in_years' ],
    [ ' ', 'patient_uuid' ],
    [ ' ', 'patient_id' ],
    [ ' ', 'patient_name' ],
    [ ' ', 'patient_short_name' ],
    [ ' ', 'patient_short_name_start' ],
    [ ' ', 'lmp_date_8601' ],
    [ ' ', 'edd_8601' ],
    [ '+', 'days_since_lmp' ],
    [ '+', 'weeks_since_lmp' ],
    [ '+', 'weeks_since_lmp_rounded' ],
    [ ' ', 'lmp_method_approx' ],
    [ ' ', 'hiv_status_known' ],
    [ ' ', 'deworming_med_received' ],
    [ ' ', 'tt_received' ],
    [ ' ', 't_pregnancy_follow_up_date' ],
    [ ' ', 't_pregnancy_follow_up' ],
    [ ' ', 't_danger_signs_referral_follow_up_date' ],
    [ ' ', 't_danger_signs_referral_follow_up' ],
    [ ' ', 'gestational_age.register_method.register_note' ],
    [ '+', 'gestational_age.method_lmp_summary' ],
    [ ' ', 'gestational_age.g_lmp_date_8601' ],
    [ ' ', 'gestational_age.g_lmp_date' ],
    [ ' ', 'gestational_age.g_edd_8601' ],
    [ ' ', 'gestational_age.g_edd' ],
    [ '-', 'gestational_age.method_none.no_info_notice' ],
    [ '-', 'gestational_age.method_none.pregnancy_confirm_note' ],
    [ '+', 'anc_visits_hf.anc_visits_hf_next.anc_visit_advice_note' ],
    [ ' ', 'risk_factors.r_risk_factor_present' ],
    [ ' ', 'danger_signs.danger_signs_note' ],
    [ ' ', 'danger_signs.r_danger_sign_present' ],
    [ ' ', 'danger_signs.refer_patient_note_1' ],
    [ ' ', 'danger_signs.refer_patient_note_2' ],
    [ ' ', 'safe_pregnancy_practices.malaria.llin_advice_note' ],
    [
      ' ',
      'safe_pregnancy_practices.malaria.malaria_prophylaxis_note'
    ],
    [ ' ', 'safe_pregnancy_practices.iron_folate.iron_folate_note' ],
    [ '+', 'safe_pregnancy_practices.deworming.deworming_med_note' ],
    [ '+', 'safe_pregnancy_practices.safe_practices_tips' ],
    [ ' ', 'safe_pregnancy_practices.hiv_status.hiv_importance_note' ],
    [ ' ', 'safe_pregnancy_practices.request_services' ],
    [ ' ', 'summary' ],
    [ ' ', 'data' ],
    [ ' ', 'meta' ]
  ],
  fields: {
    days_since_lmp__added: '158',
    weeks_since_lmp__added: '22.57',
    weeks_since_lmp_rounded__added: '22',
    anc_visits_hf__added: { anc_visits_hf_past: [Object], anc_visits_hf_next: [Object] },
    lmp_date_8601: { __old: '', __new: '2022-03-11' },
    edd_8601: { __old: '', __new: '2022-12-16' },
    hiv_status_known: { __old: 'no', __new: 'yes' },
    deworming_med_received: { __old: '', __new: 'yes' },
    t_pregnancy_follow_up: { __old: '', __new: 'no' },
    gestational_age: {
      method_none__deleted: [Object],
      method_lmp__added: [Object],
      method_lmp_summary__added: [Object],
      register_method: [Object],
      g_lmp_date_8601: [Object],
      g_lmp_date: [Object],
      g_edd_8601: [Object],
      g_edd: [Object]
    },
    risk_factors: { risk_factors_history: [Object], risk_factors_present: [Object] },
    danger_signs: {
      fits: [Object],
      very_pale: [Object],
      easily_tired: [Object],
      breathlessness: [Object]
    },
    safe_pregnancy_practices: {
      deworming__added: [Object],
      safe_practices_tips__added: [Object],
      malaria: [Object],
      iron_folate: [Object],
      hiv_status: [Object],
      request_services: [Object]
    },
    summary: {
      r_pregnancy_details_unknown__deleted: '',
      r_risk_previous_difficulties__deleted: '',
      r_risk_more_than_4_children__deleted: '',
      r_risk_last_baby_born_less_than_1_year_ago__deleted: '',
      r_request_services__deleted: '',
      r_request_service_hiv_test__deleted: '',
      r_request_service_iron__deleted: '',
      r_refer_hf_immediately__deleted: '',
      r_fup_pregnancy_visit_2_weeks__deleted: '',
      r_pregnancy_details__added: '',
      r_risk_first_pregnancy__added: '',
      r_risk_previous_miscarriage__added: '',
      r_danger_sign_fits__added: '',
      r_danger_sign_very_pale__added: '',
      r_danger_sign_easily_tired__added: '',
      r_danger_sign_breathlessness__added: '',
      r_refer_hf_appropriate_time__added: '',
      r_fup_pregnancy_visit__added: '',
      next_visit_weeks: [Object],
      edd_summary: [Object]
    },
    data: {
      __lmp_method: [Object],
      __no_lmp_registration_reason: [Object],
      __lmp_date: [Object],
      __edd: [Object],
      __num_previous_anc_hf_visits: [Object],
      __next_anc_hf_visit_date_known: [Object],
      __first_pregnancy: [Object],
      __previous_miscarriage: [Object],
      __previous_difficulties: [Object],
      __more_than_4_children: [Object],
      __last_baby_born_less_than_1_year_ago: [Object],
      __heart_condition: [Object],
      __asthma: [Object],
      __high_blood_pressure: [Object],
      __diabetes: [Object],
      __fits: [Object],
      __very_pale: [Object],
      __easily_tired: [Object],
      __breathlessness: [Object],
      __uses_llin: [Object],
      __takes_iron_folate_daily: [Object],
      __received_deworming_meds: [Object],
      __tested_for_hiv_in_past_3_months: [Object]
    },
    meta: { instanceID: [Object] }
  },
  geolocation_log: [ [ ' ' ], [ '~', [Object] ] ],
  geolocation: {
    latitude: { __old: 10.0211255, __new: 10.021174907114473 },
    longitude: { __old: -84.0804214, __new: -84.08044346869642 },
    accuracy: { __old: 16.48, __new: 35 }
  },
  _attachments: { content: { digest: [Object], length: [Object] } }
}
=====================
=====================
```
</details>

**Comment by garethbowen** [comment]
Merged. Thanks @PrjShrestha !
