### ISSUE TITLE
node-pre-gyp install results in code ELIFECYCLE  npm ERR! errno 1

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7749]
**Describe the issue**
When following the [developer install steps](https://docs.communityhealthtoolkit.org/apps/guides/hosting/core-developer/), I can not run `grunt`. The build takes a loooooonnng time (>7min) and then I get an error with the `node-pre-gyp install --fallback-to-build --loglevel http` call that results in:

```sh
>> npm ERR!
>> code ELIFECYCLE
>> npm ERR! errno 1
>> npm
>> ERR! node1-libxmljsmt-myh@1.0.4 install: `node-pre-gyp install --fallback-to-build --loglevel http`
>> npm ERR! Exit status 1
>> npm ERR! 
>> npm ERR! Failed at the node1-libxmljsmt-myh@1.0.4 install script.
```

**Describe the improvement you'd like**
Have `grunt` work with out errors

**Describe alternatives you've considered**
Trying to see if [maybe this is related](https://github.com/nodejs/node-gyp/issues/1599#issue-377710818) and an `npm` call might fix it?

```sh
sudo npm install node-gyp -g
sudo npm install node-gyp-build -g
```

Here's the full logs of when running `time grunt`:

```
added 72 packages in 397.937s
[api]
>> npm
>> WARN prepare removing existing node_modules/ before installation

> node1-libxmljsmt-myh@1.0.4 install /home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh
> node-pre-gyp install --fallback-to-build --loglevel http

>> node-pre-gyp
>> 
>> http GET https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v72-linux-x64.tar.gz
>> node-pre-gyp http
>> 404 https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v72-linux-x64.tar.gz
>> node-pre-gyp ERR! Tried to download(404): https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v72-linux-x64.tar.gz 
>> node-pre-gyp ERR! Pre-built binaries not found for node1-libxmljsmt-myh@1.0.4 and node@12.22.12 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
>> node-pre-gyp http 404 status code downloading tarball https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v72-linux-x64.tar.gz
>> gyp
>> ERR! build error
>> gyp
>> ERR! stack Error: not found: make
>> gyp ERR! stack     at getNotFoundError (/home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/which/which.js:13:12)
>> gyp ERR! stack     at F (/home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/which/which.js:68:19)
>> gyp ERR! stack     at E (/home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/which/which.js:80:29)
>> gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/which/which.js:89:16
>> gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/isexe/index.js:42:5
>> gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
>> gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
>> gyp ERR! System Linux 5.15.0-46-generic
>> gyp ERR! command "/home/ubuntu/.nvm/versions/node/v12.22.12/bin/node" "/home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh/build/Release/xmljs-myh.node" "--module_name=xmljs-myh" "--module_path=/home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh/build/Release" "--napi_version=8" "--node_abi_napi=napi"
>> gyp ERR! cwd /home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh
>> gyp ERR! node -v v12.22.12
>> gyp ERR! node-gyp -v v5.1.0
>> gyp ERR! not ok
>> node-pre-gyp ERR!
>> build error
>> node-pre-gyp ERR! stack Error: Failed to execute '/home/ubuntu/.nvm/versions/node/v12.22.12/bin/node /home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh/build/Release/xmljs-myh.node --module_name=xmljs-myh --module_path=/home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh/build/Release --napi_version=8 --node_abi_napi=napi' (1)
>> node-pre-gyp
>> ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/cht-core/api/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
>> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
>> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
>> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
>> node-pre-gyp ERR! System
>> Linux 5.15.0-46-generic
>> node-pre-gyp ERR! command "/home/ubuntu/.nvm/versions/node/v12.22.12/bin/node" "/home/ubuntu/cht-core/api/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
>> node-pre-gyp ERR! cwd /home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh
>> node-pre-gyp
>> ERR! node -v v12.22.12
>> node-pre-gyp ERR! node-pre-gyp -v v0.9.1
>> node-pre-gyp ERR!
>> not ok
Failed to execute '/home/ubuntu/.nvm/versions/node/v12.22.12/bin/node /home/ubuntu/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh/build/Release/xmljs-myh.node --module_name=xmljs-myh --module_path=/home/ubuntu/cht-core/api/node_modules/node1-libxmljsmt-myh/build/Release --napi_version=8 --node_abi_napi=napi' (1)
>> npm ERR!
>> code ELIFECYCLE
>> npm ERR! errno 1
>> npm
>> ERR! node1-libxmljsmt-myh@1.0.4 install: `node-pre-gyp install --fallback-to-build --loglevel http`
>> npm ERR! Exit status 1
>> npm ERR! 
>> npm ERR! Failed at the node1-libxmljsmt-myh@1.0.4 install script.
>> npm
>> ERR! This is probably not a problem with npm. There is likely additional logging output above.
>> 
>> npm ERR! A complete log of this run can be found in:
>> npm ERR!     /home/ubuntu/.npm/_logs/2022-08-19T22_52_43_209Z-debug.log
>> Exited with code: 1.
>> Error executing child process: Error: Process exited with code 1.
Warning: Task "exec:npm-ci-modules" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2022-08-19 22:45:13 UTC-0)
exec:npm-ci-shared-libs     45.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 10%
exec:npm-ci-modules      6m 43.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 90%
Total 7m 29.8s
```

**Comment by latin-panda** [comment]
Hi @mrjones-plip, is the issue resolved if you use python v2.7?

**Comment by elvisdorkenoo** [comment]
Thanks to @latin-panda I managed to make it work.
I worked with python 2 with then had to downgrade npm to version 6.
Current environnement :
OS : Mac OS Monterey 12.5
Python version : 2.7.18
Node version : v12.22.6
NPM version : 6.14.11

**Comment by mrjones-plip** [comment]
Thanks @elvisdorkenoo! I'm testing more exhaustively on Ubuntu 18, 20 and 22 and not seeing the easy fix.

After  5 min of just sitting here:

```sh
Running "exec:npm-ci-modules" (exec) task                                                                                                                                                   
[webapp]  
```

which looks like this:

![image](https://user-images.githubusercontent.com/8253488/187582236-8204269b-0885-4698-9e49-f795a5ef76d1.png)

I finally die in the exact same place on all 3:

![image](https://user-images.githubusercontent.com/8253488/187582375-6c8b0d10-30c6-4db0-8115-4fb9c8f667df.png)

Calling `python -V;python2 -V; python3 -V;npm -v;node -v` on my ubuntu 18 box, I get:

```
ubuntu@ubuntu-18-test:~/cht-core$ python -V;python2 -V; python3 -V;npm -v;node -v
Python 2.7.17
Python 2.7.17
Python 3.6.9
6.14.16
v12.22.12
```

While Ubuntu 20 and 22 don't have the proper symlink to resolve `python`, clearly the Ubuntu 18 box died in the same spot and it DOES resolve `python` correctly.  :thinking:

**Comment by mrjones-plip** [comment]
oh my gosh! progress! I checked out hash 3d00f5ffc34510ce43dae26190ef41f57ea01154 , the one right before we committed Enketo - and it works! so - not a `node 12`  thing OR a python 2.7 thing then, yeah? My success just now was on Ubuntu 18 with: 

```
node -v && npm -v && python -V
v12.22.12
6.14.16
Python 2.7.17
```

All other attempts so have failed until I reverted back to the old hash.

**Comment by dianabarsan** [comment]
This strikes me as strange: 
```
>> ERR! stack Error: not found: make
```

Do you have `make` installed?

**Comment by dianabarsan** [comment]
Can we close this out then?
