### ISSUE TITLE
Improve admin upgrade page UX when upgrade service fails to update containers

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7859]
**What feature do you want to improve?**
If an upgrade goes well, we expect API to be down for a couple of seconds, while the new container boots up. This means that the admin upgrade page expects to receive http errors while requesting upgrade progress. 

At the same time, when we call the upgrade endpoint to finalize the upgrade, and the request succeeds, we check whether our currently installed version is the version that we requested via the upgrade. If it is not, we display an error: 

![image](https://user-images.githubusercontent.com/35681649/197211475-37c29a49-38a9-42c5-8469-560ab3976b99.png)

The browser logs will only display an error without any details: 

![image](https://user-images.githubusercontent.com/35681649/197211727-0dbe66e2-f1f2-4b80-8139-05dc9e3a0ef4.png)

API logs will not report an error: 
```
2022-10-21 13:38:06 INFO: Saving ddocs for medic-users-meta 
2022-10-21 13:38:06 INFO: Staging complete 
2022-10-21 13:38:06 INFO: Indexing staged views 
2022-10-21 13:38:06 INFO: Indexing views complete 
2022-10-21 13:38:06 INFO: Completing install 
REQ 56bb7cba-9d82-46c0-aa1c-4c4e492ab491 192.168.176.1 - GET /api/v2/upgrade HTTP/1.0
RES 56bb7cba-9d82-46c0-aa1c-4c4e492ab491 192.168.176.1 - GET /api/v2/upgrade HTTP/1.0 200 906 10.413 ms
2022-10-21 13:38:08 INFO: Install complete 
2022-10-21 13:38:08 INFO: Finalizing install 
2022-10-21 13:38:08 INFO: Detected ddoc change - reloading 
2022-10-21 13:38:09 INFO: Deleting existent staged ddocs 
2022-10-21 13:38:09 INFO: Install finalized 
2022-10-21 13:38:09 INFO: Running DB compact and view cleanup for medic 
2022-10-21 13:38:09 INFO: Running DB compact and view cleanup for medic-sentinel 
2022-10-21 13:38:09 INFO: Running DB compact and view cleanup for medic-logs 
2022-10-21 13:38:09 INFO: Running DB compact and view cleanup for medic-users-meta 
REQ 1c127a1b-b657-4a7c-adbd-bb5c85b39d62 192.168.176.1 - GET /api/v2/upgrade HTTP/1.0
2022-10-21 13:38:09 INFO: Last upgrade log is already final. 
RES 1c127a1b-b657-4a7c-adbd-bb5c85b39d62 192.168.176.1 - GET /api/v2/upgrade HTTP/1.0 200 15 10.805 ms
REQ 4c8a6e9a-d25a-43bb-beb8-da36daea155b 192.168.176.1 - GET /api/deploy-info HTTP/1.0
RES 4c8a6e9a-d25a-43bb-beb8-da36daea155b 192.168.176.1 - GET /api/deploy-info HTTP/1.0 200 86 3.770 ms
2022-10-21 13:38:09 DEBUG: Checking for a configured outgoing message service 
```

The success of the upgrade call actually indicates an error. The most common error can be that the docker compose files were not updated (because of a name mismatch - see https://github.com/medic/cht-upgrade-service/issues/9). 

**Describe the improvement you'd like**
Analyze response from upgrade call to cht-upgrade-service. 
If the `cht-core` compose file was not updated, display an error in api logs to indicate this.

**Describe alternatives you've considered**
None. 

**Additional context**

**Comment by dianabarsan** [comment]
This is ready for AT for self-hosted on: `7859-no-doc-error`. Links to compose files are in the PR: https://github.com/medic/cht-core/pull/7863 . 

To AT: 
- download the docker compose files for this branch
- save them in a folder with different names
- start cht-upgrade-service pointing to the folder above
- upgrade to a different branch
- check errors in API

**Comment by dianabarsan** [comment]
Hi @ngaruko 

Seem that you're hitting the pull rate limit :) 
This is fixed in the `cht-upgrade-service.` and is also ready for AT: https://github.com/medic/cht-upgrade-service/issues/20

**Comment by lorerod** [comment]
**Environment**
Instance: Local using compose files from [PR](https://github.com/medic/cht-core/pull/7863) 
Browser: Chrome
Client platform: MacOS
App: Webapp
Version: 4.0.0-7859-no-doc-error

**Steps to reproduce:**
1. Download the docker compose files from PR
2. Save them in a folder with different names (cht-core-renamed.yml and cht-couchdb-renamed.yml)
3. Download the docker compose file of cht-upgrade-service from `main` branch  
4. Start cht-upgrade-service pointing to the folder created in step 2.
5. Try to upgrade to a different branch (save-couchdb-creds (~4.0.0))
6. The upgrade page shows `Error triggering update` error and the version doesn't change:

![Captura de Pantalla 2022-11-08 a la(s) 11 43 01](https://user-images.githubusercontent.com/21312057/200599792-c84a1117-14e1-44db-a32c-ebaf578c16db.png)

8. The api log displays the error:
```
2022-11-08 14:42:36 ERROR: None of the docker-compose files or containers were updated: {

  'cht-couchdb.yml': {

    ok: false,

    reason: "Existing installation not found. Use '/install' API to install."

  },

  'cht-core.yml': {

    ok: false,

    reason: "Existing installation not found. Use '/install' API to install."

  },

  'cht-couchdb-clustered.yml': {

    ok: false,

    reason: "Existing installation not found. Use '/install' API to install."

  }

} 

2022-11-08 14:42:36 ERROR: If deploying through docker-compose, please make sure that the CHT docker-compose files that you wish to be updated match the naming convention. 

2022-11-08 14:42:36 ERROR: If deploying through kubernetes, please make sure the containers you wish to be upgraded match the naming convention. 

2022-11-08 14:42:36 INFO: Last upgrade log is already final. 

2022-11-08 14:42:36 INFO: Valid Upgrade log tracking file was not found. Not updating. 

2022-11-08 14:42:36 ERROR: Error thrown while installing: Error: No containers were updated

    at Object.makeUpgradeRequest (/api/src/services/setup/utils.js:338:11)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async Object.complete (/api/src/services/setup/upgrade-steps.js:121:20)

    at async complete (/api/src/services/setup/upgrade.js:60:20)

    at async safeInstall (/api/src/services/setup/upgrade.js:45:5) {

  [stack]: 'Error: No containers were updated\n' +

    '    at Object.makeUpgradeRequest (/api/src/services/setup/utils.js:338:11)\n' +

    '    at runMicrotasks (<anonymous>)\n' +

    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +

    '    at async Object.complete (/api/src/services/setup/upgrade-steps.js:121:20)\n' +

    '    at async complete (/api/src/services/setup/upgrade.js:60:20)\n' +

    '    at async safeInstall (/api/src/services/setup/upgrade.js:45:5)',

  [message]: 'No containers were updated'

} 

REQ 3f1094a3-0cfd-4296-80e5-0ca8921c2607 172.24.0.1 - GET /api/v2/upgrade HTTP/1.0

2022-11-08 14:42:38 INFO: Last upgrade log is already final. 
```

**Comment by dianabarsan** [comment]
I'm a bit intrigued as to why you're seeing BOTH "deployment complete" _and_ "error triggering update". I'll have to look into that.

**Comment by dianabarsan** [comment]
I'm not seeing the "deployment complete" locally.
I did manage to replicate it if I first tried to upgrade to the current version (which reported as successful, because we already were on the current version). 

If you could, please, try again, just open the upgrade page and directly try to upgrade to a different branch? 
I'll open a different issue to make sure we clear the "success" status when initiating a new upgrade.

**Comment by lorerod** [comment]
**Retested**
**Environment**
Instance: Local using compose files from [PR](https://github.com/medic/cht-core/pull/7863) 
Browser: Chrome
Client platform: MacOS
App: Webapp
Version: 4.0.0-7859-no-doc-error

**Steps to reproduce:**
1. Download the docker compose files from PR
2. Save them in a folder with different names (cht-core-renamed.yml and cht-couchdb-renamed.yml)
3. Download the docker compose file of cht-upgrade-service from `main` branch  
4. Start cht-upgrade-service pointing to the folder created in step 2.
5. Try to upgrade to a different branch (save-couchdb-creds (~4.0.0))
6. The upgrade page:
- [X] Shows `Error triggering update` error
- [X] Do not show `Deployment complete` green message
- [X] The version doesn't change

<details>
<summary>Screenshot:</summary>

![Captura de Pantalla 2022-11-08 a la(s) 14 53 07](https://user-images.githubusercontent.com/21312057/200639538-f0526b9f-80ee-4019-8a1b-676009723bd4.png)


</details>

7. The api log displays the error:
<details>
<summary>cht-upgrade-service log:</summary>

```
2022-11-08 17:52:25 ERROR: None of the docker-compose files or containers were updated: {

  'cht-couchdb.yml': {

    ok: false,

    reason: "Existing installation not found. Use '/install' API to install."

  },

  'cht-core.yml': {

    ok: false,

    reason: "Existing installation not found. Use '/install' API to install."

  },

  'cht-couchdb-clustered.yml': {

    ok: false,

    reason: "Existing installation not found. Use '/install' API to install."

  }

} 

2022-11-08 17:52:25 ERROR: If deploying through docker-compose, please make sure that the CHT docker-compose files that you wish to be updated match the naming convention. 

2022-11-08 17:52:25 ERROR: If deploying through kubernetes, please make sure the containers you wish to be upgraded match the naming convention. 

2022-11-08 17:52:25 INFO: Last upgrade log is already final. 

2022-11-08 17:52:25 INFO: Valid Upgrade log tracking file was not found. Not updating. 

2022-11-08 17:52:25 ERROR: Error thrown while installing: Error: No containers were updated

    at Object.makeUpgradeRequest (/api/src/services/setup/utils.js:338:11)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async Object.complete (/api/src/services/setup/upgrade-steps.js:121:20)

    at async complete (/api/src/services/setup/upgrade.js:60:20)

    at async safeInstall (/api/src/services/setup/upgrade.js:45:5) {

  [stack]: 'Error: No containers were updated\n' +

    '    at Object.makeUpgradeRequest (/api/src/services/setup/utils.js:338:11)\n' +

    '    at runMicrotasks (<anonymous>)\n' +

    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +

    '    at async Object.complete (/api/src/services/setup/upgrade-steps.js:121:20)\n' +

    '    at async complete (/api/src/services/setup/upgrade.js:60:20)\n' +

    '    at async safeInstall (/api/src/services/setup/upgrade.js:45:5)',

  [message]: 'No containers were updated'

} 

REQ 6ac17551-ecc0-4b38-b7ef-4b58e16fc9a3 172.26.0.1 - GET /api/v2/upgrade HTTP/1.0

2022-11-08 17:52:26 INFO: Last upgrade log is already final. 
```

<details>

**Comment by dianabarsan** [comment]
Thanks so much @lorerod 

I'll create the issue about clearing the success status shortly.

**Comment by lorerod** [comment]
Thank to you @dianabarsan. I will follow up on that issue.
