### ISSUE TITLE
Submit an undo death report "before all" hook for Submit an undo death report frequently fails

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7916]
**Describe the issue**
Very frequently, `ci-webdriver-default` CI test fails with:
```
[Chrome Headless 107.0.5304.87 linux #0-23] 1) Submit an undo death report "before all" hook for Submit an undo death report
[Chrome Headless 107.0.5304.87 linux #0-23] element (".header-logo") still not displayed after 15000ms
[Chrome Headless 107.0.5304.87 linux #0-23] Error: element (".header-logo") still not displayed after 15000ms
[Chrome Headless 107.0.5304.87 linux #0-23]     at /home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/commands/browser/waitUntil.js:66:23
[Chrome Headless 107.0.5304.87 linux #0-23]     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 107.0.5304.87 linux #0-23]     at async Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:24:32)
[Chrome Headless 107.0.5304.87 linux #0-23]     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 107.0.5304.87 linux #0-23]     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 107.0.5304.87 linux #0-23]     at async Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:24:32)
[Chrome Headless 107.0.5304.87 linux #0-23]     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
[Chrome Headless 107.0.5304.87 linux #0-23]     at async waitForPageLoaded (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:177:3)
[Chrome Headless 107.0.5304.87 linux #0-23]     at async Object.goToPeople (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:97:5)
[Chrome Headless 107.0.5304.87 linux #0-23]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/enketo/undo-death-report.wdio-spec.js:25:5)
```

**Describe the improvement you'd like**
Stabilize the e2e test.

**Comment by dianabarsan** [comment]
Because this is the "before all", we don't have a screenshot of what was happening in the browser either :(
