### ISSUE TITLE
Show a more useful error message when decrypting using a different secret

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7926]
**What feature do you want to improve?**
The Credentials service uses a configurable key to do the encryption/decryption.

**Describe the improvement you'd like**
Right now if you set a credential, then change the key, then try to decrypt the credential you get a cryptic (no pun intended) error message.

```
REQ 7ed1d44f-c54a-4ea8-bcb3-5e72258e81ca 172.21.0.1 - POST /api/v2/sms/rapidpro/incoming-messages HTTP/1.0
2022-11-24 09:01:32 WARN: Non-numeric error code: ERR_OSSL_EVP_BAD_DECRYPT 
2022-11-24 09:01:32 ERROR: Server error: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at /shared-libs/settings/src/index.js:67:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [stack]: 'Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt\n' +
    '    at Decipheriv.final (node:internal/crypto/cipher:193:29)\n' +
    '    at /shared-libs/settings/src/index.js:67:30\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
  [message]: 'error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt',
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
} 
```

The fix is to set the credential again which uses the new encryption key, but it's hard to tell that from the error message. Replace this error message with a more useful one which lets you know how to fix it.

**Describe alternatives you've considered**
None...

**Additional context**
[Initially reported here](https://github.com/medic/cht-core/issues/7472#issuecomment-1326153603).

**Comment by garethbowen** [comment]
Ready for AT in https://github.com/medic/cht-core/pull/7929

To test...

1. Set up rapidpro integration including setting the credential
2. Test that the integration works as expected
3. Change the CouchDB `secret` value through `/_utils`. This will break the rapidpro integration because the credential will fail to decrypt.
4. Ensure that the error message is useful, and if you follow the instructions, it fixes the rapidpro integration again
