### ISSUE TITLE
Flaky e2e test `Submit Default Delivery Report`

### ISSUE THREAD

**Issue by m5r** [medic/cht-core#7966]
**Describe the issue**
`Submit Default Delivery Report open, submit and edit default delivery form` sometimes fails with the following error message:
```
Error: element ("li[data-record-id="25baef77-f5a1-409f-a230-7d13ee291de9"]") still not displayed after 15000ms
     at /home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/commands/browser/waitUntil.js:66:23
     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
     at async Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:24:32)
     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
     at async Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:24:32)
     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
     at async openReport (/home/runner/work/cht-core/cht-core/tests/page-objects/default/reports/reports.wdio.page.js:341:3)
     at async Object.editReport (/home/runner/work/cht-core/cht-core/tests/page-objects/default/reports/reports.wdio.page.js:348:3)
     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/enketo/submit-default-delivery-form.wdio-spec.js:270:5)
```

[Example run #1](https://github.com/medic/cht-core/actions/runs/3628093421/jobs/6119449670#step:15:776)
[Example run #2](https://github.com/medic/cht-core/actions/runs/3628093421/jobs/6123924969#step:15:759)

**Describe the improvement you'd like**
Stabilize the test

**Describe alternatives you've considered**
None

**Comment by garethbowen** [comment]
Screenshot from this failure:

![38a3f22f-aea7-462c-97ba-d8ef6dfcb1a8-attachment](https://user-images.githubusercontent.com/2064938/217990235-5ca737d9-45f1-4688-b180-23602d58c9d3.png)

browser log:
```
~~~~~~~~~~~~~ open, submit and edit default delivery form ~~~~~~~~~~~~~~~~~~~~~~
[error]: network Failed to load resource: the server responded with a status of 404 (Object Not Found) url: https://localhost/medic/form%3ADD? at 1675996925493.0078
[warning] Console Api Event: [{"type":"string","value":"Error in XMLFormService : getById : "},{"type":"string","value":"missing"},{"type":"number","value":404,"description":"404"},{"type":"object","className":"Object","description":"Object","objectId":"-186777668109747162.10.9","preview":{"type":"object","description":"Object","overflow":true,"properties":[{"name":"error","type":"string","value":"not_found"},{"name":"reason","type":"string","value":"missing"},{"name":"status","type":"number","value":"404"},{"name":"name","type":"string","value":"not_found"},{"name":"message","type":"string","value":"missing"}]}}]
[warning] Console Api Event: [{"type":"string","value":"Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored."}]
[error]: network Failed to load resource: the server responded with a status of 404 (Object Not Found) url: https://localhost/medic/form%3ADD? at 1675996931118.184
[warning] Console Api Event: [{"type":"string","value":"Error in XMLFormService : getById : "},{"type":"string","value":"missing"},{"type":"number","value":404,"description":"404"},{"type":"object","className":"Object","description":"Object","objectId":"-186777668109747162.10.10","preview":{"type":"object","description":"Object","overflow":true,"properties":[{"name":"error","type":"string","value":"not_found"},{"name":"reason","type":"string","value":"missing"},{"name":"status","type":"number","value":"404"},{"name":"name","type":"string","value":"not_found"},{"name":"message","type":"string","value":"missing"}]}}]
[warning] Console Api Event: [{"type":"string","value":"Attempt to run transitions without initialization"}]
[debug] Console Api Event: [{"type":"string","value":"You have administrative privileges; not replicating"}]
[error]: network Failed to load resource: the server responded with a status of 404 (Object Not Found) url: https://localhost/medic/privacy-policies? at 1675996953953.415
```

**Comment by garethbowen** [comment]
Change made in attempt to fix this. Please reopen if it happens again.
