### ISSUE TITLE
Flaky e2e test `purge`

### ISSUE THREAD

**Issue by m5r** [medic/cht-core#7967]
**Describe the issue**
`purge purging runs on sync and startup` sometimes fails with the following error message:
```
Error: Protocol error (Runtime.getProperties): Cannot find context with specified id
     at /home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/Connection.ts:291:57
     at new Promise (<anonymous>)
     at CDPSession.send (/home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/Connection.ts:290:12)
     at JSHandle.getProperties (/home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/JSHandle.ts:227:41)
     at Object.internalHandler.queryAll (/home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/QueryHandler.ts:84:41)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async DOMWorld.$$ (/home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/DOMWorld.ts:225:19)
     at async DevToolsDriver.findElements (/home/runner/work/cht-core/cht-core/node_modules/devtools/build/utils.js:121:11)
     at async Browser.wrappedCommand (/home/runner/work/cht-core/cht-core/node_modules/devtools/build/devtoolsdriver.js:102:26)
     at async Browser.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
```

[Example run](https://github.com/medic/cht-core/actions/runs/3628093421/jobs/6121874067#step:15:938)

**Describe the improvement you'd like**
Stabilize the test

**Describe alternatives you've considered**
None

**Comment by garethbowen** [comment]
Success rate as of today: 83%

**Comment by tatilepizs** [comment]
Closing it because it has not been failing over the last two months.
