### ISSUE TITLE
Flaky e2e test `Message tab breadcrumbs`

### ISSUE THREAD

**Issue by m5r** [medic/cht-core#7969]
**Describe the issue**
`Message tab breadcrumbs should display messages with breadcrumbs for online user` sometimes fails with the following error message:
```
Error: waitUntil condition failed with the following reason: element ("#message-list li:nth-child(1)") still not displayed after 15000ms
     at /home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15
     at async Browser.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
     at async Object.waitForMessagesInLHS (/home/runner/work/cht-core/cht-core/tests/page-objects/default/sms/messages.wdio.page.js:5:42)
     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/sms/messages-breadcrumbs.wdio-spec.js:69:5)
```

It also makes the `after each` hook fail with the following error message:
```
Error: Can't call click on element with selector "#header-dropdown li .fa-power-off" because element wasn't found
     at implicitWait (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/utils/implicitWait.js:34:19)
     at async Element.elementErrorHandlerCallbackFn (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/middlewares.js:20:29)
     at async Element.wrapCommandFn (/home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:131:29)
     at async navigateToLogoutModal (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:67:3)
     at async Object.logout (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:72:3)
     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/sms/messages-breadcrumbs.wdio-spec.js:60:5)
```

[Example run](https://github.com/medic/cht-core/actions/runs/3628093421/jobs/6118960448#step:15:1051)

I took a first look at it and it seems like the recipient selection sometimes fail because the select2 suggestions never show up.

**Describe the improvement you'd like**
Stabilize the test

**Describe alternatives you've considered**
None

**Comment by garethbowen** [comment]
Success rate as of today: 100%

**Comment by m5r** [comment]
That's amazing! It makes sense to close the issue now that this test isn't flaky anymore

**Comment by garethbowen** [comment]
Let's just leave it open... that's 100% of 12 runs which probably isn't a big enough sample size. Once we get 100% of maybe 25 I'd agree with you  :)

**Comment by tatilepizs** [comment]
Closing it because it has not been failing over the last month.
