### ISSUE TITLE
Admin app fails to update `branding` if existing document is malformed

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8026]
**Describe the bug**
A malformed `branding` doc will block the user from updating branding from the admin app. No error is shown in the UI, only in console. 

**To Reproduce**
1. Create an `branding.json` document in your config. Set the contents of this document to be `{}`. run `cht upload-branding`. 
2. Login to admin app. Go to Images -> Branding.
3. Change the logo file. 
4. Click Submit. Nothing happens.

**Expected behavior**
The UI should inform the user that the existing document is malformed. 
Even when the document is malformed, the user should have the possibility to "fix" it by editing from the Admin UI. 

**Logs**
```
angular.js:15697 Error fetching resources file TypeError: Cannot read properties of undefined (reading 'favicon')
    at images-branding.js:24:29
    at processQueue (angular.js:18075:1)
    at angular.js:18123:1
    at Scope.$digest (angular.js:19242:1)
    at angular.js:19562:1
    at TaskTracker.completeTask (angular.js:21403:1)
    at angular.js:6879:1
```

**Environment**
- Instance: any
- App: admin
- Version: 3.4.0+

**Additional context**
[Form post](https://forum.communityhealthtoolkit.org/t/branding-not-working-using-admin-interface/2399/21)

**Comment by jarias** [comment]
Hi this is Julio from Edify can you assign this to me

**Comment by mrjones-plip** [comment]
Note - I added all the "Affects" labels, but we don't have them going all the back to `3.4`.  I'm not adding more labels though.
