### ISSUE TITLE
Flaky unit test TrainingCardsComponent saveForm should call enketo save, set content in snackbar and unload form

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8125]
**Describe the issue**
Example run where this unit test failed: https://github.com/medic/cht-core/actions/runs/4418714580/jobs/7746190464#step:11:5983
```
FAILED TESTS:
  TrainingCardsComponent
    saveForm
      ✖ should call enketo save, set content in snackbar and unload form
        Chrome Headless 110.0.5481.177 (Linux x86_64)
      AssertionError: expected false to be true

      + expected - actual

      -false
      +true
      
    at Context.apply (_karma_webpack_/webpack:/tests/karma/ts/modals/training-cards/training-cards.component.spec.ts:242:64)
    at Context.apply (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:2030:30)
    at _ZoneDelegate.invoke (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:26)
    at ProxyZoneSpec.onInvoke (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:39)
    at _ZoneDelegate.invoke (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:52)
    at Zone.run (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:43)
    at Context.<anonymous> (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1046:33)
```

**Comment by latin-panda** [comment]
@Benmuiruri I'm having a hard time trying to reproduce this issue:
- I've tried running it local multiple times 
  - This test case only
  - This file only
  - Also, all unit tests 
- I haven't seen it failing in other people's PRs ([open PRs](https://github.com/medic/cht-core/pulls) and [past PRs from recent months](https://github.com/medic/cht-core/pulls?q=is%3Apr+is%3Aclosed)) 

It seems fixed, but I don't know what fixed it. No big changes in those files -- so maybe a side effect of something else?

Ben, can you please try it?

**Comment by Benmuiruri** [comment]
I've tested in `master` and I have not been able to reproduce. 
- The test case passes 
- The test suite `describe.only('TrainingCardsComponent', () => {}` passes 
- The webapp unit tests pass `npm run unit-webapp`
- All unit tests pass `npm run unit`

**Comment by latin-panda** [comment]
Thanks @Benmuiruri
I'm closing the ticket for now. Let's keep an eye on these tests, if it happens again, let's reopen the issue.
