### ISSUE TITLE
Duplicate outbound requests are sent when a document matches multiple config options

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8160]
**Describe the bug**
Described very aptly on the forum: https://forum.communityhealthtoolkit.org/t/outbound-destination-property/2485/5 and https://forum.communityhealthtoolkit.org/t/outbound-destination-property/2485/3

> However, we are seeing one object outbound being executed twice for the same form. Never the first one and it works if it’s only one outbound object, but if we have two outbound objects, the second one is executed twice. If there are three the second and the third one are executed twice as well.

**To Reproduce**
1. Create two identical outbound configs (they need different names, but everything else should be identical)
2. Submit a document that matches the relevancy condition
3. Wait for the document to be processed and for the outbound queue to clear (could take up to 10 minutes)
4. Check outbound recipient requests and notice there were three calls, instead of 2. 

**Expected behavior**
Only two requests should be executed. 

**Logs**
No errors in the logs

**Environment**
- App: sentinel
- Version: 3.9+ 

**Additional context**
In order to figure out what was going on, I had to add debug messages all over the outbound code, and I ended up with logging the error that we received here: 
https://github.com/medic/cht-core/blob/master/shared-libs/transitions/src/transitions/mark_for_outbound.js#L47

and it is: 
```
{
  error: 'conflict',
  reason: 'Document update conflict.',
  status: 409,
  name: 'conflict',
  message: 'Document update conflict.',
  stack: 'Error\n' +
    '    at Object.generateErrorFromResponse (/sentinel/node_modules/pouchdb-errors/lib/index.js:104:18)\n' +
    '    at /sentinel/node_modules/pouchdb-adapter-http/lib/index.js:254:33\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
  docId: '41ac853d-9e76-479b-ac6a-1dd2dea52969-info'
}
```
This is because the same infodoc gets updated when outbound succeeds, but we don't bother updating the rev to allow successive edits. https://github.com/medic/cht-core/blob/master/shared-libs/transitions/src/transitions/mark_for_outbound.js#L44

This causes every following outbound "block" to throw an error and generate a task - that would trigger another outbound request on a schedule - even if the initial request was actually successful.

**Comment by dianabarsan** [comment]
This same issue - with a double conflict on saving infodocs - can also manifest as a race condition. 
I'm seeing this happen often in e2e tests when running the CouchDb 3 build. So far it's unclear why this race condition is triggered much more easily, but I'm scheduling this for 4.3, to fix along with the CouchDb 3 work.

**Comment by dianabarsan** [comment]
Example of this race condition manifesting in a current build: https://github.com/medic/cht-core/actions/runs/4880312327/jobs/8708080331?pr=8170#step:16:1502
