### ISSUE TITLE
Monitoring sentinel when "Transitions are disabled" is difficult

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8162]
**Describe the bug**
On a production instance we're seeing the `/api/v2/monitoring` return an ever growing value for sentinel backlog.  The sentinel container logs are showing that the backlog is up to do date though. 

**To Reproduce**
1. Deploy an instance with CHT 4.1.0
2. Have activities that require sentinel transitions
3. Ensure transitions are actually getting processed but  `/api/v2/monitoring`  shows backlog going up

**Expected behavior**
 `/api/v2/monitoring`  and actual back log are in sync

**Logs**

```
2023-03-31 14:48:11 DEBUG: Initiating all tasks
2023-03-31 14:48:11 INFO: Task dueTasks started
2023-03-31 14:48:11 INFO: Task reminders started
2023-03-31 14:48:11 INFO: Task replications started
2023-03-31 14:48:11 INFO: Task outbound started
2023-03-31 14:48:11 INFO: Task purging started
2023-03-31 14:48:11 INFO: Task backgroundCleanup started
2023-03-31 14:48:11 INFO: Task reminders completed
2023-03-31 14:48:11 INFO: Task replications completed
2023-03-31 14:48:11 INFO: Task outbound completed
2023-03-31 14:48:11 INFO: Task purging completed
2023-03-31 14:48:11 INFO: Task dueTasks completed
2023-03-31 14:48:11 INFO: Background cleanup batch: 95881 -> 95881 (0)
2023-03-31 14:48:11 INFO: Task backgroundCleanup completed
```

**Environment**
- Instance: MoH Mali CHW
- Browser:  NA
- Client platform: NA
- App:  sentinel 
- Version: 4.1.0

**Additional context**
[App Monitoring showed](https://github.com/medic/config-moh-mali-chw/issues/651) (private GH issue) that this happened EXACTLY after we upgrade from 4.0.1 to 4.1.0 on Mar 9th:

![image](https://user-images.githubusercontent.com/8253488/229173652-6e2a13c8-acd0-48f2-8ed9-1ec5ae997996.png)

Possibly related to the last time this bui happened in #7113 ?

**Comment by kennsippell** [comment]
```
2023-04-03 22:30:21 ERROR: Failed loading transition "muting" 
2023-04-03 22:30:21 ERROR: Error: Configuration error. Config must define have a 'muting.mute_forms' array defined.
    at Object.init (/home/kenn/cht-core/shared-libs/transitions/src/transitions/muting.js:181:13)
    at Object.loadTransition [as _loadTransition] (/home/kenn/cht-core/shared-libs/transitions/src/transitions/index.js:184:16)
    at /home/kenn/cht-core/shared-libs/transitions/src/transitions/index.js:149:12
    at Array.forEach (<anonymous>)
    at Object.loadTransitions (/home/kenn/cht-core/shared-libs/transitions/src/transitions/index.js:139:25)
    at Object.loadTransitions (/home/kenn/cht-core/sentinel/src/transitions.js:10:20)
    at /home/kenn/cht-core/sentinel/src/config.js:64:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2023-04-03 22:30:21 WARN: Disabled transition "mark_for_outbound" 
2023-04-03 22:30:21 INFO: Loading transition "create_user_for_contacts" 
2023-04-03 22:30:21 ERROR: Transitions are disabled until the above configuration errors are fixed
```

This can be fixed in app configuration by disabling the muting transition. There are no muting forms for this project. 

Is sentinel doing nothing in this state? What is the purpose of having sentinel run but do nothing like this? Should we fail fast?

**Comment by dianabarsan** [comment]
> Is sentinel doing nothing in this state? 

This is correct, Sentinel is doing nothing in this state.

**Comment by dianabarsan** [comment]
> Or could we at least re-print this error each 5 minutes so this isn't a needle in a haystack?

I think this is a great suggestion.

**Comment by kennsippell** [comment]
Another option is a boolean flag for `is sentinel processing docs` in monitoring api?

**Comment by dianabarsan** [comment]
> boolean flag for is sentinel processing docs in monitoring api?

That works too. Adding a health check to Sentinel has been something we've discussed several times in the past. Right now, Sentinel doesn't communicate its state except for the two "seq" docs, which are already used by the monitoring API. 

> Are there more details on what this mean?

So far, nothing is settled. High level vision would be that logs are scanned for errors and other significant entries, with filtered entries being funneled into a digestible dashboard of sorts.

**Comment by mrjones-plip** [comment]
Thanks for the clean up of title and labels of this ticket @kennsippell  - much appreciated!

**Comment by kennsippell** [comment]
Ready for AT on `8162-logs-errors-when-trans-disabled`

To test this - update an `app_settings.json` with an unknown or crashing transition.  Look at sentinel logs and verify there is a descriptive error. Wait 5 minutes and verify the descriptive error is reprinted.

**Comment by mrjones-plip** [comment]
@kennsippell  - to be a bit more explicit for QA on how to test, "unknown or crashing transition" could be achieved with `smang`  in  `app_settings.json` , yeah?

```
  "transitions": {
    "smang": true
  }
```

**Comment by kennsippell** [comment]
Merged. Spoke with @ngaruko about [the e2e test suggestion](https://github.com/medic/cht-core/issues/8162#issuecomment-1534244273). He said he'd look at existing tests and file a followup ticket as needed.
