### ISSUE TITLE
Add visibility to documents that were blocked from replication

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8186]
**Is your feature request related to a problem? Please describe.**
When an offline user syncs up (uploads documents), API checks whether that specific user has access to create / update those documents. When a user pushes a doc they should not be allowed to create or edit, the doc is not saved in the main `medic` database, and the request returns a `denied` response for that doc. Upload is retried 3 times for each denied document. A telemetry entry is recorded every time a denied event happens. 
There is no visibility, however, on what the these docs are, as they never get stored on the server, and POST bodies are not logged in nginx or API. 

Reasons for denied docs to exist are: 
- move contacts produces docs with incorrect lineages
- supervisors submitting reports for subjects they can't see and the reports lack `needs_signoff` property
- reports with incorrect fields (form/task issues), not linking to the correct subject
- config changes that affect previously created docs
- incorrect replication (user device having docs they shouldn't have)

**Describe the solution you'd like**
Discuss ways to make the contents of these docs available for analysis. 

**Describe alternatives you've considered**
If these events are sufficiently rare, as we initially believed, we could choose to continue to ignore these docs. 

**Additional context**
[The issue](https://github.com/medic/cht-core/issues/6103) where denied replication was initially addressed.

**Comment by mrjones-plip** [comment]
Here/s [the Slack thread](https://medic.slack.com/archives/C03CYKC7NUD/p1681757018458629) where a deployment had hundreds of denied replecation telemetry points of over a period of a month.

**Comment by kennsippell** [comment]
This is a fairly common source of data-loss across the CHT projects we monitor via app-monitoring-ingest

month | sum of replication_denied_count
-- | --
2023-02-01 | 564
2023-03-01 | 2598
2023-04-01 | 719

Data uses [this query](https://github.com/medic/cht-app-monitoring-data-ingest/blob/main/postgres/matviews/replication_by_status.sql#L10) +

```
select 
  date_trunc('month', period_start),
  SUM(replication_denied_count)
from app_monitoring_replication_by_status
group by 1
order by 1
```

**Comment by dianabarsan** [comment]
> Could we make a new type of feedback doc?

Yes. So you'd opt for storing in `users-meta` and coalescing, just like any other feedback doc?

**Comment by kennsippell** [comment]
If we put the denied doc into the users-meta-db this might be the first time we put PHI into that database.  Presently, Medic sometimes asks selfhost partners to give us access to the meta database to help support them through complex technical matters, performance issues in production, errors in production, etc.   We say "there is no PHI" to get this access. 

Unsure if this is bad or a blocker. 
For now, I'm just making a note that this would cross a line not previously crossed.

**Comment by dianabarsan** [comment]
That's a great point @kennsippell . 
I'm now wondering if PHI could make it to the browser console and somehow end up in a feedback doc already.

**Comment by dianabarsan** [comment]
As I am working on feedback docs right now, I'm wondering if we should address this now / soon or at least discuss what we want to do. 

At the moment, the feedback document for a denied replication will look something like: 
```
[0-0]    {
[0-0]       "meta": {
[0-0]         "time": "2023-09-20T11:04:36.108Z",
[0-0]         "user": {
[0-0]           "name": "user1",
[0-0]           "roles": [
[0-0]             "chw"
[0-0]           ]
[0-0]         },
[0-0]         "language": "en",
[0-0]         "url": "https://localhost/#/messages",
[0-0]         "version": "4.3.0-local-development (~4.3.0)",
[0-0]         "source": "automatic",
[0-0]         "deviceId": "c9a65b96-6fce-4515-b228-3cc908535e43"
[0-0]       },
[0-0]       "info": {
[0-0]         "message": "Denied replicating to remote server",
[0-0]         "stack": "Error\n    at generateErrorFromResponse (https://localhost/main.js:149143:17)\n    at https://localhost/main.js:154819:20\n    at Array.map (<anonymous>)\n    at https://localhost/main.js:154817:35\n    at _ZoneDelegate.invoke (https://localhost/polyfills.js:2705:158)\n    at Zone.run (https://localhost/polyfills.js:2489:37)\n    at https://localhost/polyfills.js:3581:28\n    at _ZoneDelegate.invokeTask (https://localhost/polyfills.js:2732:171)\n    at Zone.runTask (https://localhost/polyfills.js:2535:39)\n    at drainMicroTaskQueue (https://localhost/polyfills.js:2903:23)"
[0-0]       },
[0-0]       "log": [
[0-0]         {
[0-0]           "level": "error",
[0-0]           "arguments": "[\"Denied replicating to remote server\",{\"id\":\"31eadcc1-c9cf-49b7-9c65-0361038991ee\",\"error\":\"forbidden\",\"name\":\"forbidden\",\"status\":500,\"stack\":\"Error\\n    at generateErrorFromResponse (https://localhost/main.js:149143:17)\\n    at https://localhost/main.js:154819:20\\n    at Array.map (<anonymous>)\\n    at https://localhost/main.js:154817:35\\n    at _ZoneDelegate.invoke (https://localhost/polyfills.js:2705:158)\\n  at Zone.run (https://localhost/polyfills.js:2489:37)\\n    at https://localhost/polyfills.js:3581:28\\n    at _ZoneDelegate.invokeTask (https://localhost/polyfills.js:2732:171)\\n    at Zone.runTask (https://localhost/polyfills.js:2535:39)\\n    at drainMicroTaskQueue (https://localhost/polyfills.js:2903:23)\"}]",
[0-0]           "time": "2023-09-20T11:04:36.106Z"
[0-0]         },
[0-0]         {
[0-0]           "level": "info",
[0-0]           "arguments": "[\"Replication started after 3 seconds since previous attempt\"]",
[0-0]           "time": "2023-09-20T11:04:36.010Z"
[0-0]         },
}
[0-0]       ],
[0-0]       "type": "feedback",
[0-0]       "_id": "feedback-2023-09-20T11:04:36.108Z-de3cdecb-f585-4582-9f8a-a4e38787ddb6",
[0-0]       "_rev": "1-2f33e6a40f20a7a0ca8653955b8f6aa9",
[0-0]     }
```

It contains no PHI. the only info about the "failed" doc is the uuid.

**Comment by dianabarsan** [comment]
Denied uploads are already recorded in telemetry. Does the additional feedback only produce noise? We can disable generating these docs, if we choose.

**Comment by garethbowen** [comment]
I assume if it fails today it's also going to fail tomorrow (until someone changes permissions or wipes the local db). We certainly don't want to generate a feedback doc per replication attempt, but I think it's most likely that telemetry on this won't be noticed.

Ultimately I think we'll need some sort of deduping somehow, especially once we're pushing so many more feedback docs. I think Kenn mentioned having an aggregate so we could sync the count of these errors rather than a whole lot of individual copies, which is probably the right outcome, though it may be tricky to work out what is a dupe and what isn't.

Until we have that I think we need to disable generating these docs.
