### ISSUE TITLE
Flaky: ci-e2e-integration - token login 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8252]
**Describe the issue**
This test is frequently failing on branches and on master:

log:
```
1) Users API
       token-login
         when token-login is configured
           should create and update many users correctly with token_login:

      AssertionError: expected IncomingMessage{ …(25), …(6) } to have property 'statusCode' of 302, but got 401
      + expected - actual

      -401
      +302
      
      at /home/runner/work/cht-core/cht-core/tests/integration/api/controllers/users.spec.js:683:34
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/integration/api/controllers/users.spec.js:1192:11)
```

**Comment by dianabarsan** [comment]
I've been already trying to fix this.

**Comment by dianabarsan** [comment]
Merged to `master`.
