### ISSUE TITLE
E2e test generating feedback docs: Edit contacts with default config

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8254]
**Important**: This is a public repository. Anyone in the world can see what's posted here. If you are posting screenshots or log files, please **carefully examine them for** the presence of any kind of **protected health information** (PHI). Images or logs containing PHI _must_ be posted in fully-redacted form, with no visible PHI.

**Describe the bug**
This test fails with:
```
[chrome 113.0.5672.63 linux #0-6] 1) Edit contacts with the default config.  should remove the primary contact from the clinic when the contact is deleted
[chrome 113.0.5672.63 linux #0-6] Feedback docs were generated during the test.
[chrome 113.0.5672.63 linux #0-6] Error: Feedback docs were generated during the test.
[chrome 113.0.5672.63 linux #0-6]     at Object.afterTest (/home/runner/work/cht-core/cht-core/tests/e2e/default/wdio.conf.js:302:31)
[chrome 113.0.5672.63 linux #0-6]     at runMicrotasks (<anonymous>)
[chrome 113.0.5672.63 linux #0-6]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[chrome 113.0.5672.63 linux #0-6]     at async Promise.all (index 0)
[chrome 113.0.5672.63 linux #0-6]     at async executeHooksWithArgsShim (file:///home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/shim.js:50:20)
[chrome 113.0.5672.63 linux #0-6]     at async Context.testFrameworkFnWrapper (file:///home/runner/work/cht-core/cht-core/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:60:40)
```

The error reported in the feedback doc is: 
```
message": "Uncaught (in promise): TypeError: Cannot read properties of null (reading 'doc')\nTypeError: Cannot read properties of null (reading 'doc')\n    at https://localhost/main.js?_sw-precache=b06b2796b1ff7211d2584e5561d38906:1:1249229\n    at Generator.next (<anonymous>)\n    at o$ (https://localhost/main.js?_sw-precache=b06b2796b1ff7211d2584e5561d38906:1:506816)\n    at _ (https://localhost/main.js?_sw-precache=b06b2796b1ff7211d2584e5561d38906:1:507019)\n    at https://localhost/main.js?_sw-precache=b06b2796b1ff7211d2584e5561d38906:1:507080\n    at new d (https://localhost/polyfills.js?_sw-precache=edc39369e9333bcb01fe3d162d9ada63:1:23310)\n    at https://localhost/main.js?_sw-precache=b06b2796b1ff7211d2584e5561d38906:1:506960\n    at r.updateFastActions (https://localhost/main.js?_sw-precache=b06b2796b1ff7211d2584e5561d38906:1:1249504)\n    at https://localhost/main.js?_sw-precache=b06b2796b1ff7211d2584e5561d38906:1:1250955\n    at https://localhost/main.js?_sw-precache=b06b2796b1ff7211d2584e5561d38906:1:992349",
```

**To Reproduce**
TBD

**Expected behavior**
Selecting a contact should not throw uncaught errors. 

**Environment**
- Instance: CI
- Browser: Chrome 
- Client platform: Linux
- App: webapp
- Version: 4.2.0 (?)

**Comment by dianabarsan** [comment]
I am about to disable this test, but here is the most recent failure (in `master`): https://github.com/medic/cht-core/actions/runs/5347610246/jobs/9696616420

**Comment by dianabarsan** [comment]
The whole test file was changed meanwhile, especially by this commit: https://github.com/medic/cht-core/commit/74b43147ea0015372f36f7948408407e34baf8b2 .
