### ISSUE TITLE
Flaky e2e test should display correct due dates with taskDaysOverdue setting and should display correct due dates with taskDaysOverdue setting and simple translation

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8257]
**Describe the issue**
Example of failure: 
https://github.com/medic/cht-core/actions/runs/5022548750/jobs/9006473706?pr=8251#step:16:1306

```
1) Task list due dates should display correct due dates with taskDaysOverdue setting
[chrome 113.0.5672.63 linux #0-62] element ("#header-dropdown-link") still not clickable after 15000ms
[chrome 113.0.5672.63 linux #0-62] Error: element ("#header-dropdown-link") still not clickable after 15000ms
[chrome 113.0.5672.63 linux #0-62]     at async openHamburgerMenu (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:141:5)
[chrome 113.0.5672.63 linux #0-62]     at async syncAndWaitForSuccess (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:274:3)
[chrome 113.0.5672.63 linux #0-62]     at async Object.sync (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:281:3)
```

```
12) Task list due dates should display correct due dates with taskDaysOverdue setting and simple translation
[chrome 113.0.5672.63 linux #0-62] element ("#header-dropdown-link") still not clickable after 15000ms
[chrome 113.0.5672.63 linux #0-62] Error: element ("#header-dropdown-link") still not clickable after 15000ms
[chrome 113.0.5672.63 linux #0-62]     at async openHamburgerMenu (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:141:5)
[chrome 113.0.5672.63 linux #0-62]     at async syncAndWaitForSuccess (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:274:3)
[chrome 113.0.5672.63 linux #0-62]     at async Object.sync (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:281:3)
```

and captured screenshot: 
![image](https://github.com/medic/cht-core/assets/35681649/1846e729-ed67-4bb2-bcd8-33869c66c4fd)

**Describe the improvement you'd like**
Fix the test. The thest be

**Describe alternatives you've considered**

**Comment by tatilepizs** [comment]
Closing it because it has not been failing over the last month.
