### ISSUE TITLE
Flaky e2e test: Add new district tests :  should edit district

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8264]
**Describe the issue**
This test is failing frequently with: 
```
Contact "Caroline's district" was not found
[chrome 113.0.[567](https://github.com/medic/cht-core/actions/runs/5044223021/jobs/9052805386#step:16:568)2.63 linux #0-4] Error: Contact "Caroline's district" was not found
[chrome 113.0.5672.63 linux #0-4]     at selectLHSRowByText (/home/runner/work/cht-core/cht-core/tests/page-objects/default/contacts/contacts.wdio.page.js:99:11)
[chrome 113.0.5672.63 linux #0-4]     at runMicrotasks (<anonymous>)
[chrome 113.0.5672.63 linux #0-4]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[chrome 113.0.5672.63 linux #0-4]     at async Object.editDistrict (/home/runner/work/cht-core/cht-core/tests/page-objects/default/contacts/contacts.wdio.page.js:281:3)
[chrome 113.0.5672.63 linux #0-4]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/contacts/add-new-district.wdio-spec.js:42:5)
```

![image](https://github.com/medic/cht-core/assets/35681649/0109b5d0-11bd-41d2-9dbb-3fde33c2acdb)

subsequent runs are failing with:
```
[chrome 113.0.5672.63 linux #0-4] [
  {
    "id": "one_district",
    "error": "conflict",
    "reason": "Document update conflict."
  },
  {
    "id": "one_person",
    "error": "conflict",
    "reason": "Document update conflict."
  }
]```
so setup doesn't support test retries. 

Example run: https://github.com/medic/cht-core/actions/runs/5044223021/jobs/9052805386


**Describe the improvement you'd like**
change the test setup so retries are possible. Stabilize the test by finding the root cause of the flake.

**Comment by tatilepizs** [comment]
Merged into `master`
PR #8531 -> `chore(#8264): restructured add-new-district.wdio-spec.js test `
