### ISSUE TITLE
Flaky test: Enabling/disabling languages should disable a language and enable another

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8357]
**Describe the issue**
This test is failing with:
```
1) Enabling/disabling languages should disable a language and enable another
waitUntil condition failed with the following reason: Cannot read properties of undefined (reading 'enabled')
Error: waitUntil condition failed with the following reason: Cannot read properties of undefined (reading 'enabled')
at async toggleLanguage (/home/runner/work/cht-core/cht-core/tests/page-objects/default/admin/admin.wdio.page.js:18:3)
at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/translations/enabled-languages.wdio-spec.js:45:5)
```

Subsequent retries fail with:
```
2) Enabling/disabling languages should disable a language and enable another
expected [] to deeply equal [ …(3) ]      
      actual expected
      
      [ { code: 'en', name: 'English' }, { code: 'es', name: 'Español (Spanish)' }, { code: 'fr', name: 'Français (French)' } ]
      
AssertionError: expected [] to deeply equal [ …(3) ]
at Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/translations/enabled-languages.wdio-spec.js:31:29)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Example run: https://github.com/medic/cht-core/actions/runs/5451095481/jobs/9919104639#step:16:1629

**Comment by dianabarsan** [comment]
I've pushed a change that tries to stabilize the test. Feel free to re-open if not stable again.

**Comment by garethbowen** [comment]
This is still flaky: https://github.com/medic/cht-core/actions/runs/7738256328/job/21099078432

Try another attempt.
