### ISSUE TITLE
Flaky test:  Muting for an offline user

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8375]
**Describe the issue**
Test is failing in `beforeAll` with: 
```
1) for an offline user "before all" hook for for an offline user
element ("#password") still not displayed after 15000ms
Error: element ("#password") still not displayed after 15000ms
     at async setPasswordValue (/home/runner/work/cht-core/cht-core/tests/page-objects/default/login/login.wdio.page.js:123:3)
     at async Object.login (/home/runner/work/cht-core/cht-core/tests/page-objects/default/login/login.wdio.page.js:19:3)
     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/transitions/client-side-muting.wdio-spec.js:256:7)1) for an offline user "before all" hook for for an offline user
 element ("#password") still not displayed after 15000ms
 Error: element ("#password") still not displayed after 15000ms
     at async setPasswordValue (/home/runner/work/cht-core/cht-core/tests/page-objects/default/login/login.wdio.page.js:123:3)
     at async Object.login (/home/runner/work/cht-core/cht-core/tests/page-objects/default/login/login.wdio.page.js:19:3)
     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/transitions/client-side-muting.wdio-spec.js:256:7)
```

Example build: https://github.com/medic/cht-core/actions/runs/5487334521/jobs/9998939840?pr=8374#step:16:1436

**Comment by garethbowen** [comment]
Two more failures this week.

**Comment by garethbowen** [comment]
And again this week. Prioritising.

**Comment by garethbowen** [comment]
![18aed13b-95c1-4065-a8d9-dd2a287a14b9-attachment](https://github.com/medic/cht-core/assets/2064938/9538a67d-a604-41b3-9d41-37fc5a7f2772)

**Comment by garethbowen** [comment]
![image](https://github.com/medic/cht-core/assets/2064938/124f7a5e-808f-45b0-b055-6cab8fa7d9d5)

**Comment by garethbowen** [comment]
Potential fix merged. Reopen if this happens again...
