### ISSUE TITLE
Offline user E2E fail locally when webapp source is not minified

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8386]
**Describe the bug**
When running e2e tests locally, after building webapp with the [`development`](https://github.com/medic/cht-core/blob/master/webapp/angular.json#L48) configuration, e2e tests that require logging in as an offline user fail because the service worker fails to get installed. 

**To Reproduce**
1. Build webapp as dev.
2. Run `npm run wdio-local`
3. Notice that e2e tests that use offline users fail.

**Expected behavior**
The service worker should install even for a dev build. 

**Logs**
Checking the `browser.console.log` file, all tests fail with this error:
```
[error] Console Api Event: [{"type":"string","value":"Error bootstrapping"},{"type":"object","subtype":"error","className":"Error","description":"Error: Service worker labeled redundant\n    at installingWorker.onstatechange (https://localhost/main.js:170685:25)","objectId":"-666984916494185887.10.1","preview":{"type":"object","subtype":"error","description":"Error: Service worker labeled redundant\n    at installingWorker.onstatechange (https://localhost/main.js:170685:25)","overflow":false,"properties":[{"name":"stack","type":"string","value":"Error: Service worker labeled redundant\n    at ins…statechange (https://localhost/main.js:170685:25)"},{"name":"message","type":"string","value":"Service worker labeled redundant"}]}}]
```

If disabling `headless`, and checking the network tab, I can see the request for `main.js` fails. 

**Environment**
- Instance: local e2e test
- Browser: Chrome webdriver
- App: webapp
- Version: 4.3.x

**Additional context**
~My current guess is that the file size exceeds the value that we allow for caching in the service worker configuration.~
This is not the case. 
It's possible this only happens on branches that add new code to webapp.

**Comment by dianabarsan** [comment]
This seems to not happen anymore.
