### ISSUE TITLE
Compile the app job fails on re-run because it can't overwrite the old build doc

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8428]
**Describe the issue**
Re-running the whole build after it had passed fails with:
```
Running "exec:push-ddoc-to-staging" (exec) task
>> node:internal/process/promises:279
>>             triggerUncaughtException(err, true /* fromPromise */);
>>             ^
>> {
>>   error: 'conflict',
>>   reason: 'Document update conflict.',
>>   status: 409,
>>   name: 'conflict',
>>   message: 'Document update conflict.',
>>   stack: 'Error\n' +
>>     '    at Object.generateErrorFromResponse (/home/runner/work/cht-core/cht-core/node_modules/pouchdb-errors/lib/index.js:104:18)\n' +
>>     '    at /home/runner/work/cht-core/cht-core/node_modules/pouchdb-adapter-http/lib/index.js:254:33\n' +
>>     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
>>   docId: 'medic:medic:test-5731629408'
>> }
>> Exited with code: 1.
>> Error executing child process: Error: Process exited with code 1.
Warning: Task "exec:push-ddoc-to-staging" failed. Use --force to continue.
```

https://github.com/medic/cht-core/actions/runs/5731629408/job/15540432957#step:12:1667

**Describe the improvement you'd like**
Handle build doc conflicts.

**Comment by dianabarsan** [comment]
Fixed by https://github.com/medic/cht-core/commit/afcab35552dda0509079bc80eb6664723f042952
