### ISSUE TITLE
Flaky e2e test: "after each" hook for Create user for contacts

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8430]
**Describe the issue**
The after each for Create user for contacts can timeout: 
```
[chrome 115.0.5790.102 linux #0-4] 1) for an offline user "after each" hook for Create user for contacts
[chrome 115.0.5790.102 linux #0-4] Timeout of 120000ms exceeded. The execution in the test "Create user for contacts "after each" hook for "creates new user for the first version of a contact to sync and conflicting replacements ignored"" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/runner/work/cht-core/cht-core/tests/e2e/default/transitions/create-user-for-contacts.replace-user.wdio-spec.js)
[chrome 115.0.5790.102 linux #0-4] Error: Timeout of 120000ms exceeded. The execution in the test "Create user for contacts "after each" hook for "creates new user for the first version of a contact to sync and conflicting replacements ignored"" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/runner/work/cht-core/cht-core/tests/e2e/default/transitions/create-user-for-contacts.replace-user.wdio-spec.js)
[chrome 115.0.5790.102 linux #0-4]     at createTimeoutError (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/errors.js:498:15)
[chrome 115.0.5790.102 linux #0-4]     at Hook.Runnable._timeoutError (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runnable.js:431:10)
[chrome 115.0.5790.102 linux #0-4]     at Timeout.<anonymous> (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runnable.js:246:24)
[chrome 115.0.5790.102 linux #0-4]     at listOnTimeout (node:internal/timers:559:17)
[chrome 115.0.5790.102 linux #0-4]     at processTimers (node:internal/timers:502:7)```

https://github.com/medic/cht-core/actions/runs/5743582968/job/15568460377?pr=8164#step:16:459

**Comment by andrablaj** [comment]
@lorerod I see this issue is assigned to you. Do you plan to work on it or should we remove your assignment for now?

**Comment by lorerod** [comment]
@andrablaj  I was planning to tackle the flaky tests before the end of the year. However, with time off for the holidays and changes in prioritization, I won’t be able to work on it. I’ll go ahead and remove my assignment for now. Thank you for checking in!
