### ISSUE TITLE
API crashes when CouchDB is overloaded

### ISSUE THREAD

**Issue by m5r** [medic/cht-core#8490]
**Describe the bug**
When CouchDB is overloaded it gets unresponsive and ends up responding with 5xx errors that make the API crash.  
It was seen on a training instance backed by a single couch node with 30 cores and 32 GB of RAM dealing with a spike of thousands of users. More info in https://github.com/medic/cht-core/issues/8324

**Expected behavior**
The API should gracefully handle this error and keep running until CouchDB is operational again.

**Logs**
Full logs were shared [on Slack](https://medic.slack.com/archives/C03H77DKY0M/p1692818007329109?thread_ts=1692792957.766869&cid=C03H77DKY0M) 

Part of the logs with the thrown error:
```text
2023-08-22 12:04:18 ERROR: UNCAUGHT EXCEPTION!
2023-08-22 12:04:18 ERROR:   Error: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at ServerResponse.interceptResponse (/api/src/controllers/bulk-docs.js:29:19)
    at apply (/api/node_modules/lodash/lodash.js:478:17)
    at ServerResponse.wrapper [as interceptResponse] (/api/node_modules/lodash/lodash.js:5337:16)
    at IncomingMessage.<anonymous> (/api/src/routing.js:865:34)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  [stack]: 'SyntaxError: Unexpected token < in JSON at position 0\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at ServerResponse.interceptResponse (/api/src/controllers/bulk-docs.js:29:19)\n' +
    '    at apply (/api/node_modules/lodash/lodash.js:478:17)\n' +
    '    at ServerResponse.wrapper [as interceptResponse] (/api/node_modules/lodash/lodash.js:5337:16)\n' +
    '    at IncomingMessage.<anonymous> (/api/src/routing.js:865:34)\n' +
    '    at IncomingMessage.emit (node:events:525:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1358:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
  [message]: 'Unexpected token < in JSON at position 0'
}
Info: Starting CHT API
2023-08-22 12:04:19 INFO: Running server checks…
```

**Environment**
- Version: 4.2.2

**Comment by m5r** [comment]
@garethbowen yes! I just tried it out locally and it keeps the API up while logging the HAProxy error responses

I'm closing my PR and we can wait for #8179 to be merged to consider this issue fixed

cc @mrjones-plip @jkuester

**Comment by garethbowen** [comment]
Great! Thanks for testing.

**Comment by dianabarsan** [comment]
Closing this as https://github.com/medic/cht-core/issues/8179 was merged.
