### ISSUE TITLE
xpath extensions tests fail locally in my timzone

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8556]
**Describe the issue**

Run: `npm run unit-webapp` in NZ timezone (+12).

```
  1) medic-xpath-extensions
       #difference-in-months
         should report difference between [object Object] and [object Object] as 0:

      AssertionError: expected 1 to equal +0
      + expected - actual

      -1
      +0
      
      at Context.<anonymous> (webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js:59:16)
      at processImmediate (node:internal/timers:466:21)

  2) medic-xpath-extensions
       #to-bikram-sambat()
         should format the str ["2015-9-2"] according to the Bikram Sambat calendar:

      AssertionError: expected '१५ भदौ २०७२' to equal '१६ भदौ २०७२'
      + expected - actual

      -१५ भदौ २०७२
      +१६ भदौ २०७२
      
      at Context.<anonymous> (webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js:108:16)
      at processImmediate (node:internal/timers:466:21)

  3) medic-xpath-extensions
       #to-bikram-sambat()
         should format the str ["1999-12-12"] according to the Bikram Sambat calendar:

      AssertionError: expected '२५ मंसिर २०५६' to equal '२६ मंसिर २०५६'
      + expected - actual

      -२५ मंसिर २०५६
      +२६ मंसिर २०५६
      
      at Context.<anonymous> (webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js:108:16)
      at processImmediate (node:internal/timers:466:21)

  4) medic-xpath-extensions
       #to-bikram-sambat()
         should format the date ["2015-09-30T11:00:00.000Z"] according to the Bikram Sambat calendar:

      AssertionError: expected '१३ असोज २०७२' to equal '१४ असोज २०७२'
      + expected - actual

      -१३ असोज २०७२
      +१४ असोज २०७२
      
      at Context.<anonymous> (webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js:108:16)
      at processImmediate (node:internal/timers:466:21)

  5) medic-xpath-extensions
       #to-bikram-sambat()
         should format the num [11111] according to the Bikram Sambat calendar:

      AssertionError: expected '२० जेठ २०५७' to equal '२१ जेठ २०५७'
      + expected - actual

      -२० जेठ २०५७
      +२१ जेठ २०५७
      
      at Context.<anonymous> (webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js:108:16)
      at processImmediate (node:internal/timers:466:21)

  6) medic-xpath-extensions
       #to-bikram-sambat()
         should format the arr [[{"textContent":"2014-09-22"}]] according to the Bikram Sambat calendar:

      AssertionError: expected '५ असोज २०७१' to equal '६ असोज २०७१'
      + expected - actual

      -५ असोज २०७१
      +६ असोज २०७१
      
      at Context.<anonymous> (webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js:108:16)
      at processImmediate (node:internal/timers:466:21)

```

**Describe the improvement you'd like**

**Describe alternatives you've considered**

**Comment by garethbowen** [comment]
Merged.
