### ISSUE TITLE
The upgrade test fails when releasing a final

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8569]
**Describe the issue**

When a final release is published the upgrade test fails because it installs the latest version (the one that was just released) then tries to upgrade to it.

Example build: https://github.com/medic/cht-core/actions/runs/6255863600/job/16986706159

```
[0-0] RUNNING in chrome - file:///tests/e2e/upgrade/upgrade.wdio-spec.js
[0-0] Error in "Performing an upgrade.should upgrade to current branch"
Error: Can't call parentElement on element with selector "span=4.4.0" because element wasn't found
    at async Object.getInstallButton (/home/runner/work/cht-core/cht-core/tests/page-objects/upgrade/upgrade.wdio.page.js:14:25)
    at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/upgrade/upgrade.wdio-spec.js:104:27)
```

**Describe the improvement you'd like**

Skip the test. Everything else works but it's confusing and concerning to have a red build after releasing.

**Describe alternatives you've considered**
We could fix it so it installs the "latest - 1" but the release has already happened so there's no point failing anyway.

**Comment by dianabarsan** [comment]
Another issue appears when pushing to older branches, to release patches. 
I think the most correct would be to get "current - 1", but we're not always disciplined to bump current version when we release (this has happened a lot recently).
