### ISSUE TITLE
Catch missing values file in k3d script

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8604]
**Describe the issue**
when you're using the soon to be [merged k3d script](https://github.com/medic/cht-core/pull/8263), and your `values.yml` is missing, you get an ugly error: 

```
 ./cht-deploy -f values.yaml                               
 Traceback (most recent call last):
   File "/home/mrjones/.local/bin/invoke", line 8, in <module>
     sys.exit(program.run())
   File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/program.py", line 384, in run
     self.execute()
   File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/program.py", line 569, in execute 
     executor.execute(*self.tasks)
   File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
     result = call.task(*args, **call.kwargs)
   File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
     result = self.body(*args, **kwargs)
   File "/home/mrjones/Documents/MedicMobile/cht-core/scripts/deploy/tasks.py", line 160, in install
     prepare(c, f)
   File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
     result = self.body(*args, **kwargs)
   File "/home/mrjones/Documents/MedicMobile/cht-core/scripts/deploy/tasks.py", line 11, in prepare
     with open(f, 'r') as stream:
 FileNotFoundError: [Errno 2] No such file or directory: 'values.yaml
```

**Describe the improvement you'd like**
It would be great if the `cht-deploy` script detected a missing file and just told you instead outputting a bit scary stack trace. 

**Describe alternatives you've considered**

**Comment by henokgetachew** [comment]
Complete. PR in review
