### ISSUE TITLE
Expression changed after it was checked Error in Reports component

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8664]
**Describe the bug**
When running dev build and running default mobile e2e tests, tests that deal with deleting reports fail because of an `ExpressionChangedAfterItHasBeenCheckedError`. 

**To Reproduce**
1. `npm run build-dev`
2. `npm run default-wdio-mobile-local`
3. report delete tests fail because of generated feedback docs: 
```
{
      "_id": "feedback-2023-10-25T11:37:26.714Z-8b1cf8a5-b3cf-4ac8-bca3-cb8eecbcb55d",
      "_rev": "1-fb9e69fdb539c346e8c38a4a09a23edd",
      "info": {
        "message": "NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '1'. Expression location: ReportsComponent component. Find more at https://angular.io/errors/NG0100",
        "stack": "Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '1'. Expression location: ReportsComponent component. Find more at https://angular.io/errors/NG0100\n    at throwErrorIfNoChangesMode (https://localhost/main.js:241807:9)\n    at bindingUpdated (https://localhost/main.js:244920:9)\n    at pureFunction1Internal (https://localhost/main.js:253360:10)\n    at Module.ɵɵpureFunction1 (https://localhost/main.js:253169:10)\n    at ReportsComponent_Template (https://localhost/main.js:24114:213)\n    at executeTemplate (https://localhost/main.js:242190:7)\n    at refreshView (https://localhost/main.js:243617:7)\n    at detectChangesInView (https://localhost/main.js:243779:5)\n    at detectChangesInComponent (https://localhost/main.js:243757:3)\n    at detectChangesInChildComponents (https://localhost/main.js:243791:5)"
      },
      "log": [
        {
          "arguments": "[\"Initiating changes watch (meta=true)\"]",
          "level": "info",
          "time": "2023-10-25T11:37:26.709Z"
        },
        {
          "arguments": "[\"Initiating changes watch (meta=false)\"]",
          "level": "info",
          "time": "2023-10-25T11:37:26.708Z"
        },
        {
          "arguments": "[\"Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '1'. Expression location: ReportsComponent component. Find more at https://angular.io/errors/NG0100\\n    at throwErrorIfNoChangesMode (https://localhost/main.js:241807:9)\\n    at bindingUpdated (https://localhost/main.js:244920:9)\\n    at pureFunction1Internal (https://localhost/main.js:253360:10)\\n    at Module.ɵɵpureFunction1 (https://localhost/main.js:253169:10)\\n    at ReportsComponent_Template (https://localhost/main.js:24114:213)\\n    at executeTemplate (https://localhost/main.js:242190:7)\\n    at refreshView (https://localhost/main.js:243617:7)\\n    at detectChangesInView (https://localhost/main.js:243779:5)\\n    at detectChangesInComponent (https://localhost/main.js:243757:3)\\n    at detectChangesInChildComponents (https://localhost/main.js:243791:5)\"]",
          "level": "error",
          "time": "2023-10-25T11:37:26.692Z"
        },
        {
          "arguments": "[\"%c next state\",\"color: #4CAF50; font-weight: bold\",{\"global\":{\"actionBar\":{\"left\":{},\"right\":{}},\"navigation\":{\"cancelCallback\":null,\"preventNavigation\":null,\"cancelTranslationKey\":null,\"recordTelemetry\":null},\"currentTab\":\"reports\",\"snapshotData\":{\"permissions\":[\"can_view_reports\"],\"tab\":\"reports\",\"name\":\"reports.detail\"},\"enketoStatus\":{\"form\":false,\"edited\":false,\"saving\":false,\"error\":null},\"facilities\":[],\"filters\":{\"search\":\"\"},\"sidebarFilter\":{},\"forms\":null,\"lastChangedDoc\":false,\"loadingContent\":false,\"loadingSubActionBar\":false,\"replicationStatus\":{\"disabled\":false,\"lastSuccessTo\":1698233844584},\"selectMode\":false,\"privacyPolicyAccepted\":true,\"showActionBar\":false,\"showContent\":false,\"showPrivacyPolicy\":false,\"title\":\"\",\"unreadCount\":{},\"version\":null,\"snackbarContent\":null,\"translationsLoaded\":true,\"userFacilityId\":null,\"trainingCardFormId\":null},\"services\":{\"lastChangedDoc\":false},\"analytics\":{\"selected\":null,\"analyticsModules\":[{\"id\":\"targets\",\"label\":\"analytics.targets\"",
          "level": "log",
          "time": "2023-10-25T11:37:26.681Z"
        },
```

**Environment**
- Instance: local test
- Browser: chrome
- App: webapp
- Version: 4.4 

**Additional context**
The issue also affects production builds, but the error won't be logged in this case and the effects will be visible - because there is no double rendering cycle.

**Comment by latin-panda** [comment]
Similar happens in the message list - mobile view 

```
"Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '1'. Expression location: MessagesComponent component. Find more at https://angular.io/errors/NG0100\n    at throwErrorIfNoChangesMode (https://localhost/main.js:271866:9)\n    at bindingUpdated (https://localhost/main.js:280094:9)\n    at pureFunction1Internal (https://localhost/main.js:289588:10)\n    at Module.ɵɵpureFunction1 (https://localhost/main.js:289397:10)\n    at MessagesComponent_Template (https://localhost/main.js:20288:213)\n    at executeTemplate (https://localhost/main.js:273164:5)\n    at refreshView (https://localhost/main.js:274629:7)\n    at detectChangesInView$1 (https://localhost/main.js:274847:5)\n    at detectChangesInViewIfAttached (https://localhost/main.js:274810:3)\n    at detectChangesInComponent (https://localhost/main.js:274799:3)"
```

**Steps**

- login in mobile view
- CHT loads the message list, wait until it finish loading
- Reload page
- See error in the browser's console
