### ISSUE TITLE
Infinite scrolling failing with 429

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8739]
**Describe the bug**
A previously stable e2e test is now failing with a 429. 
Example run: https://github.com/medic/cht-core/actions/runs/7045684491/job/19178970169#step:17:532

We should check if the test failing is a flake or a problem in the test, or if our rate limiter is failing for a valid login.

**Comment by garethbowen** [comment]
Logs included for searchability...

```
------------------------------------------------------------------
[chrome 119.0.6045.159 linux #0-7] Running: chrome (v119.0.6045.159) on linux
[chrome 119.0.6045.159 linux #0-7] Session ID: 7c51f39c98c147f5086452b388bc705b
[chrome 119.0.6045.159 linux #0-7]
[chrome 119.0.6045.159 linux #0-7] » /tests/e2e/default/contacts/infinite-scrolling.wdio-spec.js
[chrome 119.0.6045.159 linux #0-7] Infinite scrolling
[chrome 119.0.6045.159 linux #0-7]    ✖ "before all" hook for Infinite scrolling
[chrome 119.0.6045.159 linux #0-7]
[chrome 119.0.6045.159 linux #0-7] 1 failing (108ms)
[chrome 119.0.6045.159 linux #0-7]
[chrome 119.0.6045.159 linux #0-7] 1) Infinite scrolling "before all" hook for Infinite scrolling
[chrome 119.0.6045.159 linux #0-7] 429 - {"code":429,"error":"Too Many Requests"}
[chrome 119.0.6045.159 linux #0-7] StatusCodeError: 429 - {"code":429,"error":"Too Many Requests"}
[chrome 119.0.6045.159 linux #0-7]     at new StatusCodeError (/home/runner/work/cht-core/cht-core/node_modules/request-promise-core/lib/errors.js:32:15)
[chrome 119.0.6045.159 linux #0-7]     at /home/runner/work/cht-core/cht-core/node_modules/request-promise-core/lib/plumbing.js:97:41
[chrome 119.0.6045.159 linux #0-7]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
------------------------------------------------------------------
[chrome 119.0.6045.159 linux #0-8] Running: chrome (v119.0.6045.159) on linux
[chrome 119.0.6045.159 linux #0-8] Session ID: 35d309ed019f3be5ff99bde5705007c4
[chrome 119.0.6045.159 linux #0-8]
[chrome 119.0.6045.159 linux #0-8] » /tests/e2e/default/contacts/muting-contact-using-form.wdio-spec.js
[chrome 119.0.6045.159 linux #0-8] Mute/Unmute contacts using a specific form.
[chrome 119.0.6045.159 linux #0-8]    ✖ "before all" hook for Mute/Unmute contacts using a specific form.
[chrome 119.0.6045.159 linux #0-8]
[chrome 119.0.6045.159 linux #0-8] 1 failing (104ms)
[chrome 119.0.6045.159 linux #0-8]
[chrome 119.0.6045.159 linux #0-8] 1) Mute/Unmute contacts using a specific form. "before all" hook for Mute/Unmute contacts using a specific form.
[chrome 119.0.6045.159 linux #0-8] 429 - {"code":429,"error":"Too Many Requests"}
[chrome 119.0.6045.159 linux #0-8] StatusCodeError: 429 - {"code":429,"error":"Too Many Requests"}
[chrome 119.0.6045.159 linux #0-8]     at new StatusCodeError (/home/runner/work/cht-core/cht-core/node_modules/request-promise-core/lib/errors.js:32:15)
[chrome 119.0.6045.159 linux #0-8]     at /home/runner/work/cht-core/cht-core/node_modules/request-promise-core/lib/plumbing.js:97:41
[chrome 119.0.6045.159 linux #0-8]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
------------------------------------------------------------------
```

**Comment by dianabarsan** [comment]
Looking at the logs, there are no failed logins or anything along those lines.
