### ISSUE TITLE
Flaky e2e test

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8802]
**Describe the issue**

**Describe the improvement you'd like**

**Describe alternatives you've considered**

**Comment by garethbowen** [comment]
Another possibly related failure: https://github.com/medic/cht-core/actions/runs/8780156058/job/24090006364

```
[chrome-headless-shell 123.0.6312.122 linux #0-4] Running: chrome-headless-shell (v123.0.6312.122) on linux
[chrome-headless-shell 123.0.6312.122 linux #0-4] Session ID: ae1d22f9f7c60c060fd495d961830e6f
[chrome-headless-shell 123.0.6312.122 linux #0-4]
[chrome-headless-shell 123.0.6312.122 linux #0-4] » /tests/e2e/default/db/ongoing-replication.wdio-spec.js
[chrome-headless-shell 123.0.6312.122 linux #0-4] ongoing replication
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should download new documents
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should handle updates to existing documents
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should download new forms and update forms
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should download new languages and language updates
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should handle deletes
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✖ should download settings updates (5 retries)
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should handle conflicts
[chrome-headless-shell 123.0.6312.122 linux #0-4]
[chrome-headless-shell 123.0.6312.122 linux #0-4] 6 passing (4m 9s)
[chrome-headless-shell 123.0.6312.122 linux #0-4] 1 failing
[chrome-headless-shell 123.0.6312.122 linux #0-4]
[chrome-headless-shell 123.0.6312.122 linux #0-4] 1) ongoing replication should download settings updates
[chrome-headless-shell 123.0.6312.122 linux #0-4] A previous test did not call revertSettings
[chrome-headless-shell 123.0.6312.122 linux #0-4] Error: A previous test did not call revertSettings
[chrome-headless-shell 123.0.6312.122 linux #0-4]     at updateCustomSettings (/home/runner/work/cht-core/cht-core/tests/utils/index.js:438:11)
[chrome-headless-shell 123.0.6312.122 linux #0-4]     at Object.updateSettings (/home/runner/work/cht-core/cht-core/tests/utils/index.js:483:9)
[chrome-headless-shell 123.0.6312.122 linux #0-4]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/db/ongoing-replication.wdio-spec.js:171:5)
```

**Comment by dianabarsan** [comment]
I have another possibly related failure:https://github.com/medic/cht-core/actions/runs/8806181630/job/24172143420
This time the "deletes" test fails, with: 
```
[chrome-headless-shell 123.0.6312.122 linux #0-4] » /tests/e2e/default/db/ongoing-replication.wdio-spec.js
[chrome-headless-shell 123.0.6312.122 linux #0-4] ongoing replication
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should download new documents
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should handle updates to existing documents
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should download new forms and update forms
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should download new languages and language updates
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✖ should handle deletes (5 retries)
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should download settings updates
[chrome-headless-shell 123.0.6312.122 linux #0-4]    ✓ should handle conflicts
[chrome-headless-shell 123.0.6312.122 linux #0-4]
[chrome-headless-shell 123.0.6312.122 linux #0-4] 6 passing (6m 53.8s)
[chrome-headless-shell 123.0.6312.122 linux #0-4] 1 failing
[chrome-headless-shell 123.0.6312.122 linux #0-4]
[chrome-headless-shell 123.0.6312.122 linux #0-4] 1) ongoing replication should handle deletes
[chrome-headless-shell 123.0.6312.122 linux #0-4] Timed out looking for details in logs.
[chrome-headless-shell 123.0.6312.122 linux #0-4] Error: Timed out looking for details in logs.
[chrome-headless-shell 123.0.6312.122 linux #0-4]     at Timeout._onTimeout (/home/runner/work/cht-core/cht-core/tests/utils/index.js:1121:14)
[chrome-headless-shell 123.0.6312.122 linux #0-4]     at listOnTimeout (node:internal/timers:573:17)
[chrome-headless-shell 123.0.6312.122 linux #0-4]     at processTimers (node:internal/timers:514:7)
```

Every time one of these two tests fails, I can see that some after hook from the initial replication test - which runs right before this one - reports: 
```
[0-3] RUNNING in chrome - file:///tests/e2e/default/db/initial-replication.wdio-spec.js
[0-3] Stopping cht-e2e_sentinel_1 ... 
[0-3] 
[0-3] Stopping cht-e2e_sentinel_1 ... done
[0-3] 
[0-3] Starting sentinel ... 
[0-3] 
[0-3] Starting sentinel ... done
[0-3] 
[0-3] Found logs 2024-04-23T20:27:41.195 REQ: 0638d000-b4f5-4c5b-a6e9-1096bd043793 172.18.0.1 - GET /medic-test/_all_docs?include_docs=true HTTP/1.0
[0-3] 2024-04-23T20:27:41.656 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:42.652 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:43.[245](https://github.com/medic/cht-core/actions/runs/8806181630/job/24172143420#step:17:246) RES: 0638d000-b4f5-4c5b-a6e9-1096bd043793 172.18.0.1 - GET /medic-test/_all_docs?include_docs=true HTTP/1.0 200 - 27.994 ms
[0-3] 2024-04-23T20:27:43.613 REQ: ada84e43-d95c-4ae3-8b5a-74d839f38c87 172.18.0.1 admin POST /medic-test-sentinel/_all_docs? HTTP/1.0
[0-3] 2024-04-23T20:27:43.615 REQ: eaa1e66d-3f03-4d5f-8a84-321655404a36 172.18.0.1 - POST /medic-test/_bulk_docs HTTP/1.0
[0-3] 2024-04-23T20:27:43.652 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:44.652 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:45.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:46.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:47.652 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:48.652 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:49.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:50.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:51.652 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:52.652 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:53.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:54.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:55.652 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:56.312 RES: ada84e43-d95c-4ae3-8b5a-74d839f38c87 172.18.0.1 admin POST /medic-test-sentinel/_all_docs? HTTP/1.0 200 - 32.368 ms
[0-3] 2024-04-23T20:27:56.411 REQ: 44437c9e-c9c9-442a-8007-bf6018f7349b 172.18.0.1 admin POST /medic-test-sentinel/_bulk_docs HTTP/1.0
[0-3] 2024-04-23T20:27:56.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:57.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:58.[264](https://github.com/medic/cht-core/actions/runs/8806181630/job/24172143420#step:17:265) RES: 44437c9e-c9c9-442a-8007-bf6018f7349b 172.18.0.1 admin POST /medic-test-sentinel/_bulk_docs HTTP/1.0 201 - 1832.492 ms
[0-3] 2024-04-23T20:27:58.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:27:59.653 DEBUG: Checking for a configured outgoing message service 
[0-3] 2024-04-23T20:28:00.653 DEBUG: Checking for a configured outgoing message service 
[0-3]  did not match expected regex: /Settings updated/
[0-3] PASSED in chrome - file:///tests/e2e/default/db/initial-replication.wdio-spec.js
```

**Comment by dianabarsan** [comment]
Figured out was was causing the above: https://github.com/medic/cht-core/issues/8802#issuecomment-2073810480

The initial replication test adds a buuunch of docs. when we revert the database we: 
- start settings update watcher - which times out with an error after 20s
- revert settings - only if necessary, saving whether it was necessary or not
- delete docs from the db
- revert translations
- delete local docs
- address settings update watcher, either waiting for the modal, or waiting for the settings to be updated or cancelling the watcher if no settings updates are expected 

If any of the followup tasks after reverting settings takes longer than 20s, then the watcher will time out and throw an error even though we should not be watching for updates in the first place. 

This is exactly what happens in the above test. There is this line that logs the start of a _bulk_docs request: 
```
[0-3] 2024-04-23T20:27:43.615 REQ: eaa1e66d-3f03-4d5f-8a84-321655404a36 172.18.0.1 - POST /medic-test/_bulk_docs HTTP/1.0
```

The RES entry for the same request doesn't exist in this excerpt, because it happens later, but inspecting the logs will show it took 24 seconds to delete these docs: 
```
2024-04-23T20:28:07.664 RES: eaa1e66d-3f03-4d5f-8a84-321655404a36 172.18.0.1 - POST /medic-test/_bulk_docs HTTP/1.0 201 406577 23931.450 ms
```

**Comment by dianabarsan** [comment]
Pushed a commit that changed how we handle db cleanup and how we advance the sentinel seq. 
Please reopen if these tests start failing again.
