### ISSUE TITLE
CouchDb data corruption after stopping and restarting the container

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8923]
**Describe the bug**
Creating this issue mostly to document that this has and can happen. 
I had a local docker-compose instance with a 3 node CouchDb. I frequently closed the containers and restarted them to push updates. At some point, my API failed to start with this error: 

```
2024-03-10T02:08:00.429 ERROR: {
  error: '{bad_return_value,{read_beyond_eof,"./data/shards/95555553-aaaaaaa7/medic.1699080493.couch"}}',
  reason: '{gen_server,call,[<0.22283.23>,{pread_iolist,1265193},infinity]}',
  ref: 4070966599,
  status: 500,
  name: '{bad_return_value,{read_beyond_eof,"./data/shards/95555553-aaaaaaa7/medic.1699080493.couch"}}',
  message: '{gen_server,call,[<0.22283.23>,{pread_iolist,1265193},infinity]}',
  stack: 'Error\n' +
    '    at Object.generateErrorFromResponse (/service/api/node_modules/pouchdb-errors/lib/index.js:104:18)\n' +
    '    at /service/api/node_modules/pouchdb-adapter-http/lib/index.js:254:33\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
} 
```

CouchDb Error: 
```
 [error] 2024-03-10T02:14:32.118364Z couchdb@couchdb-2.local <0.1032.0> -------- CRASH REPORT Process  (<0.1032.0>) with 1 neighbors exited with reason: bad return value {read_beyond_eof,"./data/shards/95555553-aaaaaaa7/medic.1699080493.couch"} at gen_server:handle_common_reply/8(line:815) <= proc_lib:init_p_do_apply/3(line:226); initial_call: {couch_file,init,['Argument__1']}, ancestors: [<0.1031.0>,<0.1030.0>], message_queue_len: 0, links: [<0.1031.0>], dictionary: [{couch_file_fd,{{file_descriptor,prim_file,#{handle => #Ref<0.171315266.994181162.124148>,...}},...}},...], trap_exit: false, status: running, heap_size: 610, stack_size: 29, reductions: 1603

```

I know we've had other instances where data corruption has happened. 

**Environment**
- Instance: local
- Client platform: Linux, Docker
- App: CouchDb
- Version: 4.6.0

**Additional context**
I have made no attempts to recover the data (it was just test data). 2

**Comment by dianabarsan** [comment]
I've realized I had two CouchDb installations competing over network, which could have been the cause for this issue.
