### ISSUE TITLE
`xml2sms` functionality broken

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#8930]
**Describe the bug**
It seems like the [`xml2sms` functionality](https://docs.communityhealthtoolkit.org/apps/guides/forms/app-form-sms/) for sending an SMS when a report is created has been broken for awhile.

**To Reproduce**
Follow the documented steps to configure sending report data via SMS:

- In your `app_settings.json` set a value for the `gateway_number`.
- In  your form properties.json, set `"xml2sms": true`
- Assemble a cht-android apk with the `SEND_SMS` permission
- Use the Android app to submit a report
- See that you are not prompted for SMS permissions
- See `Form2Sms failed` error in the console logs

**Expected behavior**
When everything is properly configured, the user should be prompted to allow SMS permission (so the report can be sent).  But, on newer cht-core versions, this never happens.  Basically, the webapp fails to create an SMS message to send and so it never tries to trigger the permission.  

**Logs**

<details>
<summary>APK Logs</summary>
```
2024-03-13 11:21:46.511 19293-19293 MedicMobile             org.medicmobile.webapp.mobile        D  org.medicmobile.webapp.mobile.EmbeddedBrowserActivity$3 :: onConsoleMessage() :: https://192-168-1-33.local-ip.medicmobile.org:10443/main.js:1 | Form2Sms failed:  [object Object]
2024-03-13 11:21:46.512 19293-19293 MedicMobile             org.medicmobile.webapp.mobile        D  org.medicmobile.webapp.mobile.EmbeddedBrowserActivity$3 :: onConsoleMessage() :: https://192-168-1-33.local-ip.medicmobile.org:10443/main.js:1 | Unhandled Promise rejection: missing ; Zone: <root> ; Task: Promise.then ; Value: [object Object] Error
                                                                                                        at new fe (https://192-168-1-33.local-ip.medicmobile.org:10443/main.js:11:494301)
                                                                                                        at Ti (https://192-168-1-33.local-ip.medicmobile.org:10443/main.js:11:494382)
                                                                                                        at wi.objectStore.get.onsuccess [as __zone_symbol__ON_PROPERTYsuccess] (https://192-168-1-33.local-ip.medicmobile.org:10443/main.js:11:545424)
                                                                                                        at IDBRequest.ke (https://192-168-1-33.local-ip.medicmobile.org:10443/polyfills.js:1:15728)
                                                                                                        at G.invokeTask (https://192-168-1-33.local-ip.medicmobile.org:10443/polyfills.js:1:11385)
                                                                                                        at Q.runTask (https://192-168-1-33.local-ip.medicmobile.org:10443/polyfills.js:1:6758)
                                                                                                        at F.invokeTask [as invoke] (https://192-168-1-33.local-ip.medicmobile.org:10443/polyfills.js:1:12437)
                                                                                                        at q (https://192-168-1-33.local-ip.medicmobile.org:10443/polyfills.js:1:25168)
                                                                                                        at ee (https://192-168-1-33.local-ip.medicmobile.org:10443/polyfills.js:1:25477)
                                                                                                        at IDBRequest.ye (https://192-168-1-33.local-ip.medicmobile.org:10443/polyfills.js:1:25760)
```
</details>

The problem is in the [form2sms.getFormModel function](https://github.com/medic/cht-core/blob/e8d88accb607f5ae5060f9bb4a988d91dc615812/webapp/src/ts/services/form2sms.service.ts#L45).  It tries to get the form model attachment, but it is not passing the correct parameters.  It should look like the [forms service code](https://github.com/medic/cht-core/blob/e8d88accb607f5ae5060f9bb4a988d91dc615812/webapp/src/ts/services/form.service.ts#L97) with will pass the form doc id (e.g. `form:pregnancy`) and `model.xml`.  Instead, the form2sms service code is passing the form name (`pregnancy`) and `model`.  As far as I can tell, there is no way this code will ever succeed.  

I think this issue was introduced  in https://github.com/medic/cht-core/pull/7596 and shipped on `4.0.0`.

**Comment by jkuester** [comment]
Seeing as how no one has reported this issue yet, I am assuming no one (on `4.x`) is trying to use `xml2sms`.  Maybe we could just call this one of the "Breaking Changes" from `4.0.0`?  :grimacing:

**Comment by dianabarsan** [comment]
This has unfortunately never worked. 
We added `xml2sms` and then realized that Android only allows one app to send SMS, and that app becomes the default SMS app system wide. We realized that the CHT doesn't have the capability to take over all SMS functionality, so we just abandoned this feature. However, since `xml2sms` was already developed, we considered it could be useful someday to have a way to stringifying a report into a format that the CHT understands.

**Comment by dianabarsan** [comment]
Just a relevant discussion on a forum because I was second guessing my memory of the SMS permission: https://community.appinventor.mit.edu/t/help-with-android-permission-send-sms/47342/2

**Comment by jkuester** [comment]
:+1:   This makes a lot more sense as to why the functionality works as expected when testing locally:

> It may be important here to distinguish between the Android operating system and the Google Play Store. Your app should continue to work fine on Android--this is just a policy "feature" of the Play Store that Google will not publish apps that use the SEND_SMS permission unless they are intended to be the default SMS app for the phone (which your app is not). There are some exception and you must fill out a form to be considered. We tried to do this for the MIT AI2 Companion app and were rejected.
