### ISSUE TITLE
difference-in-days xpath date functions fail in CEST timezone

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#9015]
Unit tests should pass regardless of timezone. Running `npm run unit-webapp` on my dev machine in Germany (CEST) I get...

```
  2 failing

  1) medic-xpath-extensions
       #difference-in-days
         should handle cases where end date is before start date and return negative number:

      AssertionError: expected -211 to equal -212
      + expected - actual

      --211
      +-212
      
      at Context.<anonymous> (webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js:179:14)
      at processImmediate (node:internal/timers:466:21)

  2) medic-xpath-extensions
       #difference-in-days
         should return the difference when valid inputs are provided:

      AssertionError: expected 211 to deeply equal 212
      + expected - actual

      -211
      +212
      
      at Context.<anonymous> (webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js:189:14)
      at processImmediate (node:internal/timers:466:21)

```

**Comment by garethbowen** [comment]
@jkuester Would you be able to look at this failure?

**Comment by jkuester** [comment]
:sweat: Looks like they fail in any TZ that is not UTC (why do we even have those timezones???).
