### ISSUE TITLE
CHT Deploy script has error: No such file or directory

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#9076]
**Describe the bug**

**To Reproduce**
1. check out `cht-core` repo
2. `cd ./cht-core/scripts/deploy`
3. [create](https://docs.communityhealthtoolkit.org/contribute/code/core/deploy-on-eks/#starting-and-stopping-aka-deleting) a valid values YAML file called `values.yml`
4. run `./cht-deploy -f values.yml`

**Expected behavior**
CHT Core instance is deployed in EKS (or maybe you get an an error to authenticate against AWS)

Instead I get an error about a missing file.

**Logs**
```
➜  deploy git:(master) ./cht-deploy -f /home/mrjones/Documents/MedicMobile/mrjones-eks.yml
Namespace mrjones-dev does not exist. Creating the namespace.
Traceback (most recent call last):
  File "/home/mrjones/.local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/program.py", line 569, in execute
    executor.execute(*self.tasks)
  File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/mrjones/Documents/MedicMobile/cht-core/scripts/deploy/tasks.py", line 211, in install
    check_namespace_exists(c, namespace)
  File "/home/mrjones/.local/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/mrjones/Documents/MedicMobile/cht-core/scripts/deploy/tasks.py", line 65, in check_namespace_exists
    with open(os.path.join(script_dir, "helm", "namespace.yaml"), 'w') as manifest_file: # NOSONAR
FileNotFoundError: [Errno 2] No such file or directory: '/home/mrjones/Documents/MedicMobile/cht-core/scripts/deploy/helm/namespace.yaml'
```

**Environment**
- Instance: NA
- Browser: NA
- Client platform:  Ubuntu 20.04
- App: `cht-deploy` script
- Version: `master`

**Additional context**
I initially found this when testing [this PR](https://github.com/medic/cht-core/pull/9074/files).

**Comment by 1yuv** [comment]
Can you check if your login to eks service is still active? I encountered this error message once then I logged in to eks again and I was able to deploy without any error.

**Comment by dianabarsan** [comment]
Seems this has been fixed!
