### ISSUE TITLE
Integration tests fail with 420 Too Many Requests when running on a fast machine

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9079]
**Describe the issue**

Having certain requests fail with 401s is expected in our tests, this is how we validate that certain endpoints require authentication. 
However, due to how we set up rate limiting, having all these failed requests originate from the same IP can make subsequent requests automatically fail as well, if the rate limiting is exceeded.

Logs:

```
1) Users API
       token-login
         "after each" hook for "should update a user correctly with token_login":
     Error: the object {
  "code": 429
  "error": "Too Many Requests"
  "message": [undefined]
  "name": "Too Many Requests"
  "stack": "Error\n    at Object.generateErrorFromResponse (/home/diana/projects/medic/node_modules/pouchdb-errors/lib/index.js:104:18)\n    at /home/diana/projects/medic/node_modules/pouchdb-adapter-http/lib/index.js:254:33\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  "status": 429
} was thrown, throw an Error :)
      at thrown2Error (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:1241:10)
      at Runner.fail (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:443:11)
      at cbHookRun (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:532:14)
      at done (/home/diana/projects/medic/node_modules/mocha/lib/runnable.js:310:5)
      at /home/diana/projects/medic/node_modules/mocha/lib/runnable.js:377:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) Users API
       token-login
         "after all" hook for "should non-admin users cannot edit token_login docs":
     Error: the object {
  "code": 429
  "error": "Too Many Requests"
  "message": [undefined]
  "name": "Too Many Requests"
  "stack": "Error\n    at Object.generateErrorFromResponse (/home/diana/projects/medic/node_modules/pouchdb-errors/lib/index.js:104:18)\n    at /home/diana/projects/medic/node_modules/pouchdb-adapter-http/lib/index.js:254:33\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  "status": 429
} was thrown, throw an Error :)
      at thrown2Error (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:1241:10)
      at Runner.fail (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:443:11)
      at cbHookRun (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:532:14)
      at done (/home/diana/projects/medic/node_modules/mocha/lib/runnable.js:310:5)
      at /home/diana/projects/medic/node_modules/mocha/lib/runnable.js:377:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  3) Users API
       GET api/v2/users/{username}
         "before all" hook for "retrieves a user by username":
     Error: A previous test did not call revertSettings
      at updateCustomSettings (/home/diana/projects/medic/tests/utils/index.js:479:11)
      at updateSettings (/home/diana/projects/medic/tests/utils/index.js:524:9)
      at Object.updatePermissions (/home/diana/projects/medic/tests/utils/index.js:1461:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.<anonymous> (/home/diana/projects/medic/tests/integration/api/controllers/users.spec.js:1632:7)

  4) Users API
       GET api/v2/users/{username}
         "after all" hook for "retrieves self even when user does not have can_view_users permission":
     Error: the object {
  "code": 429
  "error": "Too Many Requests"
  "message": [undefined]
  "name": "Too Many Requests"
  "stack": "Error\n    at Object.generateErrorFromResponse (/home/diana/projects/medic/node_modules/pouchdb-errors/lib/index.js:104:18)\n    at /home/diana/projects/medic/node_modules/pouchdb-adapter-http/lib/index.js:254:33\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  "status": 429
} was thrown, throw an Error :)
      at thrown2Error (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:1241:10)
      at Runner.fail (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:443:11)
      at cbHookRun (/home/diana/projects/medic/node_modules/mocha/lib/runner.js:532:14)
      at done (/home/diana/projects/medic/node_modules/mocha/lib/runnable.js:310:5)
      at /home/diana/projects/medic/node_modules/mocha/lib/runnable.js:377:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Describe the improvement you'd like**
I'm experimenting with adding an 'X-Forwarded-For' header with a random IP to requests that lack authentication.

**Comment by mrjones-plip** [comment]
@dianabarsan - I seem to reliably having this problem when running `npm run integration-all-k3d-local` locally - i've gotten 3s in a row. While I'm  happy to open a new ticket, I wanted to sanity check on this old ticket in case I'm doing something silly and you already solved it.

Steps to reproduce:
1. pull `master` latest (as of 9eb752c292eff9e6ecc4080454eea1d2c545da6e)
2. run test (is `build-dev` needed?): `npm ci; npm run build-dev; npm run integration-all-k3d-local`

expected: tests complete
actual: `429`


here's my local environment:

<details><summary>docker, compose and k3d versions, kernel and OS info</summary>
<p>

```
$ docker -v && docker compose version && k3d version

Docker version 29.2.1, build a5c7197
Docker Compose version v5.1.0
k3d version v5.8.3
k3s version v1.33.6-k3s1 (default)

$ uname -a && lsb_release -a

Linux nubuntu 6.18.7-100.fc42.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jan 23 15:37:26 UTC 2026 x86_64 GNU/Linux
LSB Version:	n/a
Distributor ID:	Bluefin
Description:	Bluefin (Version: gts-42.20260303)
Release:	42
Codename:	Deinonychus
```

</p>
</details> 


And here's my logs from the e2e tests:

<details><summary>detailed log from k3d test</summary>
<p>

```
Error with request: POST https://localhost/api/v1/users 400
        ✔ should throw an error when phone is missing when updating a user with token_login (758ms)
        ✔ should create a user correctly with token_login (1132ms)
        ✔ should update a user correctly with token_login (1298ms)
Error with request: POST https://localhost/_users/_all_docs 429
        1) "after each" hook for "should update a user correctly with token_login"
Error with request: GET https://localhost/medic-test/?end=should_update_a_user_correctly_with_token_login 429
Error logging test end - ignoring
      2) "after all" hook for "should non-admin users cannot edit token_login docs"
    GET api/v2/users/{username}
Error with request: POST https://localhost/medic-test/_bulk_docs 429
      3) "before all" hook for "retrieves a user by username"
Error with request: PUT https://localhost/api/v1/settings?replace=1 429
      4) "after all" hook for "retrieves self even when user does not have can_view_users permission"
    POST/GET api/v2/users
Error with request: POST https://localhost/medic-test/ 429
      5) "before all" hook for "should create and get all users"
      6) "after all" hook for "should create and query users using filters"
    POST api/v3/users
Error with request: POST https://localhost/medic-test/_bulk_docs 429
      7) "before all" hook for "should create users with multiple facilities"
    POST /api/v1/users
Error with request: POST https://localhost/medic-test/_bulk_docs 429
      8) "before all" hook for "should not set password_change_required when user has can_skip_password_change permission"
    oidc-login
Error with request: POST https://localhost/medic-test/_bulk_docs 429
      9) "before all" hook for "should fail to create an OIDC user when oidc_provider is not configured in settings"
Error with request: GET https://localhost/_users/_all_docs?start_key="org.couchdb.user:" 429
      10) "after all" hook for "should fail to create an OIDC user when oidc_provider is not configured in settings"

  well-known
    GET /.well-known/assetlinks.json
Error with request: GET https://localhost/medic-test/?start=returns_404_if_not_configured 429
Api is not up. Cancelling workflow Error: 429 - {"code":429,"error":"Too Many Requests"}
    at request (/var/home/mrjones/Documents/MedicMobile/cht-core/tests/utils/index.js:261:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.apiLogTestStart (/var/home/mrjones/Documents/MedicMobile/cht-core/tests/utils/index.js:1612:5) {
  body: { code: 429, error: 'Too Many Requests' },
  status: 429,
  ok: false,
  headers: Headers {
    'content-length': '40',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 27 Mar 2026 22:42:26 GMT',
    'x-powered-by': 'Express'
  },
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: true,
    requestIncludesCredentials: true,
    type: 'default',
    status: 429,
    timingInfo: {
      startTime: 265223.33422,
      redirectStartTime: 0,
      redirectEndTime: 0,
      postRedirectStartTime: 265223.33422,
      finalServiceWorkerStartTime: 0,
      finalNetworkResponseStartTime: 265223.899924,
      finalNetworkRequestStartTime: 265223.363805,
      endTime: 0,
      encodedBodySize: 40,
      decodedBodySize: 40,
      finalConnectionTimingInfo: [Object]
    },
    cacheState: '',
    statusText: 'Too Many Requests',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ URL {} ],
    body: { stream: undefined, source: null, length: null }
  },
  [Symbol(headers)]: Headers {
    'content-length': '40',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 27 Mar 2026 22:42:26 GMT',
    'x-powered-by': 'Express'
  }
}

kubectl -n cht-e2e --context k3d-cht-e2e get pods --no-headers -o name

pod/cht-api-684749d5f8-8stvp
pod/cht-couchdb-1-6769f895f4-vlcx5
pod/cht-couchdb-2-c4cb6bcd-82l5m
pod/cht-couchdb-3-78d9f7c4c-gkvq9
pod/cht-haproxy-7b896b4768-g6rqr
pod/cht-haproxy-healthcheck-6d85678687-ttvmq
pod/cht-sentinel-68bc486f47-x5tgg
```

</p>
</details> 

As well, here's logs from API pod inside the k3d-cht-e2e container (as well as the rest of the logs to be safe 😅 ):   [failed.k3s.test.logs.zip](https://github.com/user-attachments/files/26317815/failed.k3s.test.logs.zip)

**Comment by dianabarsan** [comment]
Interesting, thanks for sharing, @mrjones-plip . 

In e2e tests, we use a random [IP addresses and an X-Forwarded-For header](https://github.com/medic/cht-core/blob/423ff478ca257f60189674b555c3dd9da63f6842/tests/utils/index.js#L214) to avoid this problem. And it seems to work just fine with docker tests. 

Apparently the k3d tests don't forward headers correctly? It's surprising this issue is only happening locally.

**Comment by mrjones-plip** [comment]
Yeah - I haven't dug into the IP randomization, but it looks to me like it's failing and just using one IP (`10.42.0.1`).  I'm surprised it doesn't fail sooner! 

```
➜  failed.k3s.test.logs grep -c 10.42.0.1 api.k3d.logs
11780
➜  failed.k3s.test.logs wc -l api.k3d.logs         
17830 api.k3d.logs
```

I guess if it's not failing in CI we're fine - but I'll dig a bit more.

**Comment by dianabarsan** [comment]
> I'm surprised it doesn't fail sooner!

We don't frequently make calls where we expect unauthorized responses. except for that test.

**Comment by mrjones-plip** [comment]
I guess this is only a problem for me? I'm unable to reproduce on my laptop which has literally the exact same versions of stuff installed (maybe it's timing/speed dependent 🤷 )

I'm slowly, carefully backing away from the command line, pretending like I didn't see anything 😅

**Comment by mrjones-plip** [comment]
@dianabarsan - per our chat yesterday, some time in the next week or two can you try running these locally on you're speedy desktop to see if you're able to reproduce my error? Our theory was that my slightly faster desktop reliably reproduced over my slower laptop so, by extension, your desktop should reproduce as well.

No rush!

**Comment by dianabarsan** [comment]
Sorry, this has been way down my priorities list.

**Comment by mrjones-plip** [comment]
Fair! That's prob a good place for it

**Comment by dianabarsan** [comment]
Ok, I figured it's just one command so I ran it just now. tests passed: 
```
k3d cluster delete cht-e2e
WARN[0002] Failed to delete volume 'k3d-cht-e2e-images' of cluster 'failed to find volume 'k3d-cht-e2e-images': Error: No such volume: k3d-cht-e2e-images': cht-e2e -> Try to delete it manually 

INFO[0000] Deleting cluster 'cht-e2e'                   
INFO[0002] Deleting 2 attached volumes...               
INFO[0002] Removing cluster details from default kubeconfig... 
INFO[0002] Removing standalone kubeconfig file (if there is one)... 
INFO[0002] Successfully deleted cluster cht-e2e!        

Test done. Signing off ...

  694 passing (16m)

```

no errors.

**Comment by dianabarsan** [comment]
I ran it a few more times, and got the error about 50% of the time.
