### ISSUE TITLE
cht-deploy-script: handle URL unsafe passwords properly in values.yaml

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#9129]
**What feature do you want to improve?**
cht-deploy 

**Describe the improvement you'd like**
`Avoid using non-url-safe characters in password` is mentioned in values.yml, but if users specify such password, cht-script resumes with deployment and couchdb is up. However, `cht-api` can't connect because of `non-url-safe` password, hence a deployment is in wrong state, where other services are up, but cht-api is not. 

```
name: 'StatusCodeError',
  statusCode: 401,
  message: '401 - {"error":"unauthorized","reason":"Name or password is incorrect."}',
  error: { error: 'unauthorized', reason: 'Name or password is incorrect.' },
  [stack]: 'StatusCodeError: 401 - {"error":"unauthorized","reason":"Name or password is incorrect."}\n' +
    '    at new StatusCodeError (/service/api/node_modules/request-promise-core/lib/errors.js:32:15)\n' +
    '    at plumbing.callback (/service/api/node_modules/request-promise-core/lib/plumbing.js:104:33)\n' +
    '    at Request.RP$callback [as _callback] (/service/api/node_modules/request-promise-core/lib/plumbing.js:46:31)\n' +
    '    at self.callback (/service/api/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (node:events:518:28)\n' +
    '    at Request.<anonymous> (/service/api/node_modules/request/request.js:1154:10)\n' +
    '    at Request.emit (node:events:518:28)\n' +
    '    at IncomingMessage.<anonymous> (/service/api/node_modules/request/request.js:1076:12)\n' +
    '    at Object.onceWrapper (node:events:632:28)\n' +
    '    at IncomingMessage.emit (node:events:530:35)'
```

**Describe alternatives you've considered**
There are two approaches: 
1. Handle non-url safe passowrds as well.
2. Throw error when non-url-safe password is used and don't restart any pods.

**Additional context**

**Comment by andrablaj** [comment]
As the cht-deploy script is not maintained anymore, closing this issue as not planned.
