### ISSUE TITLE
Errors validating phone numbers result in feedback document spam

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9254]
**Describe the bug**
eCHIS Kenya has tens of thousands of feedback documents about phone number validation

```
// 20240710143725
// https://baringo.echis.go.ke/medic-users-meta/feedback-2024-07-09T13:02:43.033Z-7ebc5349-7a6d-4f22-9e58-6df53d574802

{
  "_id": "feedback-2024-07-09T13:02:43.033Z-7ebc5349-7a6d-4f22-9e58-6df53d574802",
  "_rev": "1-b6a47d996671e43c922393457c158b17",
  "meta": {
    "time": "2024-07-09T13:02:43.033Z",
    "user": {
      "name": "xxx",
      "roles": [
        "community_health_volunteer"
      ]
    },
    "language": "en",
    "url": "https://baringo.echis.go.ke/#/contacts/6c9556a0-4e0e-5bd1-a1a3-36c68c72b92d/add/e_household?from=list",
    "version": "4.1.0",
    "source": "automatic",
    "deviceId": "c003a92a-6354-4a9c-906a-8d38ff5d31de"
  },
  "info": {
    "message": "Uncaught (in promise): Error: invalid phone number: \"0726XXX\"\nError: invalid phone number: \"0726XXX\"\n    at https://baringo.echis.go.ke/main.js:1:2251727\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:24796)\n    at Object.onInvoke (https://baringo.echis.go.ke/main.js:1:2387990)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:24735)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:18856)\n    at https://baringo.echis.go.ke/polyfills.js:1:35733\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:25487)\n    at Object.onInvokeTask (https://baringo.echis.go.ke/main.js:1:2387800)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:25408)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:19663)",
    "stack": "Error: Uncaught (in promise): Error: invalid phone number: \"07XXX\"\nError: invalid phone number: \"0726XXX\"\n    at https://baringo.echis.go.ke/main.js:1:2251727\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:24796)\n    at Object.onInvoke (https://baringo.echis.go.ke/main.js:1:2387990)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:24735)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:18856)\n    at https://baringo.echis.go.ke/polyfills.js:1:35733\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:25487)\n    at Object.onInvokeTask (https://baringo.echis.go.ke/main.js:1:2387800)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:25408)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:19663)\n    at ge (https://baringo.echis.go.ke/polyfills.js:1:34913)\n    at ge (https://baringo.echis.go.ke/polyfills.js:1:34431)\n    at https://baringo.echis.go.ke/polyfills.js:1:35772\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:25487)\n    at Object.onInvokeTask (https://baringo.echis.go.ke/main.js:1:2387800)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:25408)\n    at R.value (https://baringo.echis.go.ke/polyfills.js:1:19663)\n    at ke (https://baringo.echis.go.ke/polyfills.js:1:27831)\n    at R.value [as invoke] (https://baringo.echis.go.ke/polyfills.js:1:27476)\n    at W (https://baringo.echis.go.ke/polyfills.js:1:40372)"
  },
...
  "type": "feedback"
}
```

**Expected behavior**
We don't need feedback documents for normal validation errors which occur regularly during form completion and are often fixed immediately in order to submit the form.

**Environment**
- Instance: baringo
- Version: 4.1

**Additional context**

**Comment by kennsippell** [comment]
I'm content to close this as fixed in 4.4. Will reactivate if it happens on new versions.
