### ISSUE TITLE
Workflows repeatedly fails in "before all" hook for Contact summary error 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9260]
**Describe the issue**
This test's before all hook fails repeatedly. Unfortunately, there are no screenshots saved in hooks, so there isn't clear information about what happens. 
This is how the failure looks like: 
```
[chrome-headless-shell 126.0.6478.126 linux #0-3]     Contact summary error
[chrome-headless-shell 126.0.6478.126 linux #0-3]        ✖ "before all" hook for Contact summary error
[chrome-headless-shell 126.0.6478.126 linux #0-3]
[chrome-headless-shell 126.0.6478.126 linux #0-3] 4 passing (1m 7.8s)
[chrome-headless-shell 126.0.6478.126 linux #0-3] 1 failing
[chrome-headless-shell 126.0.6478.126 linux #0-3]
[chrome-headless-shell 126.0.6478.126 linux #0-3] 1) Contact summary error "before all" hook for Contact summary error
[chrome-headless-shell 126.0.6478.126 linux #0-3] element ("#header-dropdown-link") still not displayed after 40000ms
[chrome-headless-shell 126.0.6478.126 linux #0-3] Error: element ("#header-dropdown-link") still not displayed after 40000ms
[chrome-headless-shell 126.0.6478.126 linux #0-3]     at async waitForAngularLoaded (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:303:3)
[chrome-headless-shell 126.0.6478.126 linux #0-3]     at async waitForPageLoaded (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:309:3)
[chrome-headless-shell 126.0.6478.126 linux #0-3]     at async Object.goToBase (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:221:3)
[chrome-headless-shell 126.0.6478.126 linux #0-3]     at async Object.cookieLogin (/home/runner/work/cht-core/cht-core/tests/page-objects/default/login/login.wdio.page.js:62:3)
[chrome-headless-shell 126.0.6478.126 linux #0-3]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/contacts/contact-details.wdio-spec.js:174:7)
```

**Describe the improvement you'd like**
Fix the test.

**Comment by kevSeguraEdify** [comment]
Hi @dianabarsan, I'm from Edify, if this ticket is still available please assign it to me so I can review it

**Comment by dianabarsan** [comment]
Usually debugging UI e2e tests is really tricky, and not at all straight-forward. You'll probably have to deal with some race condition. 

I wouldn't recommend this as a first-try ticket, but I wish you the best of luck, persistence, patience and inspiration :D

**Comment by kevSeguraEdify** [comment]
Hi @dianabarsan, I was working on this ticket but could get running this test on my local machine. From the logs provided, I get the error was on the `contact-details.wdio-spec.js` file, under the `Contact summary error` set of tests, but I encountered two blockers:
1 - On the logs provided it says that the test `"before all" hook for Contact summary error` it's failing, but it seems this test no longer under the `Contact summary error` set of tests.
2 - I couldn't run the e2e tests, i'm getting these errors: 
```
Checking API, retries left 180
(node:80853) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
API check failed, trying again in 1 second
fetch failed
Checking API, retries left 179
API check failed, trying again in 1 second
fetch failed
Checking API, retries left 178
Error with request: GET https://localhost/api/info 502
API check failed, trying again in 1 second
502 - {"type":"ERROR","error":"502 Bad Gateway","server":"nginx"}
Checking API, retries left 177
...
```
```
Error: Error: Error: Got status code 404
Failed downloading chromedriver v140.0.7339.133 using {"cacheDir":"/var/folders/61/3s8thbcj1l996f_8dj_1phvm0000gn/T","buildId":"140.0.7339.133","platform":"mac_arm","browser":"chromedriver","unpack":true}: Got status code 404
```

Is these are know configuration issues or there is documentation to fix this?

**Comment by dianabarsan** [comment]
Hi @kevSeguraEdify 

For 1. 
The issue was logged more than one year ago. It's possible that [this commit](https://github.com/medic/cht-core/commit/5157ee973030631ae5beb81828a7f07388580814#diff-289bc2bf56ce15da23defc0c463aad4b9eb4eedab428765f207d04b93ca14879) fixed it. 
For the error, it happens here: https://github.com/medic/cht-core/blob/master/tests/e2e/default/contacts/contact-details.wdio-spec.js#L154 as can be seen clearly in the stack trace. 

For 2. 
The first logs that you have shared are normal, it's expected for the application to take a while to start up. 
As for downloading the chromedriver, I have not seen this before and it might be system specific. Are there more details that you can share?

**Comment by kevSeguraEdify** [comment]
@dianabarsan this is the full log:

```
Error: Error: Got status code 404
Failed downloading chromedriver v140.0.7339.133 using {"cacheDir":"/var/folders/61/3s8thbcj1l996f_8dj_1phvm0000gn/T","buildId":"140.0.7339.133","platform":"mac_arm","browser":"chromedriver","unpack":true}: Got status code 404
    at file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node.js:112:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _install (file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node.js:108:3)
    at async _install (file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node.js:108:3)
    at async setupChromedriver (file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node.js:223:7)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Launcher.run (file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/build/index.js:875:7)
```

It's shown after the retries logs that I share first and there is not other information about this error.

**Comment by dianabarsan** [comment]
it looks like this is a Windows environment?

**Comment by kevSeguraEdify** [comment]
Sorry for my late response @dianabarsan.
No, it's on MacOs.

**Comment by dianabarsan** [comment]
Tagging @lorerod here, as she uses MacOs and might be more familiar with this error.

**Comment by lorerod** [comment]
> ```
> Error: Error: Got status code 404
> Failed downloading chromedriver v140.0.7339.133 using {"cacheDir":"/var/folders/61/3s8thbcj1l996f_8dj_1phvm0000gn/T","buildId":"140.0.7339.133","platform":"mac_arm","browser":"chromedriver","unpack":true}: Got status code 404
>     at file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node.js:112:13
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async _install (file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node.js:108:3)
>     at async _install (file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node.js:108:3)
>     at async setupChromedriver (file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node.js:223:7)
>     at async Promise.all (index 0)
>     at async Promise.all (index 0)
>     at async Launcher.run (file:///Users/kevinsegura/Documents/medic/kevin/cht-core/node_modules/@wdio/cli/build/index.js:875:7)
> ```
> 
> It's shown after the retries logs that I share first and there is not other information about this error.

@kevSeguraEdify I haven’t seen that error before, let’s investigate. Quick question: Could you try running' npm ci' in the cht-core root directory to confirm you have all the necessary dependencies?
Additionally, could you please share your Chrome version?

**Comment by kevSeguraEdify** [comment]
Hi @lorerod now it's working, for the record if it happens to other person, from what I researched, my chrome version is `v140.0.7339.133` and it was too new at that moment so there wasn't an existing chromedriver version released and thats why I had the error apparently.

**Comment by kevSeguraEdify** [comment]
@dianabarsan since I already can run the e2e tests, I ran all e2e tests together and only this test suite some times and it seems to be already fix as you mentioned, so I think we could close this ticket.

```
 "spec" Reporter:
------------------------------------------------------------------
[chrome 140.0.7339.186 mac #0-0] Running: chrome (v140.0.7339.186) on mac
[chrome 140.0.7339.186 mac #0-0] Session ID: 6b09b6d6c62d0a9565de48116e1311c0
[chrome 140.0.7339.186 mac #0-0]
[chrome 140.0.7339.186 mac #0-0] » tests/e2e/default/contacts/contact-details.wdio-spec.js
[chrome 140.0.7339.186 mac #0-0] Contact details page.
[chrome 140.0.7339.186 mac #0-0]     Permissions to show reports and tasks
[chrome 140.0.7339.186 mac #0-0]        ✓ should show reports and tasks when permissions are enabled
[chrome 140.0.7339.186 mac #0-0]        ✓ should show contact summary that has the full context for reports > 50 validate that the pregnancy card is always displayed
[chrome 140.0.7339.186 mac #0-0]        ✓ should not show reports when permission is disabled
[chrome 140.0.7339.186 mac #0-0]        ✓ should not show tasks when permission is disabled
[chrome 140.0.7339.186 mac #0-0]
[chrome 140.0.7339.186 mac #0-0]     Contact summary error
[chrome 140.0.7339.186 mac #0-0]        ✓ should show error log for bad config
[chrome 140.0.7339.186 mac #0-0]
[chrome 140.0.7339.186 mac #0-0] 5 passing (42.5s)


Spec Files:      1 passed, 1 total (100% completed) in 00:01:05  
```

**Comment by dianabarsan** [comment]
Sweet, I haven't seen this fail recently so I guess it's fixed! Thanks for the investigation @kevSeguraEdify !
