### ISSUE TITLE
No feedback document recorded on PouchDb crash

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9294]
**Describe the bug**
When a PouchDb crash happens, we display a modal saying that the app needs to be reloaded, and we log the error on screen on the tasks tab. However, such an error does not record a feedback document, because saving the feedback document fails. 

**To Reproduce**

1. Login as an offline user. 
2. Open the console 
3. type `CHTCore.dbService.get().close();`. This will close the connection to the main database -  but theoretically not to the meta database.
4. Navigate to the tasks page. 
5. Observe the error being visible in the UI and `Error getting tasks for all contacts` getting reported in the console. 
6. Observe a warning `Error while trying to record error` in the console. 
7. Reload the page and sync. 
8. Check the server and see that there is no feedback doc recorded for the event. 

**Expected behavior**
We should have a workaround in place to record feedback docs when PouchDb cannot write. 

**Logs**
```
feedback.service.ts:179 Error getting tasks for all contacts 
Error: database is closed
    at PouchDB.<anonymous> (index.es.js:279:29)
    at PouchDB.<anonymous> (index.js:14:18)
    at index.es.js:236:21
    at new ZoneAwarePromise (zone.js:1425:21)
    at PouchDB.<anonymous> (index.es.js:223:19)
    at PouchDB.get (index.js:14:18)
    at db.service.ts:46:64
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Zone.run (zone.js:130:43)
    at NgZone.runOutsideAngular (core.mjs:14778:28)

feedback.service.ts:179 Error while trying to record error 
Error: database is closed
    at PouchDB.<anonymous> (index.es.js:279:29)
    at PouchDB.<anonymous> (index.js:14:18)
    at index.es.js:236:21
    at new ZoneAwarePromise (zone.js:1425:21)
    at PouchDB.<anonymous> (index.es.js:223:19)
    at PouchDB.get (index.js:14:18)
    at db.service.ts:46:64
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Zone.run (zone.js:130:43)
    at NgZone.runOutsideAngular (core.mjs:14778:28)

feedback.service.ts:179 Unhandled Promise rejection: database is closed ; Zone: <root> ; Task: Promise.then ; Value: 
Error: database is closed
    at PouchDB.<anonymous> (index.es.js:279:29)
    at PouchDB.<anonymous> (index.js:14:18)
    at index.es.js:236:21
    at new ZoneAwarePromise (zone.js:1425:21)
    at PouchDB.<anonymous> (index.es.js:223:19)
    at PouchDB.get (index.js:14:18)
    at db.service.ts:46:64
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Zone.run (zone.js:130:43)
    at NgZone.runOutsideAngular (core.mjs:14778:28)
```

**Environment**
- Browser: Chrome
- App: webapp
- Version: 4.7.x, 4.8.x, 4.9.x

**Additional context**
Reported as https://github.com/medic/config-nssd/issues/546

**Comment by dianabarsan** [comment]
It turns out the failure is happening because we actually access the main database when we attempt to generate the feedback doc here: https://github.com/medic/cht-core/blob/5274b92dc25d54680427af8ad55ae7024485113e/webapp/src/ts/services/feedback.service.ts#L194

**Comment by lorerod** [comment]
**Reproduced this locally**

- After navigating to Task page, this is shown in the console:

![Screenshot 2024-08-14 at 4 05 38 PM](https://github.com/user-attachments/assets/319cff0d-5255-4c34-ad7b-04f702144f85)

- After sync, there are no feedback docs for the user:

![Screenshot 2024-08-14 at 4 09 39 PM](https://github.com/user-attachments/assets/f8f6d352-ca14-45ce-8ffe-8cfb7da9bdfe)



**Fixed in branch `9294-feedback-doc-on-couch-crash`**

- After navigating to Task page, this is shown in the console:

![Screenshot 2024-08-14 at 4 16 59 PM](https://github.com/user-attachments/assets/379b6d0e-38b1-4030-95cb-dc3ce6ce99f1)

- After sync, there are three feedback docs for the user:

![Screenshot 2024-08-14 at 4 19 05 PM](https://github.com/user-attachments/assets/5a78be2b-092c-4cc7-bf3d-6f0b80b3bd30)
