### ISSUE TITLE
Validation test is failing silently

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#9315]
**Describe the issue**

To reproduce
1. Go to the `shared-libs/validation` folder
2. Run `npm test`

The output has a fatal error message:
```
  validations
    ✔ should throw an error when validate is called without initialization
2024-08-13T07:12:38.957 ERROR: error parsing validation: ParserException { message: 'Unexpected identifier', pos: 2 } 
    ✔ validate handles pupil parse errors
    ✔ validate handles pupil regex
    ✔ pass unique validation when no doc found
    ✔ pass unique validation when doc is the same
2024-08-13T07:12:38.968 ERROR: Error running "unique" validation: TypeError: callsArg failed: 2 arguments required but only 1 present
    at ensureArgs (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/behavior.js:87:15)
    at callCallback (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/behavior.js:97:9)
    at Object.invoke (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/behavior.js:160:29)
    at Object.functionStub (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/stub.js:44:43)
    at Function.invoke (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/proxy-invoke.js:53:47)
    at Object.allDocs (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/proxy.js:265:26)
    at /home/gareth/src/medic/cht-core/shared-libs/validation/src/validation.js:2:3271 {
  [stack]: 'TypeError: callsArg failed: 2 arguments required but only 1 present\n' +
    '    at ensureArgs (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/behavior.js:87:15)\n' +
    '    at callCallback (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/behavior.js:97:9)\n' +
    '    at Object.invoke (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/behavior.js:160:29)\n' +
    '    at Object.functionStub (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/stub.js:44:43)\n' +
    '    at Function.invoke (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/proxy-invoke.js:53:47)\n' +
    '    at Object.allDocs (/home/gareth/src/medic/cht-core/node_modules/sinon/lib/sinon/proxy.js:265:26)\n' +
    '    at /home/gareth/src/medic/cht-core/shared-libs/validation/src/validation.js:2:3271',
  [message]: 'callsArg failed: 2 arguments required but only 1 present'
} 
    ✔ pass unique validation when doc has errors
    ✔ fail unique validation on doc with no errors
    ✔ fail multiple field unique validation on doc with no errors
```

**Comment by garethbowen** [comment]
The problem was that at some point we switched from promises to callbacks and the rest of the tests stubs were fixed but not this one. The reason the test wasn't failing is the validation function catches all errors and logs.

The better solution would be to make the unit smaller so the exception can be thrown back to the unit test, rather than the current version which is tending towards an integration test.
