### ISSUE TITLE
Workflows repeatedly fail in e2e tests for muting and unmuting

### ISSUE THREAD

**Issue by witash** [medic/cht-core#9391]
**Describe the issue**
`for an offline user should mute and unmute a clinic while "offline", without processing in between` and `for an offline user should mute and unmute a person while "offline", with processing in between` in `/tests/e2e/default/transitions/client-side-muting.wdio-spec.js` fail for about 2/3 workflow runs

```
[chrome 128.0.6613.84 linux #0-2] Muting 
[chrome 128.0.6613.84 linux #0-2]     for an online user
[chrome 128.0.6613.84 linux #0-2]        ✓ should not process client-side when muting as an online user
[chrome 128.0.6613.84 linux #0-2] 
[chrome 128.0.6613.84 linux #0-2]     for an offline user
[chrome 128.0.6613.84 linux #0-2]        ✓ should not process muting client-side if not enabled
[chrome 128.0.6613.84 linux #0-2]        ✖ should mute and unmute a person while "offline", with processing in between
[chrome 128.0.6613.84 linux #0-2]        ✖ "after each" hook for for an offline user
[chrome 128.0.6613.84 linux #0-2]     
[chrome 128.0.6613.84 linux #0-2] 2 passing (1m 50.4s)
[chrome 128.0.6613.84 linux #0-2] 1 failing
[chrome 128.0.6613.84 linux #0-2]
[chrome 128.0.6613.84 linux #0-2] 1) for an offline user should mute and unmute a person while "offline", with processing in between
[chrome 128.0.6613.84 linux #0-2] element ("#header-dropdown li.sync-status .success") still not displayed after 20000ms
[chrome 128.0.6613.84 linux #0-2] Error: element ("#header-dropdown li.sync-status .success") still not displayed after 20000ms
[chrome 128.0.6613.84 linux #0-2]     at async syncAndWaitForSuccess (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:329:3)
[chrome 128.0.6613.84 linux #0-2]     at async Object.sync (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:350:3)
[chrome 128.0.6613.84 linux #0-2]     at async updateClientSideMutingSettings (/home/runner/work/cht-core/cht-core/tests/e2e/default/transitions/client-side-muting.wdio-spec.js:225:9)
[chrome 128.0.6613.84 linux #0-2]
[chrome 128.0.6613.84 linux #0-2] 2) for an offline user "after each" hook for for an offline user
[chrome 128.0.6613.84 linux #0-2] element ("#header-dropdown li.sync-status .success") still not displayed after 20000ms
[chrome 128.0.6613.84 linux #0-2] Error: element ("#header-dropdown li.sync-status .success") still not displayed after 20000ms
[chrome 128.0.6613.84 linux #0-2]     at async syncAndWaitForSuccess (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:329:3)
[chrome 128.0.6613.84 linux #0-2]     at async Object.sync (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:350:3)
[chrome 128.0.6613.84 linux #0-2]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/transitions/client-side-muting.wdio-spec.js:266:7)
```
https://github.com/medic/cht-core/actions/runs/10610097929/job/29407417054

Because it does pass 1/3 of the time, the assumption is that the test is broken, rather than the feature, but need to confirm.

**Describe the improvement you'd like**
Fix the test.
First thing to try is increasing the timeout, although would be better to fix the underlying issue; 20s should be plenty.

**Comment by garethbowen** [comment]
@witash I think this is a duplicate as the error is exactly the same as in this issue: https://github.com/medic/cht-core/issues/8936#issuecomment-2283448932 which, if so, is probably caused by #7375 

If so, please connect with @dianabarsan as she's started looking in to this and can probably give you some tips on how to go about fixing it.

**Comment by dianabarsan** [comment]
I've been meaning to change how the service worker is updated for such a long time. I'm down to put some time into it for next week.

**Comment by dianabarsan** [comment]
@witash is right, I just reran this test 10 times and it kept failing. I ended up disabling it on those branches.

**Comment by dianabarsan** [comment]
It appears that one of the muting forms fails to submit - the submit report is stuck on loading: 
![image](https://github.com/user-attachments/assets/6aaf1b51-dbf9-48ac-b0cc-89084ad47dc1)

**Comment by dianabarsan** [comment]
Ok. I dug further into this: 

On CI this fails with: 
![image](https://github.com/user-attachments/assets/f70ed105-3461-4ac1-a882-909eeb829e8d)

Looking at browser logs I see: 
```
[error] Console Api Event: [{"type":"object","className":"ye","description":"ye","objectId":"-5119646230267331109.9.1","preview":{"type":"object","description":"ye","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Failed to fetch\n    at https://localhos…at ne.run (https://localhost/polyfills.js:1:6297)"},{"name":"message","type":"string","value":"Failed to fetch"},{"name":"docId","type":"string","value":"_local/RKqlK_XzqTqVNyk1pzNeHg=="},{"name":"result","type":"object","value":"Object"}]}}]
[error] Console Api Event: [{"type":"string","value":"Error replicating to remote server"},{"type":"object","className":"ye","description":"ye","objectId":"-5119646230267331109.9.2","preview":{"type":"object","description":"ye","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Failed to fetch\n    at https://localhos…at ne.run (https://localhost/polyfills.js:1:6297)"},{"name":"message","type":"string","value":"Failed to fetch"},{"name":"docId","type":"string","value":"_local/RKqlK_XzqTqVNyk1pzNeHg=="},{"name":"result","type":"object","value":"Object"}]}}]
[error] Console Api Event: [{"type":"string","value":"Error replicating to remote server"},{"type":"object","className":"ye","description":"ye","objectId":"-5119646230267331109.9.3","preview":{"type":"object","description":"ye","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Failed to fetch\n    at https://localhos…at ne.run (https://localhost/polyfills.js:1:6297)"},{"name":"message","type":"string","value":"Failed to fetch"},{"name":"docId","type":"string","value":"_local/RKqlK_XzqTqVNyk1pzNeHg=="},{"name":"result","type":"object","value":"Object"}]}}]
[error] Console Api Event: [{"type":"object","className":"ye","description":"ye","objectId":"-5119646230267331109.9.4","preview":{"type":"object","description":"ye","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Failed to fetch\n    at https://localhos…H.invoke (https://localhost/polyfills.js:1:10947)"},{"name":"message","type":"string","value":"Failed to fetch"},{"name":"docId","type":"string","value":"_local/RKqlK_XzqTqVNyk1pzNeHg%3D%3D"},{"name":"result","type":"object","value":"Object"}]}}]
[error] Console Api Event: [{"type":"string","value":"Error replicating to remote server"},{"type":"object","className":"ye","description":"ye","objectId":"-5119646230267331109.9.5","preview":{"type":"object","description":"ye","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Failed to fetch\n    at https://localhos…H.invoke (https://localhost/polyfills.js:1:10947)"},{"name":"message","type":"string","value":"Failed to fetch"},{"name":"docId","type":"string","value":"_local/RKqlK_XzqTqVNyk1pzNeHg%3D%3D"},{"name":"result","type":"object","value":"Object"}]}}]
[error] Console Api Event: [{"type":"string","value":"Error replicating to remote server"},{"type":"object","className":"ye","description":"ye","objectId":"-5119646230267331109.9.6","preview":{"type":"object","description":"ye","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: Failed to fetch\n    at https://localhos…H.invoke (https://localhost/polyfills.js:1:10947)"},{"name":"message","type":"string","value":"Failed to fetch"},{"name":"docId","type":"string","value":"_local/RKqlK_XzqTqVNyk1pzNeHg%3D%3D"},{"name":"result","type":"object","value":"Object"}]}}]
```

And when I check api logs, do find a request for this _local doc that got interrupted (?):
```
2024-09-04T13:23:53.251 REQ: c7b252f8-da30-49f7-9acd-d4d13a782f01 172.18.0.1 - PUT /medic/_local/RKqlK_XzqTqVNyk1pzNeHg%3D%3D HTTP/1.0
2024-09-04T13:23:53.271 DEBUG: Checking for a configured outgoing message service 
2024-09-04T13:23:53.312 RES: c7b252f8-da30-49f7-9acd-d4d13a782f01 172.18.0.1 - PUT /medic/_local/RKqlK_XzqTqVNyk1pzNeHg%3D%3D HTTP/1.0 - - - ms```

I'm not sure about the reason for this interruption. I'm not seeing this request in Haproxy.

**Comment by garethbowen** [comment]
> [error] Console Api Event: [{"type":"string","value":"Error replicating to remote server"}

I'm wondering if it's related to throttling the browser to offline then online again. Maybe going online is failing silently, or the await is resolving too quickly? If we're confident it's a testing only issue, then we could experiment with adding a pause after going back online, or even better waiting for a remote request to succeed before being confident that we're online again.

**Comment by dianabarsan** [comment]
I've moved this to 4.12. 
>  related to throttling the browser to offline then online again
This could be. I've just implemented a retry and the error proved non persistent. 

Locally. I had geolocation timing out, which caused the endless loading I detailed above. This seems to not affect the test when run in CI.

**Comment by tatilepizs** [comment]
@dianabarsan are you working on fixing this test? I was planning on investigating to see if I could fix it, but first, I wanted to ensure I would not interfere.

**Comment by tatilepizs** [comment]
Debugging this test, I realized that the problem is when the modal related to the updated settings is displayed, it closes the sidebar menu, and sometimes the test is in the middle of verification in that menu, and that is why it is failing. 

The flow that the test is having is first set the browser as offline, update the settings, and then set the browser as online again (see this example), I thought that as soon as the browser was online again the sync would be triggered automatically, so we only needed to wait for the modal to show up, but that is not always the case, sometimes we need to click on the sync button to see the modal (I still don't know what is the difference, because the settings that are updated are always the same ones).

So, if we wait for the modal to be displayed and the sync is not triggered automatically, the tests will fail, so that is not a good idea. We will need to modify the sync method in a way that if the settings change we need to wait for the modal to be displayed, the problem is that if the modal pops up in the middle of the syn process it will close the sidebar menu and when the test is trying to verify if the sync was successfully completed (checking if the success message is displayed) the test will be failed because the menu is closed, so we will need to reopen the sidebar menu. And we can not always wait for that modal because not everytime that we click on the sync button the settings were changed 😕

**Comment by Hendrixx-RE** [comment]
@dianabarsan   is this issue resolved ? If not,Ill look into it.
