### ISSUE TITLE
Feedback doc: TypeError: Cannot read properties of undefined (reading '_id')

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9441]
**Describe the bug**
```
Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading '_id')
TypeError: Cannot read properties of undefined (reading '_id')
    at https://nairobi-echis.health.go.ke/main.js:1:1605730
    at Generator.next (<anonymous>)
    at E (https://nairobi-echis.health.go.ke/main.js:1:1285)
    at h (https://nairobi-echis.health.go.ke/main.js:1:1487)
    at https://nairobi-echis.health.go.ke/main.js:1:1546
    at new r (https://nairobi-echis.health.go.ke/polyfills.js:1:22884)
    at https://nairobi-echis.health.go.ke/main.js:1:1428
    at n.updateFastActions (https://nairobi-echis.health.go.ke/main.js:1:1605805)
    at Object.next (https://nairobi-echis.health.go.ke/main.js:1:1603550)
    at Yr.next (https://nairobi-echis.health.go.ke/main.js:1:8993)
    at ve (https://nairobi-echis.health.go.ke/polyfills.js:1:20329)
    at https://nairobi-echis.health.go.ke/polyfills.js:1:19403
    at https://nairobi-echis.health.go.ke/polyfills.js:1:19511
    at E (https://nairobi-echis.health.go.ke/main.js:1:1320)
    at h (https://nairobi-echis.health.go.ke/main.js:1:1487)
    at https://nairobi-echis.health.go.ke/main.js:1:1546
    at new r (https://nairobi-echis.health.go.ke/polyfills.js:1:22884)
    at https://nairobi-echis.health.go.ke/main.js:1:1428
    at n.updateFastActions (https://nairobi-echis.health.go.ke/main.js:1:1605805)
    at Object.next (https://nairobi-echis.health.go.ke/main.js:1:1603550)
```

**To Reproduce**
Production data

**Expected behavior**
Don't crash

**Logs**

**Environment**
- Instance: eCHIS Kenya
- Browser: (eg: Firefox, Chrome, incognito mode, etc, which worked, which didn't)
- Client platform: (eg: Windows, MacOS, Linux)
- App: (eg: webapp, admin, sentinel, api, couch2pg, cht-conf, etc)
- Version: (eg: 2.15.0, 3.0.0, etc)

**Additional context**
This is in webapp/src/ts/modules/reports/reports-content.component.ts

```
    this.fastActionList = await this.fastActionButtonService.getReportRightSideActions({
      reportContentType: selectedReportDoc.content_type,
      communicationContext: {
        sendTo: await this.getReportContact(selectedReportDoc.contact._id),
        callbackOpenSendMessage: (sendTo) => this.modalService.show(SendMessageComponent, { data: { to: sendTo } }),
      },
    });
```

**Comment by kennsippell** [comment]
It's possible from user reports that they experience this "Error loading form" when this triggers. 
![image](https://github.com/user-attachments/assets/125fc16b-bb37-4f65-8363-d7582a38d218)

Another stack
```
"Uncaught (in promise): TypeError: Cannot read properties of undefined (reading '_id')
TypeError: Cannot read properties of undefined (reading '_id')
    at https://nairobi-echis.health.go.ke/main.js?_sw-precache=90acff8d536409fe701a30df7bdac6c7:1:1101774
    at Generator.next (<anonymous>)
    at c$ (https://nairobi-echis.health.go.ke/main.js?_sw-precache=90acff8d536409fe701a30df7bdac6c7:1:506804)
    at h (https://nairobi-echis.health.go.ke/main.js?_sw-precache=90acff8d536409fe701a30df7bdac6c7:1:507007)
    at https://nairobi-echis.health.go.ke/main.js?_sw-precache=90acff8d536409fe701a30df7bdac6c7:1:507068
    at d (https://nairobi-echis.health.go.ke/polyfills.js?_sw-precache=edc39369e9333bcb01fe3d162d9ada63:1:23310)
    at https://nairobi-echis.health.go.ke/main.js?_sw-precache=90acff8d536409fe701a30df7bdac6c7:1:506948
    at r.updateFastActions (https://nairobi-echis.health.go.ke/main.js?_sw-precache=90acff8d536409fe701a30df7bdac6c7:1:1101882)
    at Object.next (https://nairobi-echis.health.go.ke/main.js?_sw-precache=90acff8d536409fe701a30df7bdac6c7:1:1099592)
    at G.next (https://nairobi-echis.health.go.ke/main.js?_sw-precache=90acff8d536409fe701a30df7bdac6c7:1:3451)"
```

**Comment by kennsippell** [comment]
Would be great to know of workarounds for this if possible. A lot of complaints in our eCHIS support channels for this "error loading forms". Blocking some CHPs from working.

**Comment by latin-panda** [comment]
@kennsippell can you please attach the task form and the report form triggering these errors? Or a snapshot of those forms if there are some privacy concerns

**Comment by kennsippell** [comment]
I found this feedback document for all users reporting the problem, but I no longer believe believe this error is the cause of error loading forms. Sorry for the confusion.

**Comment by HsingFuC** [comment]
Hi @kennsippell, I'm from Edify, if this ticket is still available please assign it to me so I can review it

**Comment by dianabarsan** [comment]
Hi @HsingFuC 

Please let me know if there's anything I can assist with.

**Comment by HsingFuC** [comment]
Hi @kennsippell, do you know how I can reproduce this error? Maybe with step-by-step guidance, since I'm new and still not very familiar with the project

**Comment by dianabarsan** [comment]
I don't think this is reproducible in any easy way. Feedback documents are generated on client devices and are used to track erros that don't surface in our usual AT workflows, so I would expect this to be some strange race condition which is very hard to reproduce (they usually are). 
@kennsippell doesn't have repro steps, but he did include the stack trace of the error. 

My advice is to go backwards from the location of the error and try to guess what could have caused it. 

This is probably not the best issue to tackle as someone new to the project :(

**Comment by HsingFuC** [comment]
Got it, I’ll try to replicate it and review the error message in the meantime. If I can't figure it out in the end, we can reassign it if that works for you

**Comment by andrablaj** [comment]
Hi @HsingFuC! Did you manage to progress on this issue?

**Comment by HsingFuC** [comment]
Hi @andrablaj, I couldn’t reproduce this error. But based on @kennsippell’s description, my guess is that the `if` condition inside `updateFastActions` is missing the `!selectedReportDoc.contact` check in it. Since I can’t reproduce it myself, I don’t feel confident creating the fix.
I also couldn’t reproduce the error shown in the screenshot, so I reviewed the code and I didn’t find any `_id` reference that could trigger this message.

@dianabarsan feel free to reassign this issue if it works for you

**Comment by andrablaj** [comment]
Thank you @HsingFuC! We unassigned this ticket, but feel free to pick any other `Good First Issue` or `Help Wanted` issue if you wish to contribute further!

**Comment by dylanpulver** [comment]
I don't think this one is a race. `reports-content.component.ts:274` reads `selectedReportDoc.contact._id`, and the only guard above it is `!selectedReportDoc` (line 267) — so it throws deterministically, 100% of the time, for any report stored **without a `contact` field**, and never for anything else.

Those reports exist by design. `api/src/services/records.js:106` builds every record from `/api/v2/records` (SMS gateway, RapidPro, Africa's Talking, JSON POST) with no `contact` key at all, and the only thing that ever adds one is `update_clinics` — which is `false` in the default `app_settings.json:462`, and which deliberately leaves `contact` unset when the sender's phone/refid matches no contact. Its own filter (`update_clinics.js:96`) is `!doc.contact`, so the model already assumes these exist. `reports_by_date` emits on `type === 'data_record' && doc.form` with no contact requirement, so they show up in the list and are openable.

**The error text is the discriminator.** I put the four `contact` shapes through the real `@medic/lineage` (in-memory PouchDB → `fetchHydratedDoc` → the real `getSelectedReportDoc` selector → the verbatim body of `updateFastActions`), on master `34500db` and on 4.10.0, the latest release when this was filed. Byte-identical on both:

```
A contact stub present, contact doc present | hydrated.contact="chw-1" | updateFastActions OK
B contact stub present, contact doc MISSING | hydrated.contact="ghost" | updateFastActions OK
C contact: null                             | hydrated.contact=null      | THREW TypeError: Cannot read properties of null (reading '_id')
D no contact key at all                     | hydrated.contact=undefined | THREW TypeError: Cannot read properties of undefined (reading '_id')
```

Only D produces the reported message. That rules out the obvious suspect: B shows a missing/unreplicated/deleted contact doc does **not** cause this — `fillParentsInDocs` keeps the minified stub (`hydration.js:58`, `lineage.shift() || doc.contact`). And "of undefined" rather than "of null" rules out C.

**Why it resists reproduction by using the app:** the form path can't create an affected report. `FormService.getUserContact(true)` throws `error.loading.form.no_contact` before `EnketoService` builds the doc, so anything submitted through a form has a contact. Clicking around a normal instance will never make one.

**Test blind spot:** every `getSelectedReportDoc` override in the suite is either `undefined` or carries a `contact` (`reports-content.component.spec.ts:57,433,459,467`). The `updateFastActions()` block varies `selectMode` and `undefined` exhaustively and never varies the `contact` axis.

To check on an affected instance: `data_record` docs that have a `form` and no `contact`. Where `update_clinics` ran and found nothing, some will also carry `sys.facility_not_found` in `errors`.

**Not verified by me:** your production data, and which version nairobi-eCHIS was running (I used 4.10.0 as the nearest release to the report date). I also did not build the webapp — I copied the `updateFastActions` body verbatim into the harness rather than run the compiled component.

I'm happy to open a PR. `sendTo` is already fully optional-chained in `getSendMessageAction` (`fast-action-button.service.ts:115,119`), so `contact?._id` plus an early return in `getReportContact` for a falsy id is safe and just hides the send-message action. Whether contactless server-ingested reports should reach the UI at all is a separate question and yours, not mine.

*AI disclosure per the CHT AI guidelines: I used Claude Code to navigate the codebase and build the differential harness. Everything above I ran and checked myself.*
