### ISSUE TITLE
RapidPro API changes result in mishandling of errors

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9467]
**Describe the bug**
RapidPro can respond with a 400 error when the target phone number is incorrect, instead of responding with a documented status. 

**To Reproduce**
1. Send a message with an incorrect phone number. 
2. Watch as API retries to send the same message over and over and throws errors. 

**Expected behavior**
An invalid message should receive a failed state, which will make sending not be retried. 

**Logs**
```
024-09-25 19:37:56]   [stack]: 'StatusCodeError: 400 - {"urns":{"0":["Invalid URN: tel:********. Ensure phone numbers contain country codes."]}}\n    at new StatusCodeError (/srv/software/medic-api/md5-cdTbX9bB
8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/plumbing.js:104:
33)\n    at Request.RP$callback [as _callback] (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/srv/software/medic-api/
md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/srv/software/medic-api/md5-cdTbX9bB8ZfHZ
msqbv4Zw==/node_modules/request/request.js:1154:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw
==/node_modules/request/request.js:1076:12)' } 
[2024-09-25 19:37:57] 2024-09-25 19:37:57 ESC[31mERRORESC[39m: Error thrown when trying to send message: { StatusCodeError: 400 - {"urns":{"0":["Invalid URN: tel:********. Ensure phone numbers contain country cod
es."]}}
[2024-09-25 19:37:57]     at new StatusCodeError (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/errors.js:32:15)
[2024-09-25 19:37:57]     at Request.plumbing.callback (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/plumbing.js:104:33)
[2024-09-25 19:37:57]     at Request.RP$callback [as _callback] (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/plumbing.js:46:31)
[2024-09-25 19:37:57]     at Request.self.callback (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request/request.js:185:22)
[2024-09-25 19:37:57]     at emitTwo (events.js:126:13)
[2024-09-25 19:37:57]     at Request.emit (events.js:214:7)
[2024-09-25 19:37:57]     at Request.<anonymous> (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request/request.js:1154:10)
[2024-09-25 19:37:57]     at emitOne (events.js:116:13)
[2024-09-25 19:37:57]     at Request.emit (events.js:211:7)
[2024-09-25 19:37:57]     at IncomingMessage.<anonymous> (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request/request.js:1076:12)
[2024-09-25 19:37:57]   name: 'StatusCodeError',
[2024-09-25 19:37:57]   statusCode: 400,
[2024-09-25 19:37:57]   message: '400 - {"urns":{"0":["Invalid URN: tel:********. Ensure phone numbers contain country codes."]}}',
[2024-09-25 19:37:57]   error: 
[2024-09-25 19:37:57]    { urns: 
[2024-09-25 19:37:57]       { '0': 
[2024-09-25 19:37:57]          [ 'Invalid URN: tel:********. Ensure phone numbers contain country codes.',
[2024-09-25 19:37:57]            [length]: 1 ] } },
[2024-09-25 19:37:57]   [stack]: 'StatusCodeError: 400 - {"urns":{"0":["Invalid URN: tel:********. Ensure phone numbers contain country codes."]}}\n    at new StatusCodeError (/srv/software/medic-api/md5-cdTbX9bB
8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/plumbing.js:104:
33)\n    at Request.RP$callback [as _callback] (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/srv/software/medic-api/
md5-cdTbX9bB8ZfHZmsqbv4Zw==/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/srv/software/medic-api/md5-cdTbX9bB8ZfHZ
msqbv4Zw==/node_modules/request/request.js:1154:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw
==/node_modules/request/request.js:1076:12)' } 
[2024-09-25 19:37:57] 2024-09-25 19:37:57 ESC[31mERRORESC[39m: Error thrown when trying to send message: { TypeError: Cannot read property 'state' of undefined
[2024-09-25 19:37:57]     at getStateUpdate (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:79:17)
[2024-09-25 19:37:57]     at request.post.then.result (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:107:14)
[2024-09-25 19:37:57]     at <anonymous>
[2024-09-25 19:37:57]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2024-09-25 19:37:57]   [stack]: 'TypeError: Cannot read property \'state\' of undefined\n    at getStateUpdate (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:79:17)\n    at request
.post.then.result (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:107:14)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2024-09-25 19:37:57]   [message]: 'Cannot read property \'state\' of undefined' } 
[2024-09-25 19:37:57] 2024-09-25 19:37:57 ESC[31mERRORESC[39m: Error thrown when trying to send message: { TypeError: Cannot read property 'state' of undefined
[2024-09-25 19:37:57]     at getStateUpdate (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:79:17)
[2024-09-25 19:37:57]     at request.post.then.result (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:107:14)
[2024-09-25 19:37:57]     at <anonymous>
[2024-09-25 19:37:57]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2024-09-25 19:37:57]   [stack]: 'TypeError: Cannot read property \'state\' of undefined\n    at getStateUpdate (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:79:17)\n    at request
.post.then.result (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:107:14)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2024-09-25 19:37:57]   [message]: 'Cannot read property \'state\' of undefined' } 
[2024-09-25 19:37:57] 2024-09-25 19:37:57 ESC[31mERRORESC[39m: Error thrown when trying to send message: { TypeError: Cannot read property 'state' of undefined
[2024-09-25 19:37:57]     at getStateUpdate (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:79:17)
[2024-09-25 19:37:57]     at request.post.then.result (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:107:14)
[2024-09-25 19:37:57]     at <anonymous>
[2024-09-25 19:37:57]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2024-09-25 19:37:57]   [stack]: 'TypeError: Cannot read property \'state\' of undefined\n    at getStateUpdate (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:79:17)\n    at request
.post.then.result (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:107:14)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2024-09-25 19:37:57]   [message]: 'Cannot read property \'state\' of undefined' } 
[2024-09-25 19:37:58] 2024-09-25 19:37:58 ESC[31mERRORESC[39m: Error thrown when trying to send message: { TypeError: Cannot read property 'state' of undefined
[2024-09-25 19:37:58]     at getStateUpdate (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:79:17)
[2024-09-25 19:37:58]     at request.post.then.result (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:107:14)
[2024-09-25 19:37:58]     at <anonymous>
[2024-09-25 19:37:58]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2024-09-25 19:37:58]   [stack]: 'TypeError: Cannot read property \'state\' of undefined\n    at getStateUpdate (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:79:17)\n    at request
.post.then.result (/srv/software/medic-api/md5-cdTbX9bB8ZfHZmsqbv4Zw==/src/services/rapidpro.js:107:14)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2024-09-25 19:37:58]   [message]: 'Cannot read property \'state\' of undefined' }
```

**Environment**
- App: API
- Version: 4.11 and much earlier

**Additional context**
Reported on the forum https://forum.communityhealthtoolkit.org/t/duplication-of-messages-in-text-it/4047/6

**Comment by garethbowen** [comment]
The patch appears to be working in production, so merging this for release.
