### ISSUE TITLE
Feedback Doc - Failed during the form rendering : Invalid XML <title>500 Internal Server Error</title>

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9557]
**Describe the bug**
```
    {
      "_id": "feedback-2024-10-02T06:39:53.800Z-56fbba1e-b8d4-4aa2-9a9c-5065e8391fdd",
        "language": "en",
        "url": "https://nairobi-echis.health.go.ke/#/tasks/x~2024-10-01~chp-performance-self-assessment-Nairobi",
        "version": "4.11.0",
        "source": "automatic",
      },
      "info": {
        "message": "Failed during the form \"chp_performance_self_assessment\" rendering : Invalid XML: <html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n",
        "stack": "Error: Failed during the form \"chp_performance_self_assessment\" rendering : Invalid XML: <html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n\n    at https://nairobi-echis.health.go.ke/main.js:1:3105501\n    at Generator.throw (<anonymous>)\n    at E (https://nairobi-echis.health.go.ke/main.js:1:1404891)\n    at _ (https://nairobi-echis.health.go.ke/main.js:1:1405129)\n    at H.invoke (https://nairobi-echis.health.go.ke/polyfills.js:1:10947)\n    at ne.run (https://nairobi-echis.health.go.ke/polyfills.js:1:6297)\n    at https://nairobi-echis.health.go.ke/polyfills.js:1:21137\n    at H.invokeTask (https://nairobi-echis.health.go.ke/polyfills.js:1:11565)\n    at ne.runTask (https://nairobi-echis.health.go.ke/polyfills.js:1:6927)\n    at t (https://nairobi-echis.health.go.ke/polyfills.js:1:13619)"
      },
      "arguments": [
        "\"Error loading form.\"",
        "\"Error: Failed during the form \\\"chp_performance_self_assessment\\\" rendering : Invalid XML: <html>\\r\\n<head><title>500 Internal Server Error</title></head>\\r\\n<body>\\r\\n<center><h1>500 Internal Server Error</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n\\n    at https://nairobi-echis.health.go.ke/main.js:1:3105501\\n    at Generator.throw (<anonymous>)\\n    at E (https://nairobi-echis.health.go.ke/main.js:1:1404891)\\n    at _ (https://nairobi-echis.health.go.ke/main.js:1:1405129)\\n    at H.invoke (https://nairobi-echis.health.go.ke/polyfills.js:1:10947)\\n    at ne.run (https://nairobi-echis.health.go.ke/polyfills.js:1:6297)\\n    at https://nairobi-echis.health.go.ke/polyfills.js:1:21137\\n    at H.invokeTask (https://nairobi-echis.health.go.ke/polyfills.js:1:11565)\\n    at ne.runTask (https://nairobi-echis.health.go.ke/polyfills.js:1:6927)\\n    at t (https://nairobi-echis.health.go.ke/polyfills.js:1:13619)\""
      ],
      "log": [
        {
          "level": "error",
          "arguments": "[\"Error loading form.\",\"Error: Failed during the form \\\"chp_performance_self_assessment\\\" rendering : Invalid XML: <html>\\r\\n<head><title>500 Internal Server Error</title></head>\\r\\n<body>\\r\\n<center><h1>500 Internal Server Error</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n<!-- a padding to disable MSIE and Chrome friendly error page -->\\r\\n\\n    at https://nairobi-echis.health.go.ke/main.js:1:3105501\\n    at Generator.throw (<anonymous>)\\n    at E (https://nairobi-echis.health.go.ke/main.js:1:1404891)\\n    at _ (https://nairobi-echis.health.go.ke/main.js:1:1405129)\\n    at H.invoke (https://nairobi-echis.health.go.ke/polyfills.js:1:10947)\\n    at ne.run (https://nairobi-echis.health.go.ke/polyfills.js:1:6297)\\n    at https://nairobi-echis.health.go.ke/polyfills.js:1:21137\\n    at H.invokeTask (https://nairobi-echis.health.go.ke/polyfills.js:1:11565)\\n    at ne.runTask (https://nairobi-echis.health.go.ke/polyfills.js:1:6927)\\n    at t (https://nairobi-echis.health.go.ke/polyfills.js:1:13619)\"]",
          "time": "2024-10-02T06:39:53.754Z"
        },
        {
          "level": "info",
          "arguments": "[\"RulesEngine Status: Enabled\"]",
          "time": "2024-10-02T06:39:49.493Z"
        },
        {
          "level": "info",
          "arguments": "[\"Initiating changes watch (meta=true)\"]",
          "time": "2024-10-02T06:39:48.559Z"
        },
        {
          "level": "info",
          "arguments": "[\"Initiating changes watch (meta=false)\"]",
          "time": "2024-10-02T06:39:48.551Z"
        },
        {
          "level": "info",
          "arguments": "[\"Persistent storage denied: storage may be cleared by the UA under storage pressure.\"]",
          "time": "2024-10-02T06:39:47.953Z"
        }
      ],
      "type": "feedback"
    },
```

**To Reproduce**

**Expected behavior**
No crash

**Logs**

**Screenshots**

**Environment**
- Instance: nairobi-echis.health.go.ke
- App: cht-core? cht-conf
- Version: 4.11 or conf  3.21.4

**Additional context**
No idea what could lead to this. Chf-conf bug? 500 request when downloading form html from server? 
It seemed to persist for the user (5x similar feedback docs) but was not widespread across the project

**Comment by dianabarsan** [comment]
>  500 request when downloading form html from server?

I don't see how this is possible. We use a `bulkGet` request, which will inline attachment content for a collection of documents in a single response body, we don't do individual requests to get one single attachment. 

https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/replication.service.ts#L75 

The only user that would request a form attachment individually is an online user. 
Is this user an online user?

**Comment by kennsippell** [comment]
She is an offline user... Quite weird

**Comment by dianabarsan** [comment]
The way that PouchDb implements bulkGet is that they test it against the target database, and then permanently mark it as supported or unsupported, depending on whether this one first try is successful or not. 
If not supported, PouchDb reverts to a one-by-one doc get request, which would request attachment individually, and it seems that saving the error body as the attachment data is what PouchDb does. (I found the code in the compiled version of pouchdb-browser, but having a hard time finding the links to actual pouchdb repo code). 

The check is done once per session, as far as I can tell, so it would not persist beyond a browser refresh. But the doc itself would persist on the user's device even after the faulty download. 

The fact that the server responded with an error on the _bulk_get and then with another error on the get attachment is just such a coincidence.

**Comment by dianabarsan** [comment]
I've validated this - I edited two API endpoints to always respond with an error: 
- the offline user _bulk_get endpoint 
- the offline user get attachment endpoint

I'm seeing an error when loading the form: 
```
feedback.service.ts:179 Error loading form. Error: Failed during the form "death_report" rendering : Syntax error, unrecognized expression: {"error":"bad_request","reason":"Invalid rev format"}
    at form.service.ts:183:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _throw (asyncToGenerator.js:20:1)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Zone.run (zone.js:130:43)
    at zone.js:1260:36
    at _ZoneDelegate.invokeTask (zone.js:403:31)
    at Zone.runTask (zone.js:174:47)
    at drainMicroTaskQueue (zone.js:582:35)
feedback.service.ts:188 
```

Where `{"error":"bad_request","reason":"Invalid rev format"}` is the exact JSON content that my get attachment endpoint is sending back. Corresponding feedback doc also got created.

**Comment by dianabarsan** [comment]
Massive edgecase here, created in the bowls of PouchDb implementation. I believe the main bug here is that PouchDb saves the attachment regardless of the response it gets from the server, be it an errored response. 
The fix should be in PouchDb! (I'll open an issue). 

A workaround for us would be to somehow force a re-sync of the form document when we fail to open it, because otherwise the user would be stuck with the faulty doc unless someone made a change to this form on the server or if they cleared their cache.

**Comment by dianabarsan** [comment]
PouchDb issue https://github.com/pouchdb/pouchdb/issues/8998
