### ISSUE TITLE
Flaky e2e test: Adding new language should add new translations

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9672]
**Describe the issue**
This test fails with: 
```
1) Adding new language should add new translations
[chrome 90.0.4430.72 linux #0-8] element ("aria/User settings") still not clickable after 15000ms
[chrome 90.0.4430.72 linux #0-8] Error: element ("aria/User settings") still not clickable after 15000ms
[chrome 90.0.4430.72 linux #0-8]     at async Object.openUserSettings (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:448:3)
[chrome 90.0.4430.72 linux #0-8]     at async Object.setLanguage (/home/runner/work/cht-core/cht-core/tests/page-objects/default/users/user-settings.wdio.page.js:23:3)
[chrome 90.0.4430.72 linux #0-8]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/translations/new-language.wdio-spec.js:55:5)
```

Test reports: 
```
element click intercepted: element click intercepted: Element <i class="fa fa-fw fa-user"></i> is not clickable at point (104, 93). Other element would receive the click: <div class="cdk-overlay-backdrop cdk-overlay-dark-backdrop cdk-overlay-backdrop-showing"></div>
```

Example run: 
https://github.com/medic/cht-core/actions/runs/12038353859/job/33567381462

**Comment by Shanmukha-Vardhan** [comment]
I'm Shanmukha, and I'm new to open-source contributions. I would love to contribute to your project. Could you please assign me an issue that I can work on? I'm eager to help out and learn more.

**Comment by jkuester** [comment]
@Shanmukha-Vardhan welcome to the world of open-source development!  Since you are new to the CHT code-base, I would not recommend starting with this issue since it could require some tricky debugging to understand how to resolve the issue. 😬 

Instead, I recommend checking out our [first time contributor documentation](https://docs.communityhealthtoolkit.org/community/contributing/first-time-contributors/) and have a look at some of the [Good First Issues](https://github.com/medic/cht-core/issues?q=is%3Aopen%20is%3Aissue%20label%3A%22Good%20first%20issue%22).  Feel free to drop a comment on any of these that are not yet assigned!  👍

**Comment by variantbyx** [comment]
I'd like to work on this issue. Please assign me.

**Comment by andrablaj** [comment]
Hi @TechieLukesh? Did you manage to progress on this issue? Feel free to reach out if you get stuck!

**Comment by dianabarsan** [comment]
I've fixed this in the wdio upgrade.
