### ISSUE TITLE
Flaky wdio test: Navigation functionality Navigation view as chw

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9689]
**Describe the issue**
This test fails in both mobile and core suites with the same error: 

```
[chrome 131.0.6778.85 linux #0-10]         as chw
[chrome 131.0.6778.85 linux #0-10]            ✖ "before all" hook for as chw
[chrome 131.0.6778.85 linux #0-10]
[chrome 131.0.6778.85 linux #0-10] 6 passing (23.7s)
[chrome 131.0.6778.85 linux #0-10] 1 failing
[chrome 131.0.6778.85 linux #0-10]
[chrome 131.0.6778.85 linux #0-10] 1) as chw "before all" hook for as chw
[chrome 131.0.6778.85 linux #0-10] element ("#password") still not displayed after 15000ms
[chrome 131.0.6778.85 linux #0-10] Error: element ("#password") still not displayed after 15000ms
[chrome 131.0.6778.85 linux #0-10]     at async setPasswordValue (/home/runner/work/cht-core/cht-core/tests/page-objects/default/login/login.wdio.page.js:132:3)
[chrome 131.0.6778.85 linux #0-10]     at async Object.login (/home/runner/work/cht-core/cht-core/tests/page-objects/default/login/login.wdio.page.js:24:3)
[chrome 131.0.6778.85 linux #0-10]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/navigation/navigation.wdio-spec.js:76:9)
```

Example run: https://github.com/medic/cht-core/actions/runs/12154250603/job/33894141551

**Comment by ShivamGupta2003** [comment]
@dianabarsan, @lorerod , Hey i wanted to work on this project. Could you please assign this task to me.

**Comment by lorerod** [comment]
Hi @ShivamGupta2003, thanks for your interest here! This issue needs a bit more context with our wdio test setup, so it’s not the best fit to start with as a first-time contributor. We have others that are more prepared for new contributors. Please have a look at our [First time Contributor docs](https://docs.communityhealthtoolkit.org/community/contributing/first-time-contributors/) and/or the [good first issues](https://github.com/search?q=org%3Amedic+label%3A%22Good+first+issue%22++&type=issues&state=open), which have a proper design in place and are ready to be implemented. Let me know if you find something you’d like to work on there.

**Comment by dianabarsan** [comment]
I've fixed this in the wdio upgrade.
