### ISSUE TITLE
Crash when loading tasks/targets: Cannot read properties of undefined (reading '_rev')

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9704]
**Describe the bug**
Crash

**To Reproduce**
Crash is in `J=>!(!q && J._rev`

```
                commitTargetDoc: (B,U,{userContactDoc: H, userSettingsDoc: G},q)=>{
                    const z = null == H ? void 0 : H._id
                      , Y = null == G ? void 0 : G._id
                      , K = `target~${U}~${z}~${Y}`;
                    return k.get(K).catch(J=>{
                        if (404 === J.status)
                            return {
                                _id: K,
                                type: "target",
                                user: Y,
                                owner: z,
                                reporting_period: U
                            }
                    }
                    ).then(J=>!(!q && J._rev) && (J.targets = B,
                    J.updated_date = y().startOf("day").valueOf(),
                    k.put(J)))
                }
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/a2541ca5-0569-4389-b5bc-72973f816165)

**Environment**
- Instance: Nairobi
- App: webapp
- Version: 4.13

**Additional context**

**Comment by dianabarsan** [comment]
It looks like this is a minor issue here: https://github.com/medic/cht-core/blob/master/shared-libs/rules-engine/src/pouchdb-provider.js#L76 where we catch and handle 404 errors, but don't explicitly throw on other errors. 
What we are seeing here is a symptom of another pouchdb crash. 
Since the username is obfuscated, can someone who has access to the unedited image check this user's feedback docs and find the underlying PouchDb error? 

I will make the change to explicitly throw non 404 errors, so the next time this happens we will have visibility into the underlying error.

**Comment by kennsippell** [comment]
The user doesn't appear to have any telemetry docs in 2024. 

```
curl -X POST https://nairobi.echis.go.ke/medic-users-meta/_find -H 'Content-Type: application/json' -d '{ "selector": { "metadata.user": "mjanethiah", "type": "telemetry" } }'
```

All tabs are throwing errors ("Error fetching people" on contacts tab), so I'm guessing `IDBDatabase` connection closing. I'll look deeper with a SQL query.

**Comment by kennsippell** [comment]
Sorry `_find` just has a default limit of 25.  Confirmed this is a global database failure.

```
        {
          "level": "error",
          "arguments": "[\"Error getting targets\",\"TypeError: Cannot read properties of undefined (reading '_rev')\\n    at https://nairobi-echis.health.go.ke/main.js:1:1295107\\n    at H.invoke (https://nairobi-echis.health.go.ke/polyfills.js:1:10947)\\n    at ne.run (https://nairobi-echis.health.go.ke/polyfills.js:1:6297)\\n    at https://nairobi-echis.health.go.ke/polyfills.js:1:21137\\n    at H.invokeTask (https://nairobi-echis.health.go.ke/polyfills.js:1:11565)\\n    at ne.runTask (https://nairobi-echis.health.go.ke/polyfills.js:1:6927)\\n    at t (https://nairobi-echis.health.go.ke/polyfills.js:1:13619)\\n    at F.invokeTask [as invoke] (https://nairobi-echis.health.go.ke/polyfills.js:1:12649)\\n    at ee (https://nairobi-echis.health.go.ke/polyfills.js:1:25336)\\n    at te (https://nairobi-echis.health.go.ke/polyfills.js:1:25628)\"]",
          "time": "2024-12-05T12:06:47.966Z"
        },
        {
          "level": "error",
          "arguments": "[\"Error selecting contact\",\"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.\\n    at ml (https://nairobi-echis.health.go.ke/main.js:1:992425)\\n    at te._get (https://nairobi-echis.health.go.ke/main.js:1:999872)\\n    at Xr.<anonymous> (https://nairobi-echis.health.go.ke/main.js:1:966828)\\n    at Xr.<anonymous> (https://nairobi-echis.health.go.ke/main.js:1:943156)\\n    at Xr.<anonymous> (https://nairobi-echis.health.go.ke/main.js:1:1821)\\n    at https://nairobi-echis.health.go.ke/main.js:1:942442\\n    at new r (https://nairobi-echis.health.go.ke/polyfills.js:1:22887)\\n    at Xr.<anonymous> (https://nairobi-echis.health.go.ke/main.js:1:942339)\\n    at Xr.get (https://nairobi-echis.health.go.ke/main.js:1:1821)\\n    at https://nairobi-echis.health.go.ke/main.js:1:2322925\"]",
          "time": "2024-12-05T12:06:43.360Z"
        },
```
